molgenis/molgenis-emx2

apps/catalogue/src/views/CatalogueView.vue
make sure reactive var networks is declared before usage in template
=> fix: null pointer in catalogue-view

apps/catalogue/src/store/actions.js, apps/catalogue/src/store/getters.js, apps/catalogue/src/store/mutations.js, apps/catalogue/src/store/state.js, apps/catalogue/src/views/VariableExplorer.vue, apps/catalogue/src/views/VariablesDetailsView.vue
- Add search box to explorer view
- Show list of variables found
- Inform user when searching or empty search result
=> feat: search variables

apps/catalogue/src/components/VariableDetails.vue, apps/catalogue/src/components/VariableListItem.vue, apps/catalogue/src/main.js, apps/catalogue/src/views/VariableDetailView.vue, apps/catalogue/src/views/VariableExplorer.vue
- Add single variable view
- Add breadcrumb to improve wayfinding
=> feat: single variable detail view

backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqlDatabaseFields.java
Make sure schema is unique and use unique name to check schema is deleted
Closes #168
=> Fix unstable test

backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqlDatabaseFields.java, gradle.properties
Run tests in serial cause postgres can not handle multiple java clients
- Revert making test 'thread save'
=> chore: run tests in serial

apps/catalogue/src/views/VariableExplorer.vue
repeated variable harmonization is not supported by grapql backend, remove until we have a work around in place
=> feat: Remove harmonization tab

apps/catalogue/README.md, apps/catalogue/package.json, apps/catalogue/src/components/VariableListItem.vue, apps/catalogue/src/store/actions.js, apps/catalogue/src/store/query/variableDetails.gql, apps/catalogue/src/views/ResourceHarmonizationDetails.vue, apps/catalogue/src/views/SingleVarDetailsView.vue, apps/catalogue/src/views/SingleVarHarmonizationView.vue, apps/catalogue/src/views/VariableDetailView.vue, apps/catalogue/src/views/VariableExplorer.vue, apps/catalogue/vue.config.js, apps/yarn.lock
Show mapping details per repeat
- Fetch data via views ( instead of using vuex )
- Move query to separate file ( for readability and re-use)
- Extend vue conf to allow loading graphql/gql files
- Add spinners ( less caching is done when not using vuex)
=> feat: show mapping details per repeat

apps/catalogue/src/views/ResourceHarmonizationDetails.vue, apps/catalogue/src/views/SingleVarDetailsView.vue, apps/catalogue/src/views/SingleVarHarmonizationView.vue, apps/catalogue/src/views/VariableDetailView.vue
- Add resource and version to query
=> fix: fix issue where mapping where not being shown

apps/catalogue/src/store/actions.js, apps/catalogue/src/store/query/databanks.gql, apps/catalogue/src/store/repository/databankRepository.js, apps/catalogue/src/views/SingleVarDetailsView.vue
- Add table to SingleVar view
- Fetch all cohort via repository ( use repo to avoid code duplication)
- Move query to separate file
=> feat: add harmonization summary per variable

apps/catalogue/src/store/actions.js, apps/catalogue/src/store/mutations.js, apps/catalogue/src/views/VariablesDetailsView.vue
- add scroll listner to var detail view
- use offset to fetch aditional vars is bottom of page is reached
=> feat: Add infinite scroll for variable list

apps/styleguide/src/tree/_TreeItem.vue, apps/styleguide/src/tree/_TreeLevel.vue
- smaller font
- place chevron in front of label 
- margin between parent and child ( if child is shown)
=> feat: set of small ui fixes to improve tree ux

apps/styleguide/src/forms/InputRef.vue
bind label for prop to input to select input by clicking label
=> fix: label click should select item

apps/catalogue/src/store/repository/variableRepository.js, apps/catalogue/src/views/ResourceHarmonizationDetails.vue, apps/catalogue/src/views/SingleVarDetailsView.vue, apps/catalogue/src/views/SingleVarHarmonizationView.vue, apps/catalogue/src/views/VariableDetailView.vue
Move data fetching to repository
Use repository from vue's
=> fix: Remove duplicate code

apps/catalogue/src/components/VariableDetails.vue, apps/catalogue/src/components/VariableListItem.vue, apps/catalogue/src/store/actions.js, apps/catalogue/src/store/query/variableDetails.gql
- note: code duplication on purpose, still up in the air if list view should use same component and query as detail view
=> feat: show permitted values ( if set)

apps/styleguide/src/forms/ButtonDropdown.vue, apps/styleguide/src/layout/MolgenisMenu.vue
if drop down is used as menu item add menu link class to style as menu item
=> fix: fix sub menu header

gradle.properties
add work around for gradle spotless plugin
see details at: https://github.com/diffplug/spotless/issues/693
=> fix: fix compatibility with jdk-16

apps/catalogue/src/App.vue, apps/catalogue/src/components/CollectionEventsList.vue, apps/catalogue/src/components/Conditions.vue, apps/catalogue/src/components/DatasourceList.vue, apps/catalogue/src/components/HarmonizationDefinition.vue, apps/catalogue/src/components/PartnersList.vue, apps/catalogue/src/components/SubcohortList.vue, apps/catalogue/src/components/VariableDetails.vue, apps/catalogue/src/main.js, apps/catalogue/src/store/query/fromVariableDetails.gql, apps/catalogue/src/store/repository/variableRepository.js, apps/catalogue/src/views/.graphqlconfig, apps/catalogue/src/views/CatalogueView.vue, apps/catalogue/src/views/CohortView.vue, apps/catalogue/src/views/DatabankView.vue, apps/catalogue/src/views/DatasourceView.vue, apps/catalogue/src/views/FromVariableDetails.vue, apps/catalogue/src/views/InstitutionView.vue, apps/catalogue/src/views/ModelView.vue, apps/catalogue/src/views/ResourceHarmonizationDetails.vue, apps/catalogue/src/views/ResourceListView.vue, apps/catalogue/src/views/VariableDetailView.vue, apps/styleguide/package.json, apps/yarn.lock, backend/build.gradle
[x] Added Cohorts to frontpage of catalogue;  refactored colors etc to make fit
[x] Added settings for ResourceListView to show Cohorts similar to need CohortenKampioen
[x] Added CohortsView, similar to needs CohortenKampioen
=> feat[catalogue]: extended homepage with Cohorts view

Jenkinsfile
change base img to gradle:jdk16-hotspot
remove apt get stuff
=> chore: Simplify Jenkins setup

apps/catalogue/src/components/VariableListItem.vue, apps/catalogue/src/views/VariablesDetailsView.vue
- change btn to li to make use of bootstrap defaults
Closes #317
=> fix: Fix variable explorer detail list style

apps/catalogue/vue.config.js, apps/dev-proxy.config.js, apps/pages/vue.config.js, apps/schema/vue.config.js, apps/settings/vue.config.js, apps/tables/vue.config.js, apps/updownload/vue.config.js
- allow override via env vars
- use dev server as default , with Catalogue_test as default schema
=> chore: control dev proxy from single file

apps/catalogue/src/components/VariableDetails.vue, apps/catalogue/src/components/harmonization/HarmonizationCell.vue, apps/catalogue/src/views/HarmonizationRow.vue, apps/catalogue/src/views/HarmonizationView.vue, apps/catalogue/src/views/SingleVarDetailsView.vue
- add icons
- add legend
- move harmonization cell render to component
- switch to using status ( [unmapped, complete, parial] for now)
- replace 'zna' with 'na'
=> feat: harmonization grid enhancement

docs/cat_cohort-data-manager.md
paar harmonization / harmonisation puntjes ;-), zinsopbouw, een spatie die miste, "so-called" iets omgebogen (werkt niet helemaal hetzelfde in het Engels)
=> chore: update cat_cohort-data-manager.md

docs/cat_network-data-manager.md
Paar spaties die ontbraken (één daarvan zit ook in de lijst wijzigingen in cohort data mgr stuk)
=> chore: update cat_network-data-manager.md

docs/cat_researcher.md
paar typo's, paar zinsopbouwdingen, plek waar ik het iets anders verwoord heb (kijk maar even: in de alinea over ELIXIR, plus de zin die begint "Some networks use the analysis environment..."), shopping cart, paar -ization / -ize puntjes
=> docs: update cat_researcher.md

backend/molgenis-emx2/src/main/resources/log4j2.xml
sync default log line pattern with emx1 for use by filebeat
=> feat: Add date to logline

apps/styleguide/src/forms/InputRefback.vue
=> fix: InputRefback was not showing

docs/cat_cohort-data-manager.md, docs/cat_network-data-manager.md
-add link to 'how to fill out template' movie 
-checked all links
-plus some minor edits
=> feat: add movie to docs

apps/catalogue/src/main.js, apps/catalogue/src/views/ResourceListView.vue, apps/catalogue/src/views/SearchResourceView.vue, apps/styleguide/src/mixins/TableMixin.vue
- Add search view ( can be added to menu via settings)
- Make resourceView handle search param
- Pass initial TableMixin searchTerm via prop
=> feat: Resource search

apps/catalogue/src/components/CollectionEventsList.vue, apps/catalogue/src/views/CohortView.vue
- Replace ageMin, ageMax with ageCategories in gql query
=> feat: Add age categories to cohort detail view

apps/catalogue/src/components/SearchResource.vue, apps/catalogue/src/views/SearchResourceView.vue
Split into component and view to enable reuse of component by other components ( getting ready for dynamic home page)
=> chore: Split up SearchResourceView

apps/styleguide/src/mixins/TableMixin.vue
Trim the search term string before sending it to the backend
Closes #528
=> fix: Trim search

apps/styleguide/src/tables/ShowHide.vue, apps/styleguide/src/tables/TableExplorer.vue
to test: open a table that has columnType=FILE and see that you cannot show filter for it.
=> fix: shouldn't filter on columnType=file (e.g. logo). closes #508

apps/styleguide/src/layout/MolgenisMenu.vue, apps/styleguide/src/layout/MolgenisSession.vue, apps/styleguide/src/layout/MolgenisSignin.vue, apps/styleguide/src/layout/MolgenisSignup.vue, apps/tables/src/App.vue, apps/tables/src/components/ListTables.vue, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java, backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/GraphqlApi.java
see commit messages for the other related changes.
=> fix: signin and sign out should work even when permission denied to a schema

apps/central/src/App.vue
=> fix: have tables menu item path differ form api path

apps/styleguide/src/layout/MolgenisSignin.vue
Reload page to refresh theme after login
Closes #622
=> fix: Fix theme issue

data/datacatalogue/molgenis.csv, docs/catalogue/cat_admin.md
*CollectionEvents.standardizedTools changed to ref_array which is searchable.
*description for Cohorts.releaseType updated
=> fix: columnType of standardizedTools to ref_array

.circleci/config.yml, .jenkins/build-pod.yaml, backend/build.gradle, build.gradle, docs/molgenis/run_java.md
Do we want to update to jdk17? I suppose we do, it is lts.
=> feat: update build dependency to jdk17

backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestMergeAlter.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlColumnExecutor.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlSchema.java
=> fix: cannot change from ontology_array to ref_array. closes #711

data/datacatalogue/molgenis.csv, docs/catalogue/cat_admin.md
=> fix[catalogue]: Institution.typeOther should be of type text

apps/catalogue/src/components/detailView/SectionField.vue
=> fix: in catalogue detailview ref fields should become hyperlinks

apps/catalogue/src/components/detailView/SectionField.vue, backend/molgenis-emx2-io/src/test/java/org/molgenis/emx2/io/TestCohortCatalogue.java, data/datacatalogue/RWEcatalogue/AreasOfInformation.csv, data/datacatalogue/molgenis.csv, docs/catalogue/cat_admin.md
Please to test
- Download/upload minerva from production
- Add a few tests on the new columns and values (see the 
Changes:
* Added RWEresources.approvalForPublication
* Added Databanks.populationSize with nested table PopulationSizes
* Updated description of RWEresources.counts
* Added areas of information to Dispensings list
'
ATC,,Dispensings included
RxNorm,,Dispensings included
EphMRA,,Dispensings included
ALT,,Dispensings included
DrugBank,,Dispensings included
Not coded (Free text),,Dispensings included
Dispensings other,,Dispensings included
'
* added fields Database.
=> Feat: added new fields and codes for Minerva

apps/styleguide/src/index.js, apps/styleguide/src/tables/RowButtonAdd.vue, apps/styleguide/src/tables/RowButtonClone.vue, apps/styleguide/src/tables/RowButtonDelete.vue, apps/styleguide/src/tables/RowButtonEdit.vue, apps/styleguide/src/tables/RowEditModal.vue, apps/styleguide/src/tables/TableExplorer.vue
To test: in table explorer you see for each row a clone button.
=> feat: add row clone button to table view

apps/styleguide/src/forms/InputRefback.vue, apps/styleguide/src/tables/RowEditModal.vue
previous copy button was not shown in tables inside the forms. Now it should be and work.
=> feat: add copy button to refback table in the forms

apps/catalogue/src/components/detailView/SectionField.vue
=> fix: text fields were not shown in catalogue details views

apps/catalogue/src/views/CohortView.vue
=> fix[catalogue]: in cohorts detail, countries were shown for regions

apps/styleguide/src/layout/MolgenisMenu.vue
component expects bool instead of string
=> fix: isMenuItem is a boolean

apps/dev-proxy.config.js, apps/styleguide/styleguide.config.js
More generic initial dev proxy config
Allows for re-use and syncing multiple dependant app and libs
=> chore: Update dev proxy config

apps/styleguide/src/layout/ReadMore.vue
should not lead to open in catalogue cohort or databak list. #closes #822
=> fix: show more. #closes #822

backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisWebservice.java, backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
Add path to handle ```/robots.txt ``` request
=> feat: add default robots.txt path handler

apps/central/src/components/Admin.vue
Remove modal is not visible as the modal css breaks the layout ( when hidden)
Closes #774
=> fix: Fix users list scroll

apps/dev-proxy.config.js, apps/styleguide/src/display/LinksList.vue, apps/styleguide/src/forms/InputOntology.vue, apps/styleguide/src/forms/InputRef.vue, apps/styleguide/src/forms/InputRefback.vue, apps/styleguide/src/layout/VueTemplate.vue, apps/styleguide/src/mixins/TableMetadataMixin.vue, apps/styleguide/src/mixins/TableMixin.vue, apps/styleguide/src/tables/FilterSidebar.vue, apps/styleguide/src/tables/RowButtonAdd.vue, apps/styleguide/src/tables/RowFormInput.vue, apps/styleguide/src/tables/TableExplorer.vue, apps/styleguide/src/tables/TableSearch.vue
How to test:
- go to https://preview-pr-emx2-854.dev.molgenis.org
- sign in (or make pet store schema public)
- go to styleguide
- open developer console and see no errors (i.e. red marked console entries)
=> fix: styleguide should not give errors in console

apps/styleguide/src/layout/MolgenisSession.vue
If a user is not allowed to access schema data, setting where not fetched
this PR includes a settings fetch a the database level ( allowed for all users)
Closes #866
=> fix: Fetch settings at db level in addition to schema level

apps/catalogue/src/filters.js, apps/catalogue/src/views/cohorts/CohortView.vue, apps/catalogue/src/views/cohorts/CollectionEvent.vue, apps/catalogue/src/views/cohorts/Subcohort.vue
- fix cohort type
- use not available instead of n/a
=> fix: Cohort view details

apps/catalogue/src/main.js
note: 'old' view can be viewed by changing the route to '../alt-cohorts/...'
=> feat: Switch to using alternative cohort view

.circleci/config.yml, apps/Dockerfile, apps/build.gradle, apps/nuxt-ssr/package.json, apps/package.json, apps/yarn.lock, build.gradle
Build a docker images for the ssr-catalogue ( for deployment) 
if setup is done add to circle CI config 
```      # push ssr-catalogue to repo
- run: ./gradlew dockerPush
=> fix: Use docker plugin to have gradle build ssr catalogue image

apps/catalogue/src/main.js
=> fix: Stop search from triggering route change

apps/styleguide/src/forms/InputRefback.vue, apps/styleguide/src/layout/LayoutModal.vue
=> fix: scrollbar should be shown for large modal screens

backend/molgenis-emx2/src/main/java/org/molgenis/emx2/ColumnType.java, backend/molgenis-emx2/src/main/java/org/molgenis/emx2/Row.java, backend/molgenis-emx2/src/main/java/org/molgenis/emx2/utils/TypeUtils.java, backend/molgenis-emx2/src/test/java/org/molgenis/emx2/TestTypeUtils.java
How to test
* will trim spaces in csv and excel (except for columnType=text)
* will trim spaces in when you edit data via web forms (except for columnType=text)
N.B. is implemented server side so is trimmed on every insert, update
=> feat: trim string values and interpret empty string value as null M8771

.github/workflows/github_build_action.yml
All build steps are here, except 'release'.
If we would stop JenkinsFile it **should** work to add release but might want to test that.
=> build: add github actions

apps/styleguide/src/forms/InputOntology.vue, apps/styleguide/src/forms/InputOntologySubtree.vue
Closes #970. (see there for example data).
- faster rendering
- faster select
- faster search
- faster deselect
n.b. only thing we didn't touch was speed on the server but that seems to be fast enough?
=> fix: Large ontologies do not load in forms

apps/styleguide/src/layout/ReadMore.vue
Prevent default browser href behaviour, for readmore action link
Closes #1033
=> fix: Fix read more link

apps/styleguide/src/tables/RowEditModal.vue
=> fix: clone button didn't work. closes #1032

apps/styleguide/src/forms/InputString.vue, apps/styleguide/src/forms/_appendClear.vue, apps/tables/src/components/ListTables.vue
Also removes a unnecessary "search" text
=> fix: remove broken inline string edit clear button

apps/catalogue/src/components/RefbackTable.vue
use dataDictionary instead of resource link
Closes #1028
=> fix: 1028 broken link due to model change

apps/tables/src/components/ListTables.vue
Reverts molgenis/molgenis-emx2#1076
=> Revert "chore: make not yet implemented download methods no longer clickable"

apps/nuxt-ssr/pages/_schema/ssr-catalogue/_resource/index.vue, apps/nuxt-ssr/pages/_schema/ssr-catalogue/index.vue
Use dynamic path to allow for schema and app name
=> fix: ssr links to data definitions

apps/molgenis-components/src/components/forms/BaseInput.vue, apps/molgenis-components/src/components/forms/InputPassword.vue, apps/molgenis-components/src/components/forms/InputString.vue, apps/molgenis-components/src/components/organisms/SignInForm.vue, apps/molgenis-components/src/docs/forms/InputPassword.vue, apps/molgenis-components/src/docs/forms/InputString.vue
add comments describing the BaseInput props comments and there relation to emx2 fields
=> chore: BaseInput props comments

apps/molgenis-components/index.html, apps/molgenis-components/lib/main.js, apps/molgenis-components/src/client/client.js, apps/molgenis-components/src/components/forms/BaseInput.vue, apps/molgenis-components/src/components/forms/FormGroup.vue, apps/molgenis-components/src/components/forms/InputPassword.vue, apps/molgenis-components/src/components/forms/InputSearch.vue, apps/molgenis-components/src/components/forms/InputString.vue, apps/molgenis-components/src/docs/forms/InputSearch.vue, apps/nuxt-ssr/nuxt.config.js, apps/nuxt-ssr/pages/_schema/ssr-catalogue/cohorts/index.vue
Add SearchInput to molgenis component lib
Use searchInput in cohorts view
_additional fixes:_ 
- components lib index page; use current bootstrap version
- components client.js; use safe methods for checking has own prop
=> feat: Add search to ssr cohorts view

apps/.prettierrc.js
so we don't get reformatting on every commit
=> chore: reset prettier to default

apps/styleguide/src/tables/RowEditModal.vue
Note: most changes are formatting; fix is on line 156 where it should be 'name' instead of 'id'
=> fix: columns with spaces were not visible in nested forms

apps/build.gradle
to rule out these have caused any issues
=> fix: undo changes to build.gradle

apps/molgenis-components/src/App.vue
make sure parent is 100% and parent has no visible overflow
=> fix: Fix issue with double scrollbar in some browsers

apps/molgenis-components/lib/main.js, apps/molgenis-components/src/components/layout/SignInForm.vue, apps/molgenis-components/vite.config.js
and rename MolgenisSignIn to SignInForm
=> fix: Fix components build config

apps/molgenis-components/docs-plugin.js, apps/molgenis-components/package.json
fix issue where previously generated examples remain in docs folder
fix issue where previously generated showCase app does not get rebuild
=> fix: Cleanup generated folders before build

Jenkinsfile
bump version to trigger refresh
=> fix: bump chart version

Jenkinsfile
Reverts molgenis/molgenis-emx2#1231
=> Revert "fix: rollback chart bump"

build.gradle
Reverts molgenis/molgenis-emx2#1233
=> Revert "build: upgrade to helm v3"

apps/molgenis-components/src/components/layout/Molgenis.vue, apps/settings/package.json, apps/settings/src/App.vue, apps/settings/src/components/Members.vue, apps/settings/src/components/MenuDesign.vue, apps/settings/src/components/MenuManager.vue, apps/settings/src/components/PageManager.vue
- Replace usage of styleguide components with molgenis-components
=> feat: Move settings app over to using molgenis-components

apps/molgenis-components/src/App.vue, apps/molgenis-components/src/components/filters/FilterInput.vue, apps/molgenis-components/src/components/filters/FilterSidebar.vue, apps/molgenis-components/src/components/filters/OntologyFilter.vue, apps/molgenis-components/src/components/forms/FormInput.vue, apps/molgenis-components/src/components/forms/InputOntology.vue
- add filter type
- fix issue where no scrollbar would be shown in focused view after page reload
=> feat: Add Ontology filter

.jenkins/build-pod.yaml
Reverts molgenis/molgenis-emx2#1307
=> Revert "build: update jenkins pod to jdk17"

apps/catalogue/src/components/NetworkCards.vue
single component should not override the global framework code 
Closes #1319
=> fix: fix framework styling

.jenkins/build-pod.yaml, Jenkinsfile
Reverts molgenis/molgenis-emx2#1312
=> build: update jenkins pod to jdk17

apps/settings/src/App.vue, apps/settings/src/components/SettingsManager.vue, apps/settings/src/main.js
add, edit, delete works for schema settings
~~note: fix read only in forms components ( other pr #1336 )~~
=> feat: Edit schema settings

apps/molgenis-components/src/components/forms/InputDate.vue, apps/molgenis-components/src/components/forms/InputDecimal.vue, apps/molgenis-components/src/components/forms/InputInt.vue, apps/molgenis-components/src/components/forms/InputLong.vue, apps/molgenis-components/src/components/forms/baseInputs/BaseInputDate.vue, apps/molgenis-components/src/components/forms/baseInputs/BaseInputDecimal.vue, apps/molgenis-components/src/components/forms/baseInputs/BaseInputInt.vue
pass on missing props to style input fields
=> fix: Fix required field styling

apps/updownload/src/components/Import.vue, backend/build.gradle, backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/CsvApi.java, backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisWebservice.java, backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
CSV import of data table now works. Since the filename is lost because there is no multipart form input, the target table is found by matching column names instead.
=> fix: for #894

.circleci/config.yml, .docker/initdb.sql, .github/workflows/github_build_action.yml.bak, .jenkins/build-pod.yaml, Jenkinsfile, docker-compose.yml, helm-chart/values.yaml
Reverts molgenis/molgenis-emx2#1366
=> fix: docker compose to use postgres/molgenis instead of postgres/molgenisdb

apps/molgenis-components/index.html, apps/molgenis-components/src/components/forms/RowEdit.vue, apps/nuxt-ssr/nuxt.config.js
@molgenis/expressions can not be loadend into node context
remove untill replacement is created
related to https://github.com/molgenis/molgenis-expressions/issues/14
=> fix: Fix ssr render capability

apps/molgenis-components/index.html, apps/nuxt-ssr/nuxt.config.js
explicitly set cors header via script param
=> fix: fetch expressions from external server

apps/catalogue/src/views/TableView.vue
=> fix: 1288-table-mapping-issue

apps/build.gradle, apps/molgenis-components/package.json, apps/molgenis-components/src/components/utils.test.js, apps/yarn.lock
- add lib dep
- configure test setup
- call via gradle
=> chore: Add vite test lib

backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/beaconv2/endpoints/genomicvariants/GenomicVariantsResponse.java
fix: code warnings in GenomicVariants response that were raising flags when building
=> fix: code warnings in GenomicVariants response

docs/molgenis/run_java.md
seperate between opening postgres console and pasting…
=> docs: clarify postgres initialization 

data/datacatalogue/stagingCohortsUMCG/molgenis.csv
Apply change to model to include 2.6 features
=> feat: update model to 2.6

data/datacatalogue/stagingCohortsUMCG/molgenis.csv
For the staging area this is a no op update, to keep the version in sync with de catalogue model
=> chore: Update model from 2.6 to 2.7

apps/molgenis-components/vite.config.js
Fix issue where call to expression.js was not proxied
=> fix: add expression.js call to proxy list

apps/molgenis-components/src/components/forms/InputString.vue, apps/styleguide/package.json
Null check string field value before length check
Closes #1514
=> fix: null-check-before-use

apps/central/src/components/Groups.vue, apps/central/src/components/LastUpdateField.vue, apps/central/src/components/SchemaCreateModal.vue, apps/central/src/components/SchemaDeleteModal.vue, apps/central/src/components/SchemaEditModal.vue, backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlSchemaFieldFactory.java, backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestChangelog.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlSchema.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlSchemaMetadata.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlSchemaMetadataExecutor.java, backend/molgenis-emx2/src/main/java/org/molgenis/emx2/Schema.java
- Add limit option to changes query
- Call changes query for each schema if use has the rights to do so
- Show changes in groups table and add link to changelog
-  [x] Sort by update date
-  [ ] format date with things like today at 11.30 and yesterday
=> feat: 9286 show last updated schema

backend/build.gradle, backend/molgenis-emx2-webapi/build.gradle
we must be careful to wait for them to update properly.
issue is caused by stricter slf4j rules.
=> fix: slf4j logging was broken since pac4j and sass updates, undo

apps/central/src/main.js, apps/helloworld/src/main.js, apps/pages/src/main.js, apps/settings/src/main.js
Add this missing import for the component specific css ( this gets bundled into the app.css by the app build)
=> fix: All missing component lib style import

apps/central/src/components/LastUpdateField.vue
fix: update the route name from log to changelog
=> fix: fix app link

apps/molgenis-components/src/components/forms/InputOntology.vue
=> fix: 1586 pass on override limit to client

docker-compose.yml
credentials are now fixed so that docker-compose works
=> fix: docker-compose used the wrong credentials

apps/molgenis-components/src/components/forms/ConfirmModal.vue, apps/molgenis-components/src/components/forms/EditModal.vue, apps/molgenis-components/src/components/forms/InputRefBack.vue, apps/molgenis-components/src/components/forms/InputRefSelect.vue, apps/molgenis-components/src/components/forms/RowEdit.vue
- add actions handlers to table buttons
- fix passing visible columns
=> fix: inputRefback

apps/molgenis-components/src/components/tables/TableExplorer.vue
Add ButtonAlt import in TableExplorer
=> fix: add missing button import

backend/build.gradle
Reverts molgenis/molgenis-emx2#1581
=> Revert "fix(deps): update org.pac4j"

backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPoint.java, backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPointDataset.java, backend/molgenis-emx2-semantics/src/test/java/org/molgenis/emx2/semantics/fairdatapoint/FAIRDataPointBadDistributionInDatasetTest.java, backend/molgenis-emx2-semantics/src/test/java/org/molgenis/emx2/semantics/fairdatapoint/FAIRDataPointTest.java
Refactor of FDP components to allow a full output test to compare expected vs actual content (instead of "contains yes/no")
=> Rework FDP for better testability

apps/molgenis-components/src/components/tables/Pagination.vue
Small graphical fix
Pagination buttons gray out and events does not fire if navigation is impossible. ( on first page and last page)
=> fix: add the disabled status in the Pagination component

apps/molgenis-components/src/components/forms/EditModal.vue, apps/molgenis-components/src/components/forms/InputRefBack.vue
to test , add row via refback ( for example add row to orders via Pet table ( edit pet, add order)
=> fix: add row via ref-back

.circleci/config.yml, Jenkinsfile
We gonna merge this once the 'previews' are working again.
=> fix: switch back release to jenkins

.circleci/config.yml, Jenkinsfile
Reverts molgenis/molgenis-emx2#1626
=> Revert "fix: switch back release to jenkins"

backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestCreateBasicDataColumnTypeColumns.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java
=> fix: EQUALS not supported for type EMAIL

apps/molgenis-components/src/components/forms/ArrayInput.vue, apps/molgenis-components/src/components/forms/InputBoolean.vue, apps/molgenis-components/src/components/forms/InputDate.vue, apps/molgenis-components/src/components/forms/InputDecimal.vue, apps/molgenis-components/src/components/forms/InputInt.vue, apps/molgenis-components/src/components/forms/InputLong.vue, apps/molgenis-components/src/components/forms/InputText.vue
BOOLEAN_ARRAY and REF_ARRAY are not included yet and should be done in a separate pull request, as they need a more custom solution if we want them to work.
=> feat: add array options for most inputs

backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlColumnExecutor.java
Added semantics to describe the columns for OntologyTerms. Also improved the field descriptions.
=> Added semantics for ontology term columns

apps/central/package.json, apps/molgenis-components/package.json, apps/yarn.lock
- sync vite versions across app
- remove unneeded vue 3 vite plugin
=> chore: clean up js dependencies

apps/molgenis-components/src/components/forms/ButtonDropdown.vue
=> fix: use toggle for dropDown use in menu

apps/molgenis-components/src/components/tables/Pagination.vue
- docs example should be valid vue 2 SFC ( single template root)
=> fix: fix pagination docs

backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/Migrations.java
new migration was put in wrong order
now new migration is added to the end
=> fix: migration order was wrong

data/datacatalogue/stagingCohorts/molgenis.csv
Changed
- Resources.institution to columnType ref_array
- Cohorts.studies to columnType refback
- Cohorts.networks to columnType refback
- Partners.institution to columnType ref
- Contributors.contact to columnType ref
- TableMappings.toDataDictionary to columnType ref
- TableMappings.toTable to columnType ref
- Cohorts.designDescription columnType text to lowercase
=> Cohort staging: Incorrect columnType for Resources, Cohorts and Contributions

apps/catalogue/package.json, apps/gendecs/package.json, apps/graphql-playground/package.json, apps/helloworld/package.json, apps/nuxt-ssr/package.json, apps/pages/package.json, apps/settings/package.json, apps/styleguide/package.json, apps/tables/package.json, apps/updownload/package.json, apps/yarn.lock
add vue cli deps to app dev depenency lsit as CI does not use global version
=> fix: fix missing ci dep issue

apps/molgenis-components/lib/main.js, apps/molgenis-components/src/components/forms/ConfirmModal.vue, apps/molgenis-components/src/components/organisms/RowAddButton.vue, apps/molgenis-components/src/components/organisms/RowCloneButton.vue, apps/molgenis-components/src/components/organisms/RowDeleteButton.vue, apps/molgenis-components/src/components/organisms/RowEditButton.vue
composition of button and edit modal configured to row edit
=> feat: add row actions button wrappers 

data/datacatalogue/stagingShared/molgenis.csv
=> chore: added version(2.8) to SharedStaging model

backend/molgenis-emx2-datamodels/src/test/java/org/molgenis/emx2/datamodels/TestLoaders.java, data/datacatalogue/stagingNetworks/molgenis.csv
update
- Version 2.3 to 2.8
added
- CollectionEvents.coreVariables
- Subcohorts.counts
- Subcohorts.comorbidity
- SubcohortCounts.subcohort
- SubcohortCounts.ageGroup
- SubcohortCounts.N total
- SubcohortCounts.N female
- SubcohortCounts.N male
- Networks.type
=> chore: update stagingNetwork model to v2.8

.jenkins/build-pod.yaml, Jenkinsfile
- setting limit only sets requests equal to limit
=> chore: Set jenkins pods resource limits

data/datacatalogue/stagingCohortsUMCG/molgenis.csv
- Cohorts.type to columnType ontology_array
- Cohorts.design to columnType ontology
- Cohorts.collectionType to columnType ontology_array
- CollectionEvents.startYear to columnType ontology
- CollectionEvents.startMonth to columnType ontology
- CollectionEvents.endYear to columnType ontology
- CollectionEvents.endMonth to columnType ontology
- SubcohortCounts.ageGroup to columnType ontology
=> fix columnType ref/ref_array to ontology/ontology_array UMCG cohort staging model

apps/package.json
revert nohoist as it does not solve the symlink issue
=> chore: revert nohoist

backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqSchemaFields.java, backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestQueryJsonGraph.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java
silly error on my end, because I failed to put the json splitter command in right place.
=> fix: groupBy failed to count distinct rows 

backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTable.java
=> fix: can't save row edits/updates

backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTable.java
=> Autoformatting fix

apps/molgenis-components/src/components/forms/InputRefSelect.vue, apps/molgenis-components/src/components/organisms/RowAddButton.vue, apps/molgenis-components/src/components/organisms/RowEditButton.vue, apps/molgenis-components/src/components/tables/TableSearch.vue
=> fix: Add missing crud options to search table

apps/molgenis-components/src/components/forms/InputRef.vue, apps/molgenis-components/src/components/forms/InputRefList.vue
Add edit actions to ref input table
Reload table data after edit modal is close
Reload options list after table is closed 
Closes #1787
=> fix: show edit actions in ref input table view

apps/catalogue/src/main.js
=> fix: catalogue vue3

apps/molgenis-components/src/components/filters/FilterInput.vue, apps/molgenis-components/src/components/filters/FilterSidebar.vue, apps/molgenis-components/src/components/forms/InputOntology.vue, apps/molgenis-components/src/components/forms/InputRefList.vue
Issue also applied to ref_array
closes #1795
=> fix: ontology filter doesn't update when wells are removed. closes #1795

backend/molgenis-emx2-webapi/build.gradle
Reverts molgenis/molgenis-emx2#1862
because of sl4j issue
=> Revert "fix(deps): update dependency de.larsgrefer.sass:sass-embedded-host to v1.9.0"

backend/molgenis-emx2-datamodels/src/test/java/org/molgenis/emx2/datamodels/TestLoaders.java, backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestCrossSchemaForeignKeysAndInheritance.java, backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestOntologyTableIsGenerated.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/ChangeLogExecutor.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlSchemaMetadataExecutor.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadataExecutor.java, backend/molgenis-emx2/src/main/java/org/molgenis/emx2/TableMetadata.java, backend/molgenis-emx2/src/main/java/org/molgenis/emx2/utils/ColumnSort.java
=> fix: prevend schema drop when ref depend on it (stop cascade)

apps/schema/src/components/Schema.vue, apps/schema/src/components/SchemaToc.vue
Place sticky pannels below dropdown
Place toc below headers
Closes #1785
=> fix: 1785 schema editor sticky panels

Jenkinsfile
update app id ( to same id as used in the preview)
=> chore: update app id for dev upgrade

backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlSchemaFieldFactory.java
Fixes the schema editor. 
s2r for the bug without the fix:
- login to emx2
- go the the schema manager of a schema e.g. the pet store
- try to add a new column (of any other edit)
- click save
=> fix: saving in the schema editor

backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/beaconv2/endpoints/individuals/ejp_rd_vp/EJP_VP_IndividualsQuery.java, backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/beaconv2/endpoints/individuals/ejp_rd_vp/NCITToGSSOSexMapping.java, backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/beaconv2/requests/BeaconQuery.java, backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/beaconv2/requests/Filter.java, backend/molgenis-emx2-semantics/src/test/java/org/molgenis/emx2/semantics/beaconv2/Beaconv2_ModelEndpointsTest.java
Changes to reach compliance Beaconized EJP-RD Virtual Platform API available at https://github.com/ejp-rd-vp/vp-api-specs.
- Ontology nomenclature was updated and moved to static variables
- Added support for value arrays (in addition to single values)
- Added support for special ontology filters that use the 'id' field to supply values (either array or single)
=> feat: Beaconized VP compliance

Jenkinsfile
use app name instead of chart name
=> chore: fix app name in rancher upgrade command

docs/molgenis/_sidebar.md, docs/molgenis/dev_beaconv2.md, docs/molgenis/dev_fairdatapoint.md, docs/molgenis/dev_rdf.md
Updated documentation for
- FAIR Data Point
New documentation for
- RDF
- Beacon v2
=> Feat: fairapidoc

apps/nuxt3-ssr/composables/fetchSetting.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/index.vue, docs/catalogue/_sidebar.md, docs/catalogue/cat_server_side-rendered.md
show under constriuction notice when 'CATALOGUE_NOTICE' setting is set
=> feat: under construction notice via settings

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/index.vue
=> fix: fix sort order

backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
Remove test that fails on some environments, probably due to parallel execution issues
=> Remove test with unpredictable behaviour

apps/nuxt3-ssr/components/SearchFilterGroupChild.vue
- just comment out  for now, discuss removing or adding flag later`
=> feat: remove the child count form the filter group render

apps/nuxt3-ssr/components/ReferenceCard.vue, apps/nuxt3-ssr/components/SearchFilterGroup.vue, apps/nuxt3-ssr/components/content/ContentBlockGeneralDesign.vue, apps/nuxt3-ssr/composables/fetchGql.ts, apps/nuxt3-ssr/composables/fetchOntology.ts, apps/nuxt3-ssr/composables/fetchSetting.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/index.vue
Backend no longer exposed ontologies via source schema Ontologies should be queried direct from there own schema
+ code formatting
=> fix: fix ontology fetch for breaking backend change

Jenkinsfile
allows for fixed reference handy for dev server
=> chore: add 'latest' tags for ssr image

apps/nuxt3-ssr/components/DefinitionList.vue, apps/nuxt3-ssr/components/content/ContentBlockGeneralDesign.vue, apps/nuxt3-ssr/interfaces/Icohort.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/cohorts/[cohort]/index.vue
add field design scematic to cohort data request
Add basic inline emx2 file link render
=> feat: add design schematic

Jenkinsfile
lock chart version als workaround for slow/cached chart repo
=> fix: dev upgrade

apps/nuxt3-ssr/components/content/ContentBlockAttachedFiles.vue, apps/nuxt3-ssr/gql/fragments/file.js, apps/nuxt3-ssr/interfaces/Icohort.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/cohorts/[cohort]/index.vue
- note: can be extended with light box later ( see design mockups)
=> feat: basic documents rendering for cohorts

backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java
motivation, in BBMRI-ERIC model the following query failed with 'name' unknown column error:
```{Biobanks{collections(orderby: {name:ASC}){name}}}```
Fix: move conversion of column identifier to column name for orderBy in helper function and use for both the root and the nested query handling.
closes #1971
=> fix: orderBy on nested tableds didn't convert ids to names properly

apps/nuxt3-ssr/gql/collectionEvent.js, apps/nuxt3-ssr/interfaces/Icohort.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/cohorts/[cohort]/collection-events/[collectionevent].vue
feat: Add standardizedTools and standardizedToolsOther to collectionEvent details
=> feat: Add standardizedTools and standardizedToolsOther 

apps/nuxt3-ssr/package.json, apps/yarn.lock
=> fix: revert nuxt version bump due to issue

apps/molgenis-components/src/client/client.ts, apps/molgenis-components/src/components/tables/AggregateTable.vue
- Use the api error message if we have it, it will have more details than the axios error.
- Show the error in the Aggregate table
=> fix: add better error messages; fix: show error in Aggregate table

apps/nuxt3-ssr/components/SideModal.vue, apps/nuxt3-ssr/tailwind.config.cjs, apps/nuxt3-ssr/tailwind.config.umcg.cjs
use theme variable instead of fixed color
=> fix: fix modal footer background color

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/index.vue
note: should be moved from app code into database
=> fix spelling error

backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqSchemaFields.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java
=> fix: aggregate sum/avg/etc should use column identifier instead of name

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/index.vue
=> fix: fix landing page card

apps/nuxt3-ssr/components/AppHeader.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/about.vue
Future todo: parameterize the about text.
=> feat: add about page specific for umcg

apps/nuxt3-ssr/components/CollectionEventDisplay.vue, apps/nuxt3-ssr/components/SubCohortDisplay.vue, apps/nuxt3-ssr/components/content/ContentBlockGeneralDesign.vue, apps/nuxt3-ssr/gql/collectionEvent.js, apps/nuxt3-ssr/gql/subcohort.js, apps/nuxt3-ssr/interfaces/Icohort.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/cohorts/[cohort]/collection-events/[collectionevent].vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/cohorts/[cohort]/index.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/cohorts/[cohort]/subcohorts/[subcohort].vue
Workaround for https://github.com/molgenis/molgenis-emx2/issues/2175
=> fix: move oderby from gql back into node

Jenkinsfile, helm-chart/templates/deployment.yaml, helm-chart/values.yaml
- pass MOLGENIS_INCLUDE_CATALOGUE_DEMO env var via helm cart
=> chore: load catalogue demo data on preview install

apps/nuxt3-ssr/app.vue, apps/nuxt3-ssr/error.vue
- and add page title for error page
=> fix: Add hash to error page style call

apps/nuxt3-ssr/app.vue
=> fix: 2189 Footer not sticking to page bottom

apps/nuxt3-ssr/.gitignore
no need to add changes ( hash ) to the repo
file is updated during build
=> chore: add fingerprint.js to git ignore

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/cohorts/index.vue
Closes #2229
Update the refTable id with the catalogue model V3 name
=> fix: 2229 ssr-catalogue areas of information filter

apps/catalogue3/src/components/VariableListItem.vue, apps/catalogue3/src/store/actions.js, apps/catalogue3/src/views/VariableExplorer.vue
=> fix: catalogue3 keywords filter

data/datacatalogue3/stagingRWE/molgenis.csv
add staging area for RWE resources
this was needed for IKNL/NKR
=> Feat: add rwe staging

backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlSchema.java, backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
=> fix: remove settings overload from SqlSchema migrate function

backend/build.gradle
Reverts molgenis/molgenis-emx2#2151
=> Revert "fix(deps): update dependency org.jooq:jooq to v3.18.0"

apps/catalogue/src/components/VariableDetails.vue
https://preview-emx2-pr-2287.dev.molgenis.org/catalogue/catalogue/#/variable-explorer/smoking?model=EUChildNetworkCDM
=> fix: separate-list-with-comma

apps/molgenis-components/src/client/client.ts
Readding missing information in the details popup
Current situation:
After this fix:
=> fix: add missing popup title

data/fairdatahub/beaconv2/molgenis.csv
Added refbacks to FDH tables to allow better navigation back to Individuals
=> Refbacks for better navigation

apps/catalogue/src/components/RefbackTable.vue, apps/catalogue/src/views/ResourceRedirectView.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/cohorts/[cohort]/index.vue
I am happy to consider other formatter for the javascript, please advice.
=> chore: fix formatting

.circleci/config.yml, build.gradle, ci/create_or_update_preview.sh, ci/install_docker_helm_kubectl.sh, ci/set_kubectl_config.sh
Interacts with #2234 that contains simplification of the docker build
todo:
=> build: move previews and release to circleci, stop using jenkins

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/index.vue, apps/nuxt3-ssr/tailwind.config.cjs, apps/nuxt3-ssr/tailwind.config.ts, apps/nuxt3-ssr/tailwind.config.umcg.cjs
border style is theme dependant
=> fix: landing page border style

apps/molgenis-components/src/components/tables/TableExplorer.vue
=> fix: should not be empty value on rows per page option

apps/molgenis-components/src/components/layout/MolgenisFooter.vue
=> fix: remove empty line above version info in footer

apps/catalogue/src/components/VariableListItem.vue
=> fix(catalogue): variable explorer should also show labels

apps/catalogue/src/components/CohortCards.vue
=> fix(catalogue): design was not shown properly in cohorts view

.circleci/config.yml, tools/README.md, tools/build.gradle
=> build: remove buildPython from default gradle build command

apps/molgenis-components/src/components/constants.js, apps/molgenis-components/src/components/forms/RowEdit.vue, backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestValidation.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTypeUtils.java
=> fix: disable validation and compute on heading columns

apps/molgenis-components/src/components/tables/TableMolgenis.vue
closes #2397
Does this have impact in refback or something?
=> fix: in TableMolgenis when item selected in while selection empty you get false

apps/molgenis-components/src/components/layout/MolgenisMenu.vue
=> fix: have a working mobile/tablet menu button

apps/catalogue/src/components/RefbackTable.vue, apps/molgenis-components/lib/main.js, apps/molgenis-components/src/components/tables/RenderValue.vue, apps/molgenis-components/src/components/utils.ts
If a template misses a requested bit of information a fallback will be displayed instead.
Also removed duplicated code.
=> fix: failt gracefully on template error

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/cohorts/index.vue
Add filters type and design 
https://trac.molgeniscloud.org/ticket/10088
https://preview-emx2-pr-2427.dev.molgenis.org/catalogue-demo/ssr-catalogue/cohorts/
preview used default theme, umcg theme example:
=> feat: Add extra cohort filters (Cohort type en Design) #10088

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/index.vue, docs/catalogue/cat_server_side-rendered.md
- set landing page text via setting ( fallback to default)
- format large number ( 123456 -> 123.456 )
=> feat: Dynamic landing page texts + format number

apps/molgenis-components/src/components/forms/InputSearch.vue
initial value of search can now be set
=> fix: now able to set initial value of searchfield

apps/catalogue/src/components/CohortCards.vue, apps/catalogue/src/store/actions.js
fixes https://github.com/molgenis/molgenis-emx2/issues/2417
=> fix: use correct orderby filter value

.circleci/config.yml, build.gradle
partial solution, this PR disables release but should do all other stuff including previews so at least PR work is okay.
Todo after: make sure right assets will be published and then hope for the best
=> build: move to other build plugin

apps/catalogue/src/views/SingleVarDetailsView.vue, apps/catalogue/src/views/VariableDetailView.vue
If the variable is viewed in the context of a network, filter the harmonization x axis (cohorts) by the network
Closes #2420
=> fix: filter by network

apps/catalogue/src/views/VariableExplorer.vue
=> fix: Order variable fetch

apps/catalogue/src/components/CohortCards.vue
=> feat: Replace n/a with empty field

apps/catalogue/src/components/HarmonisationDetails.vue, apps/catalogue/src/components/VariableCard.vue, apps/catalogue/src/components/detailView/LinkedResourcesFieldValue.vue, apps/catalogue/src/views/cohorts/CohortView.vue, apps/catalogue/src/views/cohorts/Subcohort.vue
fixed for case mentioned in attached issue + fix for similar lists in catalogue app
related to #2457
=> fix: Add missing white space to comma list

apps/catalogue/src/components/CohortCards.vue
- update institution field to new leadOrganisation and additionalOrganisations
=> fix: 2473 Catalogue cohort card, Institutions always show N/A

apps/nuxt3-ssr/components/content/ContentBlockIntro.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/cohorts/[cohort]/index.vue, backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MessageApi.java
Replace demo id with dynamic id from route
- Add error logging to message api
- Add fallback contact option ( show email in mailto link) when message filter is passed
=> fix: ssr catalogue send contact message

apps/molgenis-components/src/components/forms/EditModal.vue, apps/molgenis-components/src/main.js
- Respect feature flag
- Allow passing flag instead of fetching
- Extend demo component to toggle feature flag on and off
Closes #2500
Closes #2501
=> fix: No chapters flag not respected

apps/nuxt3-ssr/components/table/Content.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/cohorts/[cohort]/index.vue
- allow passing explicit orderby column ( instead of using header id)
Closes #2525
=> fix: orderby computed column

apps/catalogue/src/main.js, apps/catalogue/src/store/query/collectionEvent.js, apps/catalogue/src/store/query/subcohortDetails.js, apps/catalogue/src/views/SearchAllResources.vue, apps/catalogue/src/views/cohorts/Subcohort.vue, apps/molgenis-components/src/components/forms/InputOntology.vue
got to catalogue-demo/#/search2
To make it fully functional a few bug fixes were needed.
=> feat: add search screen prototype to catalogue

apps/molgenis-components/src/components/tables/RoutedTableExplorer.vue, apps/molgenis-components/src/components/tables/TableExplorer.vue
Closes #2554
Closes #2373
Note: same issue would needs to be fixed for getPrimaryKey calls
=> fix: 2554 Use relove key function to build row key

apps/molgenis-components/src/components/tables/AggregateTable.vue
Fixes an issue where the aggregate table can't deal with refs that start with a capital letter or contain a space.
=> fix: aggregate table for refs 

apps/molgenis-components/src/components/forms/InputFile.vue, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java
=> fix: file input for did not show previous value if there was a space in the name. closes #2593

apps/molgenis-components/src/client/client.ts
=> fix(catalogue): not showing resource list. closes #2591

apps/molgenis-components/src/components/tables/TableExplorer.vue
=> fix: now able to filter on DATETIME without error

backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java
motivation: when firing many token based requests without using session client side there result in denial of service because so many sessions lead to out of memory. Therefore, token based access is not put in session cache.
N.B. for future we should see if we can reduce overhead of sessions by sharing resources such as graphql and database caches between sessions.
=> fix: token based access should not result in overflow of sessions

data/datacatalogue/CatalogueOntologies/External identifier types.csv, data/datacatalogue/CatalogueOntologies/Units.csv
edits to Units and External identifier types
changes to external identifier types inside database to be made with onto manager
=> fix: edit ontologies

apps/molgenis-components/src/components/forms/EditModal.vue
fixes: https://github.com/molgenis/molgenis-emx2/issues/2571
=> fix(molgenis-components): make sure we can scroll in editmodal popup

apps/molgenis-components/src/components/utils.test.ts, apps/molgenis-components/src/components/utils.ts
=> fix: check for long input validity

apps/nuxt3-ssr/components/CohortCard.vue, apps/nuxt3-ssr/interfaces/types.ts
=> fix: fix cohort cart short description toggle and empty value case

apps/molgenis-components/src/Interfaces/IColumn.ts, apps/molgenis-components/src/components/forms/InputFile.vue, apps/molgenis-components/src/components/forms/RowEdit.vue, apps/molgenis-components/src/components/forms/formUtils/formUtils.ts
Fix should make expressions work again in forms.
Made RowEdit component typescript.
Fixed Typo bug for refLink in rowedit.
=> fix(molgenis-components): import expression function; tsify RowEdit; fix refLink typo

apps/nuxt3-ssr/nuxt.config.ts, apps/nuxt3-ssr/package.json, apps/yarn.lock
to use enable dev tools in nuxt.config.ts
https://nuxt.com/blog/introducing-nuxt-devtools
=> chore(nuxt3-ssr): add setup for nuxt dev tools

apps/molgenis-components/src/components/forms/EditModal.vue, apps/yarn.lock
Fixes #2719
Use heading labels if they are available.
=> fix: show labels for chapters

apps/molgenis-components/src/ClientView.vue, apps/molgenis-components/src/client/client.ts, apps/molgenis-components/src/components/tables/TableMolgenis.vue
Remove no longer necessary option from codebase (was needed for nuxt2, but nuxt3 doesn't anymore).
=> chore: clean up obsolete/unused myaxios option

backend/molgenis-emx2/src/main/java/org/molgenis/emx2/utils/JavaScriptUtils.java
=> fix: make regex validation work in backend

apps/molgenis-components/src/components/forms/RowEdit.vue, apps/molgenis-components/src/components/forms/formUtils/formUtils.ts
=> fix: don't count invisible fields towards errors

backend/molgenis-emx2-io/src/main/java/org/molgenis/emx2/io/emx2/Emx2.java, backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/semantics/QueryHelper.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadata.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadataExecutor.java, backend/molgenis-emx2/src/main/java/org/molgenis/emx2/Column.java, backend/molgenis-emx2/src/main/java/org/molgenis/emx2/Constants.java, backend/molgenis-emx2/src/main/java/org/molgenis/emx2/TableMetadata.java, backend/molgenis-emx2/src/test/java/org/molgenis/emx2/TestColumn.java
fix case issue that leaded to sys columns being added to search index
Closes #2759
=> fix: 2759 sys column in search index

apps/nuxt3-ssr/components/landing/CardPrimary.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/index.vue
review: https://docs.google.com/document/d/11KMqeprpAIpQI-f0ZOAkPSVLk8Co6wbr/edit#heading=h.gjdgxs
- more whitespace on to and below main cards
- smaller font size
=> fix: review comments

apps/nuxt3-ssr/components/NetworkCard.vue, apps/nuxt3-ssr/components/content/ReadMore.vue, apps/nuxt3-ssr/interfaces/types.ts
Improve styling and add links to network subsections
=> feat: improve network card

apps/nuxt3-ssr/components/HyperLink.vue, apps/nuxt3-ssr/components/content/ContentBlockIntro.vue, apps/nuxt3-ssr/components/content/ContentGenericItem.vue, apps/nuxt3-ssr/components/content/type/ContentTypeHyperLink.vue
- Add render component for generic field of type hyperlink
- Field is rendered using Hyperlink component
- Replace similar pieces of html with component
=> feat: add generic hyperlink field

apps/nuxt3-ssr/app.vue
not setting the max age defaulted to a session cookie
=> fix(nuxt3-ssr): fix set analytics cookie max age

apps/nuxt3-ssr/components/landing/CardPrimary.vue
Add some y axis padding to make it more like the design
=> fix: fix count styling

apps/molgenis-components/src/components/forms/RowEdit.vue
=> fix: default value for ontology/ref was not shown. closes #2843

apps/molgenis-components/src/components/forms/InputOntology.vue, apps/molgenis-components/src/components/forms/InputOntologySubtree.vue
Fixes #2422 
Fixes ontology inputs showing the name instead of labels.
=> fix: show ontology labels when available

apps/molgenis-components/src/components/forms/RowEdit.vue
The computed code resets the changed default value back to the initial default value ( not reflected in the form ).
This PR makes you able to change a default value, save, and have it really be the value you have chosen.
fixes: https://github.com/molgenis/molgenis-emx2/issues/2840
=> fix(molgenis-components): Save changed default value in new record

apps/molgenis-components/src/components/forms/FormInput.vue, apps/molgenis-components/src/components/forms/InputRefBack.vue, apps/molgenis-components/src/components/forms/RowEdit.vue, apps/molgenis-components/src/components/tables/TableExplorer.vue
Related issues:
#2740 
#2734 
#2710
=> fix(molgenis-components): make sure input refback gets a primary key

apps/molgenis-components/src/components/forms/FormInput.vue, apps/molgenis-components/src/components/forms/InputRefBack.vue, apps/molgenis-components/src/components/forms/RowEdit.vue, apps/nuxt3-ssr/components/HorizontalScrollHelper.vue, apps/nuxt3-ssr/components/content/ContentBlock.vue, apps/nuxt3-ssr/components/harmonization/VariableDetails.vue, apps/nuxt3-ssr/components/layouts/DetailPage.vue
Components that are too big to fit in the layout should not destroy it.
=> fix(nuxt3-ssr): layout brakes with incompressible components

apps/molgenis-components/src/components/tables/AggregateTable.vue
removes console warning for missing property
=> chore: fix aggregate table demo warning

.circleci/config.yml
- todo: run playwright via gradle, or run node via prebuild container
=> chore: Remove direct node dependency from circle ci build

backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java
would this be in the direction you need?
I was not yet able to test this ;-)
=> chore: try to create the needed subqueries to other PR

apps/build.gradle, backend/build.gradle
defaults to download=true ( same as current behaviour)
=> chore: allow nodespec download override

apps/molgenis-components/src/components/forms/InputRefList.vue, apps/molgenis-components/src/components/forms/RowEdit.vue
fix: name-id issue
fix: typo on variable causing the view more button to malfunction
chore: add extra example with more options than shown
chore: rename view as table
chore: better layout when using multiple columns
=> fix: some small fixes for refInputList

apps/schema/package.json, apps/schema/src/components/Schema.vue
currently saving in the schema editor is not possible due to broken import
=> fix: import gql in schema editor

backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RDFService.java, backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/RDFTest.java
fix #2963 column predicate is no longer a subclass of 
fix #2930 sio database column and database row are no longer used 
chore removed unused static variables
=> fix: predicates should not be assigned as classes and incorrect use of sio

apps/directory/src/components/report-components/FactsTable.vue
=> fix: star model issue

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/variables/index.vue
Store current active view in the path-query to allow for paging and back
=> feat: Show paging for variable harmonisation

apps/central/src/components/SchemaDeleteModal.vue, backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlDatabaseFieldFactory.java, backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqlDatabaseFields.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java
=> fix: couldn't delete schema because name was used instead of id. 

apps/build.gradle, apps/nuxt3-ssr/utils/buildQueryFilter.test.ts
The previous version was incorrect ( only ran the last project in the project list ], i did not understand how gradle handled the args list. this pr fixes by having nx figure out what projects have a test target and if they do run the tests
=> chore: Fix the (ci) build test runner

apps/nuxt3-ssr/components/header/Catalogue.vue, apps/nuxt3-ssr/nuxt.config.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/datasources/[datasource].vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/index.vue
- check for feature flag
- remove ununsed code
- clear variable names
=> fix: ssr catalogue fixes and code cleanup

backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RDFService.java, backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/RDFTest.java
- Test if a column is an array and only then use getStringArray otherwise use getString
- Test
=> Fix for iri being split

apps/molgenis-components/src/components/forms/InputRefList.vue
=> fix: label selection selects first items in list. closes #2975

apps/molgenis-components/src/components/forms/InputOntology.vue
fix: https://github.com/molgenis/molgenis-emx2/issues/3027
=> fix(molgenis-components): make InputOntology able to deselect terms

apps/nuxt3-ssr/components/NetworkCard.vue, apps/nuxt3-ssr/components/landing/CardSecondary.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/networks/[network].vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/networks/index.vue
- sync loading to avoid reloading page on client
- remove unused code
- format code
- fix typscipt issues
=> fix: fix ssr loading issues and typescript errors

apps/nuxt3-ssr/components/header/Global.vue
=> fix: Main catalogue about page fails to load #3112

apps/nuxt3-ssr/components/CatalogueItemList.vue, apps/nuxt3-ssr/components/CollectionEventDisplay.vue, apps/nuxt3-ssr/interfaces/types.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/[cohort]/collection-events/[collectionevent].vue
Remove collection-event core-vars from preview popup fix typing issues and data loading
=> feat: 10601 As CBCH I want small UI changers (A)

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/[cohort]/collection-events/[collectionevent].vue
Move core variables to its own section
https://trac.molgeniscloud.org/ticket/10601#comment:12
=> feat:10601 As CBCH I want small UI changers (B)

apps/nuxt3-ssr/composables/useGqlFetch.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/about.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/index.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/datasources/index.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/networks/index.vue
- add defaults for emx2 gql endpoint call
- add default response error logging
=> feat: gql use fetch wrapper

apps/directory/src/components/biobankcards-components/BiobankCard.vue, apps/directory/vite.config.js
=> fix: show use of filters in collection count text

backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlSchemaFieldFactory.java, backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqlSchemaFields.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlSchema.java
=> fix: table truncate broken since v10 refactor using ids instead of names. closes #3133

apps/directory/src/components/generators/view-components/Subcollection.vue, apps/directory/src/property-config/initialCollectionColumns.js, apps/directory/src/views/CollectionReport.vue
=> fix(directory): show subcollections on collection card wip

apps/directory/src/views/BiobankReport.vue
=> fix: add sorting to collection list

.circleci/config.yml
do not run tests again in release job
=> chore: fix build pipeline release job

apps/nuxt3-ssr/app.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/[variable].vue
=> fix: catalogue browser tab label

apps/nuxt3-ssr/components/harmonization/HarmonizationStatus.vue, apps/nuxt3-ssr/components/harmonization/HarmonizationTableCell.vue, apps/nuxt3-ssr/components/harmonization/HarmonizationTableCellStatusIcon.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
Note in practice fetch variables is to slow ( due to missing db indexes in table hierarchies ? ) , suggest to add spinner in separate pr and look into loading time issues by (automatically) adding db indexes
=> fix: scope variable loading

apps/nuxt3-ssr/gql/variable.js, apps/nuxt3-ssr/interfaces/types.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
- extend variable fetch
- fix typing
Related to: #3187
=> fix: Include the targetVariable in variable fetch

apps/nuxt3-ssr/components/NetworkCard.vue, apps/nuxt3-ssr/components/PageHeader.vue, apps/nuxt3-ssr/components/content/ContentBlockAttachedFiles.vue, apps/nuxt3-ssr/components/content/ContentBlockContact.vue, apps/nuxt3-ssr/components/content/ContentBlockNetwork.vue, apps/nuxt3-ssr/components/content/ContentBlockPartners.vue, apps/nuxt3-ssr/components/header/Catalogue.vue, apps/nuxt3-ssr/components/table/Content.vue, apps/nuxt3-ssr/composables/fetchGql.ts, apps/nuxt3-ssr/composables/fetchOntology.ts, apps/nuxt3-ssr/composables/useGqlFetch.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
=> feat: on catalogue landing page show id/name and link to about

apps/nuxt3-ssr/components/harmonization/HarmonizationGridPerVariable.vue, apps/nuxt3-ssr/components/harmonization/HarmonizationLegend.vue, apps/nuxt3-ssr/components/harmonization/VariableDetails.vue, apps/nuxt3-ssr/components/table/StickyTable.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/[variable].vue
feat: show repeated variable harmonisation as grid
- if repeats show mapping status as (repeat, cohort) grid 
- fix ts typings for stickyTable
- cleanup data loading for variable details
Closes https://github.com/molgenis/molgenis-emx2/issues/3228
=> feat: show repeated variable harmonisation as grid

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
=> fix: Add null check to see if data includes cohorts

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue, apps/yarn.lock
how to test:
- in data catalogue chose a catalogue and then you can click the name of network (instead of priously the 'about').
todo:
=> feat(catalogue): in catalogue overview replace 'about' link with of title

.circleci/config.yml
how to test:
- see that preview link is working
=> chore: fix link to preview server

.circleci/config.yml
=> build: split test and preview in seperate jobs so they both complete faster

backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/AvailableDataModels.java
=> chore: fix format

apps/central/src/components/LastUpdateField.vue
closes #3070
To test see #3070
=> fix(central): changelog couldn't fetch. closes #3070

apps/molgenis-components/src/components/forms/RowEdit.vue
how to test:
- have a date field with this default value expression `=new Date().toISOString()`
This fix will makes sure the expression is not executed every change. ( creating infinite loops and making it unchangeable )
=> fix: dont have the default values expression trigger on every change

apps/nuxt3-ssr/middleware/analytics.global.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/[cohort]/subcohorts/[subcohort].vue
Adds middleware function the calls analytics server, on spa route change, if analytics is setup and allowed
how to test:
- review code 
- test all pages function ( no regression issues )
- sign in to site improve account and test event are logged ( might only work for acc and prod due to siteimprove config)
=> feat: Add client side navigation analytics

apps/yarn.lock
Reverts molgenis/molgenis-emx2#3251
=> fix: Revert "fix(deps): update dependency floating-vue to v2.0.0"

docs/molgenis/_sidebar.md, docs/molgenis/dev_profiles.md
how to test:
- na, it's only documentation
todo:
=> Add doc for profiles

apps/catalogue/package.json, apps/central/package.json, apps/cranio-provider/package.json, apps/cranio-public/package.json, apps/directory/package.json, apps/ern-genturis/package.json, apps/ern-ithaca/package.json, apps/ern-reconnet/package.json, apps/ern-skin/package.json, apps/gportal/package.json, apps/helloworld/package.json, apps/molgenis-components/package.json, apps/molgenis-viz/package.json, apps/nuxt3-ssr/package.json, apps/pages/package.json, apps/projectmanager/package.json, apps/reports/package.json, apps/schema/package.json, apps/settings/package.json, apps/tables/package.json, apps/tasks/package.json, apps/updownload/package.json, apps/yarn.lock
=> chore: bump vue and nuxt

README.md
=> chore: Update README.md link to demo server

apps/build.gradle
=> chore:revert-node-bump

data/_models/shared/DataCatalogue-TODO.csv
Minor update on Network variables table to include reference to all variables (also repeats)
=> chore: network variables.variable refTable to All variables

apps/nuxt3-ssr/components/header/Catalogue.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
- fix, should check cohort-only flag before dataSources_agg ref
how to test:
- checkout and run with cohort only flag set to 'true'
=> fix: cohort only view render

apps/nuxt3-ssr/components/landing/Central.vue, apps/nuxt3-ssr/components/landing/CohortsOnly.vue, apps/nuxt3-ssr/nuxt.config.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
Rename sum to _sum in gql requests
how to test:
todo:
=> fix: Update agg sum request

apps/dev-proxy.config.js, apps/schema/package.json, apps/schema/src/components/ColumnEditModal.vue, apps/schema/src/components/SchemaToc.vue, apps/schema/tsconfig.json
how to test:
- no functionality is changed adding the ts
- Should now be able to add columns to a newly created table in the schema app without saving the table first.
- set the dev proxy to pet store because FAIR DATA HUB schema does not exist
todo:
=> fix: creating column on new table; chore add ts to schema app; chore: change dev schema

apps/nuxt3-ssr/package.json, apps/yarn.lock
=> fix: update deps

e2e/playwright.config.ts, e2e/tests/catalogue/show-landing-page.spec.ts
=> chore: add e2e test for ssr catalogue

.circleci/config.yml, e2e/playwright.config.ts
add test results to circle ci output
to test view the test tab in de job runner
=> chore: show e2e test results

apps/directory/src/App.vue
Fixes: #3397
how to test:
- Filter text is readable and nog white on white
=> fix: remove white text in filters

.circleci/config.yml
=> chore: run a job after merge

.circleci/config.yml
Reverts molgenis/molgenis-emx2#3428
=> Revert "chore: run a job after merge"

.circleci/config.yml
all passed params are required to be listed, used or not 
how to test:
todo:
=> build: fix trigger params

apps/meta-data-utils/src/tableQuery.ts, apps/nuxt3-ssr/components/ResourceCard.vue, apps/nuxt3-ssr/components/SideModal.vue, apps/nuxt3-ssr/components/SideNavigation.vue, apps/nuxt3-ssr/components/content/ContentBlockIntro.vue, apps/nuxt3-ssr/components/content/ContentBlockModal.vue, apps/nuxt3-ssr/components/content/ContentGenericItem.vue, apps/nuxt3-ssr/components/content/ContentGenericItemList.vue, apps/nuxt3-ssr/components/content/ReadMore.vue, apps/nuxt3-ssr/components/content/type/ContentTypeHyperLink.vue, apps/nuxt3-ssr/components/content/type/ContentTypeOntologyArray.vue, apps/nuxt3-ssr/components/content/type/ContentTypeRefBack.vue, apps/nuxt3-ssr/components/content/type/ContentTypeString.vue, apps/nuxt3-ssr/components/content/type/ContentTypeText.vue, apps/nuxt3-ssr/components/notification/NotificationModal.vue, apps/nuxt3-ssr/composables/assetLoader.ts, apps/nuxt3-ssr/interfaces/types.ts, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/[resourceType]/[resource].vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/[resourceType]/index.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/playground.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/tables.vue
Until we have a histoire/storybook playground test using ```/ssr-catalogue/tables```
=> feat: catalogue content ref back

backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlColumnExecutor.java
=> chore: format code

apps/nuxt3-ssr/package.json, apps/yarn.lock
reverts https://github.com/molgenis/molgenis-emx2/commit/d5d1b55aa6ced377feb1af38d02cbf18a77a6bd1
how to test:
todo:
=> fix: revert commit which breaks windows build

.circleci/config.yml
=> chore: bump playwright base image

apps/molgenis-components/src/queryEmx2/queryEMX2.test.ts, apps/molgenis-components/src/queryEmx2/queryEmx2.ts
Moved the test from somewhere in the directory app to the molgenis-components.
=> chore: move query builder test so it actually runs

docker-compose.yml
=> chore: Bump compose postgres version to pg 15

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/index.vue, e2e/tests/catalogue/filter-cohort-by-design.spec.ts
Closes #3461
how to test:
todo:
=> fix: cohorts list page filter issues

apps/molgenis-components/src/components/forms/InfoPopover.vue
fixes: #3220
The InfoPopover component  creates a .tooltiptext element which acts as a popover. The problem was that the popover became clipped because of a parent's overflow property in the directory app. The component is now refactored so that it appends the popover to the body and positions it accordingly, relative to the .w3tooltip element.
=> fix: InfoPopover molgenis component

backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration18.sql
=> fix: migration18 sql issue

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/[cohort]/index.vue
Closes #3534
how to test:
- see issue text
=> fix: remove redundant text

apps/molgenis-components/src/components/forms/ArrayInput.vue
fix for #3486 
how to test:
- see #3486 
todo:
=> fix: array input description

apps/molgenis-components/src/components/forms/ArrayInput.vue, apps/molgenis-components/src/components/forms/InputRefList.vue
fixes #3466 
how to test:
- see issue
=> fix: ref array input

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/[cohort]/index.vue
Closes #3515
how to test:
- see issue
=> fix: update block description

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/networks/[network].vue, e2e/tests/catalogue/network-resource-list-item-detail-link.spec.ts
Closes #3554
how to test:
- see steps in issue
todo:
=> fix: sub catalogue link form network details to resource

apps/cranio-public/src/views/view-home.vue, apps/cranio-public/vite.config.js
Fixes #3590 
This PR updates the contact details in the `cranio-public` app
- Go to the app in demo schema `cranioDemo/cranio-public/#/`
- On the home page, scroll down to the "Contact Us" section and hover over the button to view the email address. The email should reflect the changes listed in the "Files changed" tab
(You can ignore the errors on the other pages)
=> fix: updated contact details

.circleci/config.yml
=> chore: disable gradle cache for release

.circleci/config.yml, e2e/package.json, e2e/yarn.lock
=> feat: bump playwright tooling

data/biobank-directory/molgenis.csv
how to test:
- go to preview and check that with this change it's now possible to update a sub-collection without any errors.
todo:
- [na] updated testplan to include a test for this fix, including ref to bug using # notation
=> chore(directory): remove parent_collection expression due to a bug

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
Closes #3599
how to test:
todo:
=> fix: 3599 variable list paging

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue, e2e/tests/catalogue/search-results-count.spec.ts
Closes #3589
how to test:
todo:
=> fix: 3589 Missing cohorts when not in catalogue scope

apps/directory/src/filter-config/filterOptions.ts, apps/directory/src/filter-config/initialFilterFacets.js, apps/directory/src/stores/biobanksStore.js, apps/directory/src/stores/filtersStore.js, apps/directory/src/stores/qualitiesStore.js
how to test:
- fix frontend filters to works with ontologies in separate schema
todo:
=> fix: allow separate ontology schema for directory app

apps/directory/src/property-config/initialCollectionColumns.js
=> fix: show subcollection data as links if possible

apps/tailwind-components/tailwind.config.js
replace hardcoded value with variable for umcg theme
how to test:
- go to: https://preview-emx2-pr-3637.dev.molgenis.org/catalogue-demo/ssr-catalogue/all/cohorts?theme=umcg
- scroll to bottom and check the background color for the paging btn's matches the theme 
todo:
=> fix: fix paging bg style

apps/directory/src/components/filters/OntologyFilter.vue, apps/directory/src/filter-config/initialFilterFacets.js, apps/directory/src/functions/applyFiltersToQuery.js, apps/directory/src/functions/bookmarkMapper.js, apps/directory/src/stores/filtersStore.js, apps/directory/vite.config.js
closes #3608  
how to test:
- go to the dir app
- click on the diagnosis available filter
- select "match all"
- select some filters e.g. U07.0, U07.1, and U07.2 (has 1 result)
- selecting match any will now give more results
todo:
=> feat: add all filter for diagnosis

apps/directory/src/stores/biobanksStore.js
closes #3623 
how to test:
- see #3623 
todo:
=> fix: show biobanks without collection on filtering

docs/molgenis/dev_rdf.md
=> docs: fix rdf filter rows explanation

apps/directory/src/functions/viewmodelMapper.js, apps/directory/src/functions/viewmodelMapper.test.ts
- added tests to the directory front-end
- fixed bug where contact names would have an extra space with suffix titles
- fixed bug regards url fields 
how to test:
- go to the directory folder. 
- run 'yarn test'
- all tests should pass
todo:
=> fix: add tests and fix found bugs

data/biobank-directory/ontologies/QualityStandards.csv
- Added the iso-20186-1-EPND code to the Quality Standards table in the Directory Ontologies
how to test:
- Check the QualityStandars table in the DirectoryOntologies and see that the iso-20186-1-EPND is in there. 
- Could also upload real BBMRI-ERIC data from directory-emx2-acc.molgenis.net as this contains a collection with this new quality code.
todo:
=> chore(directory): add new quality code

apps/molgenis-components/src/components/layout/Molgenis.vue
- Allow custom footers in preparation of  #3621 
how to test:
- go to the style guide
- go to the molgenis component
- see the second example
todo:
=> feat: allow custom footers

.github/ISSUE_TEMPLATE/bug_report.md
how to test:
review the suggested change
=> chore: update issue template with note on duplicate issues

apps/directory/src/stores/filtersStore.ts
- added typescript
how to test:
- code review will be enough, no functionality is changed.
=> chore: add typescript to filterstore

apps/catalogue/package.json, apps/central/package.json, apps/cranio-provider/package.json, apps/cranio-public/package.json, apps/directory/package.json, apps/ern-genturis/package.json, apps/ern-ithaca/package.json, apps/ern-reconnet/package.json, apps/ern-skin/package.json, apps/gportal/package.json, apps/helloworld/package.json, apps/molgenis-components/package.json, apps/molgenis-viz/package.json, apps/nuxt3-ssr/package.json, apps/pages/package.json, apps/projectmanager/package.json, apps/reports/package.json, apps/schema/package.json, apps/settings/package.json, apps/tables/package.json, apps/tailwind-components/package.json, apps/tasks/package.json, apps/updownload/package.json, apps/yarn.lock
Update nuxt to latest version
how to test:
- everything should work as it did before ( only better ) (details see: https://nuxt.com/blog/v3-11)
=> chore: upgrade nuxt and related modules

apps/cranio-provider/src/views/provider-clp-all-centers.vue, apps/cranio-provider/src/views/provider-cs-center-surgical.vue, apps/cranio-public/src/views/view-public-dashboard.vue, apps/ern-genturis/src/views/view-public-dashboard.vue, apps/ern-ithaca/src/views/view-dashboard.vue, apps/ern-skin/src/views/view-public-dashboard.vue, apps/molgenis-viz/src/views/viz-geo-mercator.vue
PR #3536 introduced a lot of changes and features to the molgenis-viz component library. However, this meant that there are some breaking changes in some of the dashboards. This PR corrects the param names where necessary.
=> fix: corrected param names

azure-pipelines.yml
- in sycn with circleci
how to test:
- just review and have green test
=> chore: update azure-pipelines.yml to psql 15

apps/molgenis-components/src/queryEmx2/queryEmx2.ts
- Fixes #3579 for match any filter (still broken for match all).
how to test:
- see issue
=> fix: allow more filters (>1000) without timeout

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/[cohort]/index.vue
Closes #3519
how to test:
todo:
=> fix: 3519 fix dataset listing description field name

backend/build.gradle, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java
Reverts molgenis/molgenis-emx2#3719
=> Revert "fix: limit/offset/where should be applied before json nested joins otherwise queries get slow. closes #3666 closes #3481 closes #3652."

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/networks/[network].vue
- update label
Closes #3653
how to test:
todo:
=> fix catalogue data sources label

apps/nuxt3-ssr/components/DatasetDisplay.vue
- change label
Closes #3553
how to test:
todo:
=> fix: catalogue number of rows label

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/[cohort]/index.vue
- rename the label to match the value 
how to test:
todo:
=> fix: fix label to match value

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/[resourceType]/index.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/index.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/datasources/index.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/networks/index.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
- add workaround for broken nuxt scroll to top
Closes #3693 
how to test:
todo:
=> fix: 3693 scroll to top on next page

tools/pyclient/requirements.txt
- updated requirements.txt => requests==2.31.0 into requests>=2.28.1 to be able to use the emx2-pyclient together with the pyhandle package.
how to test:
- create a venv with the requirements and also install pyhandle==1.2.1, this should work without any problems.
todo:
=> fix(emx2-pyclient): update requests requirement

apps/directory/src/components/biobankcards-components/BiobankCard.vue
fixes: #3738
- fix for overflowing content on the biobank cards
how to test:
- Check biobank cards on the directory app
=> fix: overflowing content of biobank cards

tools/pyclient/README.md
- fixed a typo in the README in order to create a new PR which hopefully will trigger a new release to PyPI after being merged.
how to test:
- not
todo:
=> fix(emx2-pyclient): release requirements update #3781

apps/directory/src/functions/bioschemasMapper.js, apps/directory/src/views/BiobankReport.vue
- fixes and closes #3646 and closes #3749
- Added message that there are no collections if applicable.
how to test:
- see issue
=> fix: error when there is no collection

apps/nuxt3-ssr/components/CohortDisplay.vue
Closes #3716
how to test:
todo:
=> fix: 3716 show cohort.website string an link

apps/directory/src/stores/filtersStore.ts
- minor refactor and code deduplication 
-
how to test:
- nothing changed functionality wise
todo:
=> chore: minor filter store refactor

docs/molgenis/dev_profiles.md
Clarification of adding multiple tags, demodata and settings
=> Update profile doc

apps/molgenis-components/src/components/account/MolgenisSession.vue, apps/molgenis-components/src/components/layout/Molgenis.vue, apps/settings/src/components/Theme.vue
- Add custom html to footer 
- Add custom js 
how to test:
- as admin go to the 'theme' settings and add some html and een js console.log command
todo:
=> feat: custom add js and html to theme

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/[cohort]/index.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/networks/[network].vue
=> fix: 3416 update label

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/networks/[network].vue
=> fix: 3793 link to vars page

apps/nuxt3-ssr/components/VariableCard.vue
=> fix: 3805 revert line break

backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/ScriptTask.java, backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/Task.java, backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/TaskServiceInDatabase.java, backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/TaskServiceScheduler.java
Closes #3817
- 'fix' task contractor
- unschedule task if if task row is changed to disabled 
- do not schedule tasks that are disabled when loading tasks from database
how to test:
todo:
=> fix: 3817 dont run task if disabled

apps/molgenis-components/src/components/layout/Molgenis.vue, apps/settings/src/components/Theme.vue
fixes: #3626
- Saving a theme will now always save ( removed race condition) 
- Having a error in you Additional javascript would make settings unreachable ( oeps ) , now just log's it to the console
- Saving a theme will now auto reload the page for instant feedback.
how to test:
- Change the theme
- On save its always saved and reloaded.
=> fix: theme will now save first try

apps/directory/src/stores/filtersStore.ts
- fix: #3763 
known issue with current state: 
- Changing match any/all loads data even if no filter is selected.
how to test:
- see issue, try to change a filter while loading data
=> fix(directory): concurrency fix

apps/nuxt3-ssr/components/VariableCard.vue
- fix: #3805 
how to test:
- see isssue
=> fix(nuxt-ssr): don't split bubble over lines

data/biobank-directory/ontologies/QualityStandards.csv
- Added an extra row to the QualityStandards table in the DirectoryOntologies
how to test:
- check if standard iso-20186-2-EPND with label, code and definition is added
- changed the definition of iso-20186-1-EPND
todo:
=> chore(directory): add new quality standard

apps/molgenis-components/lib/main.js, apps/molgenis-components/src/components/constants.ts, apps/molgenis-components/src/components/forms/ArrayInput.vue, apps/molgenis-components/src/components/forms/FormInput.vue, apps/molgenis-components/src/components/forms/InputEmail.vue, apps/molgenis-components/src/components/forms/InputHyperlink.vue
- added hyperlink input to molgenis components
- closes #3823 
- also did some lay-outing
how to test:
- go to the styleguide
- go to InputHyperlink
- try some hyperlink variations
- add a hyperlink to a schema
- check in forms that it works there as well
todo:
=> fix: add hyperlink input

docs/molgenis/run_docker.md
closes #3679
- fix links in the docker run page
how to test:
- please verify the changed links
=> fix(docs): docker compose urls

docs/molgenis/use_usingpyclient.md, tools/pyclient/dev/upload_file.py, tools/pyclient/src/molgenis_emx2_pyclient/client.py, tools/pyclient/src/molgenis_emx2_pyclient/graphql_queries.py
- added a method for uploading files to a database with the Pyclient
how to test:
- use the 'upload_file.py' script in the dev folder
todo:
=> feat(pyclient): upload method for the Pyclient

docs/molgenis/dev_graphql.md, docs/molgenis/use_permissions.md
fixes: https://github.com/molgenis/GCC/issues/104
Added documentation for missing authorization levels
=> docs(permissions): new authorization levels

backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/QueryEntryType.java, backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/endpoints/datasets/Pagination.java, backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/filter/Filter.java, backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/requests/BeaconQuery.java
- Moved pagination to the data fetch with graphql to speed up things. And added support to add pagination parameters for get requests
how to test:
todo:
=> feat(beacon): moved Beacon pagination to graphql api level

apps/gportal/README.md
- Added readme on how to configure the gportal application
how to test:
todo:
=> fix: init readme

apps/nuxt3-ssr/components/filter/Ontology.vue, apps/tailwind-components/app.vue, apps/tailwind-components/components/Modal.vue, apps/tailwind-components/pages/Modal.story.vue
- formatted app.vue since it isn't auto formatted and changed subTitle to subtitle since it is one word.
=> chore(tailwind-components): format app.vue and fix spelling mistake

backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/endpoints/Info.java, backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/BeaconApi.java
Added id to sql query when fetching info data from endpoint tabel
How to test:
See Beaconv2_InfoTest still passing, with the updated query
=> fix(beacon): use id when fetching info data from endpoint tabel

docs/molgenis/dev_quickstart.md
- Just replaced ' with `
how to test:
todo:
=> chore: fix incorrect quotes causing code not being able to be copy-pasted

backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/CatalogueComplianceTest.java, backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/ComplianceTest.java, backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/FDPComplianceTest.java, backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/SHACLIntegrationTest.java
- Fixes usage of PascalCase instead of camelCase.
- Improved code structure.
how to test:
todo:
=> chore(rdf): fixes invalid code conventions

apps/nuxt3-ssr/components/landing/CardPrimary.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
=> fix(nuxt3-ssr): add a force aggregate button

apps/nuxt3-ssr/components/landing/CardPrimary.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
- open force link in new tab
how to test:
- opening the link works and opens in a new tab
=> fix(nuxt3-ssr): open force link in new tab

docs/molgenis/dev_beaconv2.md
- Performed performance tests and summarised it in the docs
=> docs(beacon): added performance docs

docs/molgenis/use_usingpyclient.md, tools/pyclient/dev/dev.py, tools/pyclient/src/molgenis_emx2_pyclient/client.py
- made a number of methods asynchronous **(breaking change)**
- added reporting of schema creation progress (from template) and its subtasks in the logging
how to test:
todo:
=> Pyclient: added logging updates for schema creation task

apps/tailwind-components/.gitignore, apps/tailwind-components/.pa11yci, apps/tailwind-components/README.md, apps/tailwind-components/package.json, apps/yarn.lock
- ~Add ignore rules for nuxt elements~: no longer needed
how to test:
=> chore (tests): init pa11yci config

backend/molgenis-emx2-fairdatapoint/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPoint.java, backend/molgenis-emx2-fairdatapoint/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPointCatalog.java, backend/molgenis-emx2-fairdatapoint/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPointDataset.java, backend/molgenis-emx2-fairdatapoint/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPointDistribution.java
- check if object is iri before adding triple
how to test:
=> fix(fdp): check if object is iri before adding triple

data/_demodata/applications/datacatalogue/Variables.csv
- small data change in demo data, see diff
how to test:
- does it work in the preview?
todo:
=> chore: edits testVarRepeats repeatMax and repeatUnit

helm-chart/templates/deployment.yaml
-  change help chart deploy script requesting and limiting resource usage
how to test:
- should result in better distribution of pods on k8s
=> build(preview): request and limit resources to help k8s in planning

helm-chart/templates/deployment.yaml
see name.
should see easier deploy of previews
=> build(helm-chart): remove cpu requirement from docker to ease k8s deployments

apps/nuxt3-ssr/components/harmonisation/HarmonisationLegendDetailed.vue, apps/nuxt3-ssr/components/harmonisation/HarmonisationLegendMatrix.vue, apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
closes https://github.com/molgenis/molgenis-emx2/issues/4341
=> fix(catalogue): use resource or source instead of cohorts 

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
closes https://github.com/molgenis/molgenis-emx2/issues/4247
before:
after:
=> fix(catalogue): variables filter on source showed incorrect mappings

backend/molgenis-emx2-sql/src/test/java/org/molgenis/emx2/sql/TestSqlTypeUtils.java
- Last PR added a newline quickly and apparently not formatted correctly.
=> chore: formatting

backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/JavalinCustomHttpActionAdapter.java, backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/controllers/OIDCController.java, backend/molgenis-emx2-webapi/src/test/java/org/molgenis/emx2/web/JavalinCustomHttpActionAdapterTest.java
=> chore: add test for custom javalin oidc action adapter

backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlColumnExecutor.java, backend/molgenis-emx2-typescript/src/test/resources/expected-types.ts, backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
to enable filtering of subsets of an ontology, e.g. similar to profiles specific use
=> feat(ontology): enable tags on ontology rows

.circleci/config.yml
we seem to have  issues that parallel releases don't work.
May this be solution?
=> fix: releases don't work when in parallel

.circleci/config.yml
Reverts molgenis/molgenis-emx2#4433
=> fix: undo changes releases don't work when in parallel

apps/nuxt3-ssr/components/content/cohort/GeneralDesign.vue
hide keywords from collection details view
=> fix(catalogue): hide keywords

apps/settings/src/components/Members.vue
fixes: #4237
how to test:
todo:
=> fix(settings): remove excessive email validation in user settings

apps/central/src/components/SchemaCreateModal.vue, backend/molgenis-emx2/src/main/java/org/molgenis/emx2/TableMetadata.java, docs/molgenis/use_database.md, docs/molgenis/use_schema.md, e2e/tests/central/admin!create-database.spec.ts
- Updated docs according to #4391 
- Minor adjustment to the text in apps/backend (singular -> plural)
- Check if agreed on changes
=> chore: updated docs according to recent changes in database regex

helm-chart/templates/deployment.yaml
- reduce resource requirements because we are not using it
- see preview still works
=> build: reduce preview resource requirements

apps/molgenis-components/src/components/forms/FormInput.vue, apps/molgenis-components/src/components/forms/InputRefBack.vue, apps/molgenis-components/src/components/forms/RowEdit.vue
=> fix(molgenis-components): missing expression data in ref input

apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
=> fix(catalogue): remove full stop on catalogue page second level actions.

.github/ISSUE_TEMPLATE/1-bug_report.yml
- Updated EMX2 placeholder to be more generic
- Added spaces to system configuration values after `:` (easier better formatting)
- Added placeholder for system configuration so that if user removes value for some reason, the placeholder will show up
=> chore: bug template improvements

tools/directory/CHANGELOG.md, tools/directory/README.md, tools/directory/bump-version.sh, tools/directory/setup.cfg, tools/directory/setup.py, tools/directory/src/molgenis_emx2/directory_client/__init__.py
- Made adjustments to bump version.sh and setup.cfg to accommodate a separate versioning scheme for molgenis-emx2-directory-client apart from the molgenis-emx2 repo
- Updated README
- Clone the repo locally and run bumpversion.sh 
=> chore(directory): Own versioning scheme

apps/molgenis-components/src/components/forms/InputBoolean.vue
=> fix: InputBoolean uses yes/no

backend/molgenis-emx2/src/main/java/org/molgenis/emx2/utils/TypeUtils.java
=> chore: fix formatting error

apps/tailwind-components/assets/css/main.css, apps/tailwind-components/components/SourceCode.vue, apps/tailwind-components/components/Story.vue, apps/tailwind-components/pages/Button.story.vue, apps/tailwind-components/pages/index.vue, apps/tailwind-components/pages/input/Checkbox.story.vue, apps/tailwind-components/pages/input/Label.story.vue, apps/tailwind-components/pages/input/Listbox.story.vue, apps/tailwind-components/pages/viz/ChartLegend.story.vue, apps/tailwind-components/tailwind.config.js
Part of molgenis/GCC#279
> [!NOTE]
> This PR contains general fixes to the tailwind stories (e.g., general styling, removing unnecessary text, etc.). Improvements to the functionality of stories will introduced in subsequent PRs. The viz component story is not part of this PR.
- Navigate to the preview.
- View stories: note changes to the source code and less content in the stories
=> fix(tw): fixes to stories

data/portal/Dataset mappings.csv
- removed attributes with reference to `catalogue` schema (as these do not exist)
=> fix(portal): removed reference to schema and table that does not exist

apps/molgenis-components/package.json, apps/molgenis-components/src/components/constants.ts, apps/molgenis-components/src/components/forms/InputLong.vue, apps/molgenis-components/src/components/forms/InputRangeDecimal.vue, apps/molgenis-components/src/components/forms/InputRangeLong.vue, apps/molgenis-components/src/components/forms/baseInputs/BaseInputDecimal.vue, apps/molgenis-components/src/components/forms/baseInputs/BaseInputInt.vue, apps/molgenis-components/src/components/forms/baseInputs/BaseInputLong.vue, apps/molgenis-components/src/components/forms/formUtils/formUtils.test.ts, apps/molgenis-components/src/components/forms/formUtils/formUtils.ts, apps/molgenis-components/src/components/utils.test.ts, apps/molgenis-components/src/components/utils.ts, apps/ui/package.json, apps/yarn.lock
- Moved validation for longs to FormGroup
- Added validation for ints (valid number/valid java int), and decimals (valid number). 
- Also added validation for the array variants
- Fixed hyperlink tests
- go to the molgenis compnents
- go to editmodal
- open it on the order table. Edit the quantity field to test LONG, price to test DECIMAL
- For int and array versions, add an additional column to play around with with the schema editor.
=> chore: update validations

apps/directory/src/components/biobankcards-components/BiobankCard.vue
This PR closes molgenis/GCC#891
- Navigate to the preview and go to the directory app
- Note the new title
> [!NOTE]
> I'm not entirely familiar with the directory app. If there are any issues as a result, please let me know.
=> fix: updated biobank card title

docs/molgenis/semantics.md
- grammar-related fixes
- review
=> docs: Grammar-related fixes

backend/build.gradle
- Reverted the log4j library from compileOnly to implementation 
- Check out master and see no java log
- Check out this branch and see java log.
=> fix: logging via log4j library

backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/ColumnTypeRdfMapperTest.java
- improved test in case it fails with explicit error messages
- review code
=> chore: added explicit error messages for RDF `assertAll` with `assertTrue`

apps/directory/src/components/cart/NegotiatorSelection.vue, apps/directory/src/stores/checkoutStore.ts
- Added more detailed errors to the directory negotiator according to https://negotiator.bbmri-eric.eu/api/swagger-ui/index.html#/Requests/retrieve
- closes https://github.com/molgenis/GCC/issues/1034
- go to the directory demo
- add some collection to the card
- click on the request button
- click the send to negotiator button
- it should show a 400 error message (demo data can't be actually requested).
=> feat: better negotiator errors

.circleci/config.yml
=> build: change sonar.login to sonar.token

apps/catalogue/pages/[schema]/catalogue/[catalogue]/about.vue
Update support email about.vue
=> Update support email about.vue

apps/tailwind-components/.pa11yci, apps/tailwind-components/README.md, apps/tailwind-components/package.json, apps/tailwind-components/scripts/pa11y_update_urls.js, apps/tailwind-components/tests/e2e/components/input/listbox.spec.ts, apps/tailwind-components/tests/vitest/components/input/Listbox.spec.ts
=> chore: update tw tests

.circleci/config.yml
=> fix(config): changed wrong url for slack channel notification

backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java, backend/molgenis-emx2-sql/src/test/java/org/molgenis/emx2/sql/TestRefBack.java
fixes #4832 
fixed reference joins for inherited tables in de SqlQuery.java 
See issue https://github.com/molgenis/molgenis-emx2/issues/4832
=> fix(emx2): fixed reference joins for inherited tables

docs/catalogue/cat_data-manager.md
=> fix: link in docs

docs/molgenis/run_docker.md
=> doc(docker): document delete for psql

backend/build.gradle, backend/molgenis-emx2/build.gradle
addresses https://github.com/molgenis/GCC/issues/1205
=> fix: upgrade javalin to 6.5.0

apps/molgenis-components/src/components/forms/formUtils/formUtils.ts
=> fix: BigInt util function

apps/directory/src/stores/networkStore.ts, apps/directory/src/views/NetworkReport.vue
=> fix: don't show withdrawn biobanks on network report

.github/ISSUE_TEMPLATE/1-bug_report.yml
Added the placeholder as value as well.
=> chore: Update 1-bug_report.yml

apps/directory/src/i18n/i18n.js, apps/directory/src/views/CollectionReport.vue, apps/directory/vite.config.js
=> fix: show warning when collection is withdrawn

apps/directory/src/views/BiobankReport.vue, apps/directory/src/views/NetworkReport.vue, apps/directory/vite.config.js
- fix: #4960 
- minor textual improvements
- see issue
=> fix: show correct count if subcollection is withdrawn

apps/directory/src/stores/filtersStore.ts
=> fix: results for removing search

backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/PrimaryKey.java
- Just some Javadoc to ensure we do not run into issues in the future if for some reason array keys are re-introduced and suddenly things would break.
=> chore: added some javadoc to ensure future changes keep current limitations in mind

backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java
Fixes #4955 
- Added an extra join when for inherited tables.
- See issue #4955
=> fix: added inheritance join to column in subquery

backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java, backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/PrimaryKey.java, backend/molgenis-emx2/src/main/java/org/molgenis/emx2/TableMetadata.java, backend/molgenis-emx2/src/test/java/org/molgenis/emx2/TestTableMetadata.java
- Refactored some code to make column by identifier retrieval easier
=> chore: small refactor to make column by identifier retrieval easier

backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/Migrations.java, backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlColumnRefArrayExecutor.java, backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration26.sql
Fixes #4894
- Added the manage role as owner of the trigger functions
See issue #4894
=> fix: set manager permission to trigger functions

apps/molgenis-components/src/components/forms/InputOntology.vue, apps/yarn.lock
=> fix(forms): couldn't clear ontology. closes #4981 

apps/molgenis-components/src/components/forms/formUtils/formUtils.test.ts, apps/molgenis-components/src/components/forms/formUtils/formUtils.ts
=> fix(forms): emtpy _array types gave error for 'int' and 'hyperlink'. closes #4986,#4956

data/_models/shared/Version.csv, docs/catalogue/cat_admin.md
see changes to 6.0
This is a follow up to molgenis/molgenis-emx2#4919
=> fix(docs): documentation for major change in catalogue model was missing

backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTypeUtils.java
fixes #4974 #4574 #5007
- Added the simplePostClient functionality to computed values in the back-end
-
=> feat: add javascript bindings (simplePostClient) to computed values

apps/directory/src/components/report-components/FactsTable.vue, apps/directory/src/functions/applyFiltersToQuery.js, apps/molgenis-components/src/queryEmx2/queryEmx2.ts
-fix: https://github.com/molgenis/GCC/issues/1101
- Go to a collection
- Look at the facts table
- it should no longer contain a lot of anies
- deselect a column. 
- that column should now contain only anies
=> fix(directory): facts table displays incorrect rows

apps/catalogue/gql/variable.ts, apps/ui/pages/admin.vue
- an incorrect import path caused building the application to fail
- just `gradlew run` or `gradlew clean run --rerun-tasks`
=> fix: use correct import path

docs/molgenis/dev_quickstart.md, docs/molgenis/dev_rdf.md, docs/molgenis/run_systemd.md
=> docs: minor fixes (Java version & extra link to semantics in rdf section)

backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/Migrations.java, backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration27.sql, backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration28.sql
- Added an update to the original admin user to set the isAdmin field to true
=> fix: added update to admin user migration

data/biobank-directory/ontologies/DiseaseTypes.csv
Missing codesystem value caused scripts to fail
=> fix(directory): add codesystem 'Not applicable' to 'Any'

backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
=> fix(tests): multithreaded login test only fails when logged in as admin

data/_ontologies/Biosample type.csv
- Added cfDNA (Circulating Cell-Free DNA) to Biosample type, needed for OpenSpecimen (sample) data.
=> Chore:  add cfDNA to Biosample type ontologie

backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/config/RdfConfig.java
moved commented words to another line that are moved there by the linter.
- see that the file is not corrected when building and running this branch
=> chore(rdf): helping the linter with comment formatting 

apps/catalogue/pages/[catalogue]/[resourceType]/index.vue
closes https://github.com/molgenis/GCC/issues/1108
=> fix(catalogue): page title in collections/networks was not uppercase.

apps/directory/src/stores/checkoutStore.ts
- fix: https://github.com/molgenis/GCC/issues/1536
- Also fixed it for non podium negotiator errors
- send a request to the podium with an incorrect username or password
- put an invalid negotiator version in the settings and send a request
=> fix: better error handling for negotiator

docs/directory/directory_admin.md
- added matomo settings to the manual
=> docs(directory): add matomo settings to manual

apps/tailwind-components/assets/icons/Menu Open.svg, apps/tailwind-components/assets/icons/Menu Open.svg 
remove space after the extension
=> chore: rename Menu Open.svg  to Menu Open.svg

docs/molgenis/use_schema.md
- Go the [form types section in the schema guide](https://preview-emx2-pr-5261.dev.molgenis.org/apps/docs/#/molgenis/use_schema?id=form-types)
=> docs: documentation for form display

apps/directory/src/App.vue, apps/directory/src/functions/bookmarkMapper.ts, apps/directory/src/stores/checkoutStore.ts, apps/directory/src/stores/filtersStore.ts
- removed boolean which was set to false and then never updated
=> chore(directory): remove always false bool

apps/directory/src/App.vue, apps/directory/src/components/biobankcards-components/MatchesOn.vue, apps/directory/src/filter-config/filterOptions.ts, apps/directory/src/functions/bookmarkMapper.ts, apps/directory/src/stores/filtersStore.ts
- just some renaming to make some variable names a bit more clear
=> chore(directory): rename variables

apps/directory/src/components/filters/SearchFilter.vue, apps/directory/src/functions/bookmarkMapper.ts
- Fixes loading the string/search filter from url
- Enter something in the search input
- See that the url updated with the filter
- Press f5 or copy the url and paste it into a new tab
- See that the filter is applied.
=> fix: string filter from url

apps/directory/src/filter-config/filterOptions.ts, apps/directory/src/stores/filtersStore.ts
=> chore: refactoring filter options

backend/molgenis-emx2-webapi/src/test/java/org/molgenis/emx2/web/WebApiSmokeTests.java
=> fix(beacon): removed redundant tests from WebApiSmokeTests

backend/molgenis-emx2-datamodels/src/test/java/org/molgenis/emx2/datamodels/CatalogueTest.java
- Removed some code that did not have any use.
- Test should still work.
=> chore: removed unused code

backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/TaskServiceInDatabase.java, backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/TaskApi.java, docs/molgenis/use_scripts_jobs.md
- Added documentation for the task api
- Fixed the tasks list api, which failed in non schema context. And return nothing in the right context.
- 
=> fix(tasks): added documentation and fixed task list api

backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration27.sql
added if not exists to migration script when adding admin field
=> fix: added if not exists when adding admin field

apps/tailwind-components/pages/viz/ChartLegend.story.vue
- In the new components gallery, go to the vizChartLegend story. Adjust the settings and view the changes
=> chore(tw): update legend story and integrate prop controls

apps/molgenis-components/src/client/IClient.ts, apps/molgenis-components/src/client/client.ts, apps/molgenis-components/src/components/tables/AggregateTable.vue
- fixes #5141 
- added support for "RADIO" columns (category in pet store)
- added support for composite keys
- see isssue, should be fixed for pet store. Couldn't verify for the other schema as the mentioned table doesn't seem to exist.
=> fix(explorer-bst): refbacks in aggregate table

apps/molgenis-components/src/components/forms/InputHeading.vue, apps/tailwind-components/components/form/Fields.vue, backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/json/Table.java, backend/molgenis-emx2/src/main/java/org/molgenis/emx2/Constants.java
closes [#1872](https://github.com/molgenis/GCC/issues/1872)
closes https://github.com/molgenis/molgenis-emx2/issues/5425
motivation:
* new _mg heading gets in the way of e.g. python client and csv import.
test:
=> fix(forms): rename _mg_top_of_form to mg_top_of_form so it is ignored just like other mg_ columns are
