molgenis/molgenis-emx2

- apps/styleguide/src/tree/TreeComponent.vue
- apps/styleguide/src/tree/_TreeItem.vue
Sync with catalog data model change, keyword now has human readable name
> fix: Use name as tree label

- apps/styleguide/src/tables/FilterWells.vue
Vue adds props to make objects reactive, by replacing a object the reactivity is removed.
If the object (the array) is altered ( cleared ) instead of replaced the reactivity stays intact
> fix: Fix filter-well remove all handler

- apps/catalogue/src/views/SingleVarHarmonizationView.vue
Fixes issue where using the browser back button would result in empty vue due to no tab ( child view ) being selected
by using replace instead of push the empty view is not put in the history
> fix: remove empty parent route

- apps/catalogue/src/components/HarmonizationDefinition.vue
- apps/catalogue/src/store/actions.js
- apps/catalogue/src/views/SingleVarDetailsView.vue
- apps/catalogue/src/views/SingleVarHarmonizationView.vue
- apps/catalogue/src/views/VariableDetailView.vue
Remove calls to fetch variable details from child-views
The child is renderd in the context of the parent,
the parent can fetch the data and pass as prop to the child
> chore: remove unneeded data fetch calls

- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/MetadataUtils.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java
in a few files because 'Record' is now ambiguous because it has been added to java.lang since java14
> fix: need explicit org.jooq.Record since jdk14 added Record to java.lang

- apps/styleguide/styleguide.config.js
- use env setting to set proxy target
- default to local host and 'pet store' schema
> chore: setup configurable proxy for style guide resources

- .circleci/config.yml
use gradle base image, remove the need for apt-get install git dance
> chore: improve circle ci config

- apps/catalogue/src/views/ResourceHarmonizationDetails.vue
- apps/catalogue/src/views/SingleVarDetailsView.vue
Some vars have no mapping, the ui should not try and render these, but skip them
> fix: Handle missing mapping

- apps/styleguide/src/layout/LayoutModal.vue
In light of "Data is lost when entering data via forms and clicking outside form."  
[x] when clicking outside of a modal it does NOT close.
closes #212
> fix: data is lost when entering data via forms and clicking outside form. closes #212

- Jenkinsfile
assigning to env['TAG_NAME'] uses putAt which is unsafe
> chore(Jenkinsfile): set env with dot notation

- docker-compose.yml
- docs/dev_quickstart.md
When you expose the ports you can run `docker-compose up postgres`. In this way you do not need to install postgres from scratch but you can run docker to use postgres as a backend for development.
> chore: expose ports in postgres container

- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManagerDatabaseListener.java
- backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/DatabaseListener.java
resulting in 'admin' settings not available when logging in as admin. See #431
To see fail
- on old server, login as 'admin' and go to https://emx2.test.molgenis.org/apps/central/#/admin
To see success
- on this pull request log in as admin and go to https://localhost:8080/apps/central/#/admin
Also see WebApiSmokeTests.testGraphqlApi in the pull request.
> Fix: admin settings not available / when user switches graphqlapi was not refreshed 

- .gitignore
- .jenkins/build-pod.yaml
- Jenkinsfile
- build.gradle
- helm-chart/Chart.yaml
- helm-chart/questions.yaml
- helm-chart/templates/deployment.yaml
- helm-chart/templates/ingress.yaml
- helm-chart/templates/pvc.yaml
- helm-chart/templates/svc.yaml
- helm-chart/values.yaml
Changes:
- Chart is now build and published on the chart repo during merge
- Chart is using the MOLGENIS version (we could do this differently and only trigger the chart build when chart files are changed)
- The PR flow differs now from the master build in terms of rancher deployment and chart builds
- The pod-template is in a separate file in `.jenkins/build-pod.yaml` to clean up the Jenkinsfile
- The build result is posted on slack in the **pr-emx2** channel
> feat: add pr previews

- apps/schema/src/components/Schema.vue
- apps/schema/src/components/SchemaSimple.vue
- apps/styleguide/src/tables/FilterSidebar.vue
- backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlConstants.java
Motivation:
* we had error when opening 'schema'.
* we had error in styleguide test for sidebar (not important)
> fix: remove references to columnFormat that broke schema editor tool

- backend/molgenis-emx2-io/src/main/java/org/molgenis/emx2/io/readers/CsvTableWriter.java
- backend/molgenis-emx2-run/src/main/java/org/molgenis/emx2/AToolToCleanDatabase.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/MetadataUtils.java
- backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/utils/TableSort.java
Implemented:
* deterministic column ordering for csv download
* deterministic table ordering in metadata molgenis.csv download
Motivation:
* testCsvApi_zipUploadDownload was regularly breaking on order 
* when you download molgenis.csv via api https://emx2.dev.molgenis.org/pet%20store/api/csv then order emx columns is weird
> Fix: csv api upload/download

- apps/styleguide/src/layout/MolgenisSession.vue
Adds missing keys to session fetch
Closes: https://github.com/molgenis/molgenis-emx2/issues/476 ( however issue is older then session keys feature )
> fix: add missing default keys to session settings fetch

- apps/catalogue/src/views/TableView.vue
When you go to https://minerva.molgeniscloud.org/Minerva/catalogue/#/tables/AP/1.0/AP  and then try to click link for the tables high up on the page it fails.
In this pull request that should not happen.
So download the minerva, upload in preview, go to URL above and click the link
> fix[catalogue]: when in tables view you couldn't click to the ETL

- backend/molgenis-emx2-io/src/main/java/org/molgenis/emx2/io/readers/CsvTableReader.java
- backend/molgenis-emx2-io/src/main/java/org/molgenis/emx2/io/tablestore/TableStoreForCsvInZipFile.java
- backend/molgenis-emx2-io/src/test/java/org/molgenis/emx2/io/TestCsvTableReader.java
This should solve recent issue we had that a csv.zip file couldn't be imported with error:
"Import failed: Transaction failed: Import failed: java.lang.ArrayIndexOutOfBoundsException: arraycopy: source index -43 out of bounds for char[8192]. Error at line 1.: arraycopy: source index -43 out of bounds for char[8192] in 3100ms"
> Fix: import fails on empty csv file

- apps/catalogue/src/views/CohortView.vue
- apps/styleguide/src/forms/InputText.vue
- apps/styleguide/src/forms/ResizableTextarea.vue
and also refactored so it doesn't use 'document' anymore easing the way towards ssr.
To test
- view textarea
- see there is no scroll bar
- see you can use clear button without overlapping scroll bar #732 
- see you can't accidentally click clear while using a scroll bar #601 
closes #732 
closes #601
> fix: textinput should not show scroll 

- apps/styleguide/src/forms/InputOntology.vue
- apps/styleguide/src/forms/InputOntologySubtree.vue
- apps/styleguide/src/forms/_appendClear.vue
- apps/styleguide/src/forms/_formGroup.vue
How to test
- you can search (case insensitive)
- if list is larger then 50% of screen then it will show scrollbar
- if your terms have 'definition' field with contents then that contents is shown
closes #745
> feat: add search, definition and scrollbar to ontology input

- backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestGrantRolesToUsers.java
- backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestSettings.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlSchema.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlSchemaMetadata.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadata.java
- docs/molgenis/use_permissions.md
How to test:
* create a manager (or owner, who also has manager permission)
* create a editor 
* create a viewer
* observe that managers can set settings on schema level (e.g. theme) and editors cannot
* observe that editors can set settings on table level (e.g. using cog on table list view, right top) and viewers cannot
Discuss: we could limit also table settings to managers only
> feat: schema settings can be set by managers, table settings can be set by editors

- backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqlAdminFields.java
because ran outside of transaction and therefore sometimes intereferences with other tests that also change users.
This should help.
> test: testUsers failed irregularly 

- backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestAddColumnUpdateSearchTrigger.java
- backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestMergeAlter.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/TableMetadata.java
Note: some test cases also had too long table names. This means that these tests fail unless you have a clean database.
So that is a caveat for developers to consider.
> Fix: check for table length was incorrect

- docs/molgenis/_sidebar.md
fix dead link OIDC integration (sidebar) in documentation
> chore: fix dead link OIDC integration (sidebar)

- .circleci/config.yml
- apps/Dockerfile
- apps/build.gradle
- apps/nuxt-ssr/package.json
- apps/nuxt-ssr/yarn.lock
- apps/package.json
- apps/styleguide/src/display/LinksList.vue
- apps/yarn.lock
fix: css loader
- Do not share css-loader between modules, as css-loader versions are incompatible
Closes #942
Related to #934
> fix: Fix css loader

- renovate.json
All components need to be migrated to vue 3 before using the vue framework
> chore: ignore vue 3 major change

- apps/central/src/components/Groups.vue
To test:
* change menu of a database such that e.g. 'schema' is the first menu item
* then go back to 'list databases' and select your database again
* you should then see 'schema'
> fix: when linking from central to schema then first menu item should be selected

- backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestQueryJsonGraph.java
- backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestRefBack.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java
caused by psql json_object() receiving >100 params
e.g. https://github.com/hasura/graphql-engine/issues/4004
n.b. arbitrary formatting changes required fixing of tests.
> fix: queries fail on large tables (e.g. Databanks)

- backend/molgenis-emx2-webapi/build.gradle
motivation: was breaking github action (because that one is not cached I suppose)
> chore: remove unused mockito dependency

- backend/molgenis-emx2-run/src/main/java/org/molgenis/emx2/AToolToCleanDatabase.java
due to changes in the user management, the deleteAll function stopt working
by making the user the admim the tool has the rights it needs to delete everything
> fix: fix broken deleteAll

- apps/catalogue/src/components/VariableDetails.vue
When viewing a single repeated variable detail, do not show the mapped by field,
The mappedBy status is displayed in the table
Closes #1137
> fix(catalogue): Fix 1137

- apps/build.gradle
by having 'apps/build.gradle' smarter so we don't run all kinds of task needlessly.
- checks better on inputs/outputs
- only runs the 'buildStyleguide' and 'buildShowcase' for relevant apps
N.B. you notice this when working locally, making some changes and then run again.
> build: make 'gradle run' faster 

- apps/molgenis-components/src/App.vue
Uses css variable to obtain hook to html and body style value
And change these if in focus mode
This solves the issue of the scrollbar missing in focused examples that extend beyond the fold
> fix: Add missing scrollbar in focus view

- apps/molgenis-components/src/components/forms/baseInputs/BaseInput.vue
Remove html type property from base input as each input component has a hardcoded type.
> chore: remove unused property

- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/MetadataUtils.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlSchemaMetadata.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/Constants.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisWebservice.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/Database.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/SchemaMetadata.java
- docs/molgenis/use_global_settings.md
to make users directly go to path you like the to go, skipping /apps/central
To test:
* sign in as admin
* use admin settings -> LANDING_PAGE and set that to /pet store/
* open new browser and go to root of the preview server, you will see you navigate to /pet store/ instead of /apps/central/
You can still go back to /apps/central using the breadcrumb pull down.
TODO: if you have no permission on the url the breadcrumb doesnt show well
NOTE: refactored settings internals at backend to fix a bug where settings could have duplicate key
> feat: added LANDING_PAGE setting 

- backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestCreateForeignKeys.java
- backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestCreateForeignKeysArrays.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/Reference.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/Row.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/TableMetadata.java
this was consequence when we added 'validation' that required checks were removed from postgresql and moved to java.
setRequired() was not correctly passed to the technical columns for insert/update.
fixes #1294
> fix: required check failed on ref, ref_array, ontology, ontology_array

- apps/updownload/src/components/Task.vue
At last refector we renamed 'steps' to 'subTasks' in API, but failed to update the UI. When download and then upload Excel of pet store then:
Old
Fixed
Closes #1258
> fix: progress of substasks was not shown in Excel upload

- apps/catalogue/src/components/NetworkCards.vue
Before
After:
Thank you to @jelmerveen
> fix: logos should not be stretched

- backend/molgenis-emx2-webapi/build.gradle
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/BootstrapThemeService.java
The deprecated `io.bit3.jsass.Compiler` was replaced with the actively maintained `de.larsgrefer.sass.embedded.SassCompiler`. This compiler works on modern systems, gives stylesheet deprecation warnings, and allows compression of the served CSS. Tested and working under:
- MacOS 12.4 on M1 processor, running on IntelliJ IDE
- MacOS 12.4 on M1 processor, running on fat JAR distribution
- Windows 10, running on fat JAR distribution
> fix: replaced jsass.Compiler with de.larsgrefer.sass.embedded.SassCompiler

- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/BeaconApi.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/FAIRDataPointApi.java
FAIR Data Point API responses are now MIME typed as `text/turtle` and Beacon v2 API responses are types as `application/json`. This informs clients on how to handle the response and allows better rendering.
> fix: response MIME types for FDP and Beacon 

- apps/styleguide/src/tables/RowEditModal.vue
> fix: when refLink then error was shown for correct examples.

- apps/build.gradle
Reverts molgenis/molgenis-emx2#1384
Motivation: see if this leads to more stability in the build to get rid of "finished with non-zero exit value 127" errors.
> Revert "chore(deps): update plugin com.github.node-gradle.node to v3.4.0"

- apps/molgenis-components/package.json
allow cross evn to be used when node env is set to prod
> chore: set cross env as dep

- apps/molgenis-components/src/components/forms/InputRefBack.vue
fix: swap spinner for empty table in case of empty options list ( empty ref table)
> fix: inputRefback handle empty options list

- apps/molgenis-components/src/components/forms/EditModal.vue
Use the default data prop to reset ref key in case of clone
solves issue in clone via inputRefback , the key from the parent table should stil be set on the clone data set.
Row data if first fetched based on clone origin id, then the keys are removed , then the ref key from the parent is put back . This pr adds the part where the ref key is put back
> fix: set ref key as part of cloned row data

- apps/molgenis-components/src/components/task/Task.vue
- apps/molgenis-components/src/components/task/TaskList.vue
Closes #1649
graphql-request uses code that can not run the server side ( window.FormData call )
> fix: replace graphql-request with client call

- backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqlCrossSchemaRefs.java
- backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestCrossSchemaForeignKeysAndInheritance.java
TestGraphqlCrossSchemaRefs and TestCrossSchemaForeignKeysAndInheritance would only successfully run once on a clean database, but fail when attempted more than once. What happened:
__Run 1__
Start from a clean database.
Schema 1 does not exist, no dropping needed, is created empty.
Schema 2 does not exist, no dropping needed, is created empty.
Schemas are filled with data, including Schema 2 receiving data with a dependency on Schema 1.
Test succeeds.
__Run 2__
Start from a dirty database.
Schema 1 already exists, is therefore dropped, and created empty.
Schema 2 already exists, is therefore dropped, but this fails because there is still an existing data dependency on Schema 1, which no longer exists.
Test fails.
So we have to first drop Schema 2 and then Schema 1, and then create them …
> fix: table create and drop order for tests now repeatable

- backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPointCatalog.java
- backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPointDataset.java
Maybe this fixes the test problem where languages appear in a different order. Cannot reproduce locally, it never fails.
```
org.molgenis.emx2.semantics.fairdatapoint.FAIRDataPointTest > FDPDataset FAILED
org.junit.ComparisonFailure: expected:<...terms:language lang:[eng, lang:nld];
dcterms:relation...> but was:<...terms:language lang:[nld, lang:eng];
```
> Linked hashmap to fix language order

- apps/graphql-playground/src/main.js
motivation: if you have private schema then you can't use graphql-playground, even if you have signed in.
It seems session is not included. This draft PR tries to fix it. But it is working locally so that doesn't help for the testing
> fix: session in graphql-playground

- apps/molgenis-components/src/client/client.js
Fixes issue where card settings where not loaded as part of the table meta data, resulting in card template not being used.
> fix: load table settings with metaData

- apps/build.gradle
No need to check for app name to witch to vite settings as all all are now build using vite Only nuxt ssr app and molgenis-components app have others build (input / output ) folders
> chore: cleanup gradle apps build files

- Jenkinsfile
- apps/build.gradle
- apps/package.json
Workaround for gradle/yarn-workspace interaction issue. 
gradle does parallel runs of the apps build ,  yarn-workspace hoists up the dependancies to the app/node_modules folder , but yarn does not expect parallel build and then throws a file already exists exception. 
seems like a yarn issue to me , as a work around we can stop hoisting
> chore: fix jenkins build 

- apps/molgenis-components/src/components/forms/InputOntology.vue
- apps/molgenis-components/src/components/forms/InputOntologySubtree.vue
- apps/yarn.lock
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlColumnExecutor.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadataExecutor.java
- backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
- docs/molgenis/use_schema.md
Motivation: 
- sometimes same names must be used in multiple sub hierarchies; this would require prefix. To keep UI clean you can now use a shorter label.
For example:
- prescriptions:xyz 
- dispensings:xyz
in both places you would like to show 'xyz' on in the form. (in the filter statements you would like to see the prescriptions:xyz)
N.B. only works on newly created ontology tables; do we want a migration?
> feat: can define ontology labels

- apps/molgenis-components/src/components/layout/ReadMore.vue
> fix: Clicking 'show more' in a table takes you back to tables overview

- apps/schema/src/components/ColumnEditModal.vue
Tiny fix in the schema editor form. The check on new column names now also accepts whitespace as a valid character, as expected.
> fix: name check on edit column name input

- apps/molgenis-components/src/components/forms/InputOntology.vue
- apps/molgenis-components/src/components/forms/InputOntologySubtree.vue
Issue:
* when you now open ontology dialogue and search, only matches on 'name' are shown
new:
* also matching label, definition, code are shown
> feat: expand ontology search to not only search on name

- data/datacatalogue3/CatalogueOntologies/Areas of information ds.csv
- data/datacatalogue3/CatalogueOntologies/Document types.csv
- data/datacatalogue3/CatalogueOntologies/Network features.csv
- data/datacatalogue3/CatalogueOntologies/Organisation features.csv
- data/datacatalogue3/CatalogueOntologies/Study design classification.csv
- data/datacatalogue3/CatalogueOntologies/Study features.csv
- data/datacatalogue3/CatalogueOntologies/Study quality marks.csv
- data/datacatalogue3/CatalogueOntologies/Study requirements.csv
- data/datacatalogue3/molgenis.csv
add:
-Linked datasources.other linked data source (text) - Meant for when data source that is linked is not in list of data sources entered into the database. The field Linked datasources.linked data source should contain an option 'Other' and the data source name can then be specified in the new field. Just entering the other data source into the Data sources table is not preferred by EMA, because this may create ownership problems.
-Data sources.disease details other (text)
moved:
-Data sources.population age groups to Data resources.population age groups - data item also used by UMCG cohorts
delete:
-Data sources.population size - is duplicate of Data recources.number of participants
change:
-column names in ontologies description to definition
> Feat/model 3.1

- apps/schema/src/components/ColumnEditModal.vue
- apps/schema/src/components/Schema.vue
Don't show title above modal:
Don't show a vue property in the modal title
> fix: remove vue property name from title; fix: hide header behind modal

- backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/semantics/RDFService.java
- backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/semantics/rdf/ColumnToRDF.java
- backend/molgenis-emx2-semantics/src/test/java/org/molgenis/emx2/semantics/rdf/OntologyTableSemantics.java
- backend/molgenis-emx2-semantics/src/test/java/org/molgenis/emx2/semantics/rdf/RDFTest.java
- backend/molgenis-emx2-semantics/src/test/java/org/molgenis/emx2/semantics/rdf/StringsForRDFTest.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/RDFApi.java
- backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
Columns were defined in RDF export, like so:
```
<https://joeri.molgeniscloud.org/pet%20store/api/rdf/Category/column/name> a sio:SIO_000757,
qb:MeasureProperty, owl:DatatypeProperty;
rdfs:range "http://www.w3.org/2001/XMLSchema#string";
rdfs:label "name";
rdfs:domain <https://joeri.molgeniscloud.org/pet%20store/api/rdf/Category> .
```
Where `https://joeri.molgeniscloud.org/pet%20store/api/rdf/Category/column/name` is the IRI that identifies this column (_name_) for this table (_Category_). 
This IRI is then used to express row values, e.g. where _cat_ is an instance of _Category_:
```
<https://joeri.molgeniscloud.org/pet%20store/api/rdf/Category/cat> a <https://joeri.molgeniscloud.org/pet%20store/api/rdf/Category>,
sio:SIO_001187, qb:Observation;
qb:dataSet …
```
> fix: column IRI in RDF API is now retrievable

- Jenkinsfile
the java container pushes a new chart version to the repo. the new version needs to be available before it can be used by rancher
> chore: wait for chart publish

- Jenkinsfile
- README.md
Motivation is to reduce Jenkins builds, that currently builds every PR twice (once for the PR and once for the source branch).
Solution is that only the 'PR' and 'master' branches have steps to execute (I couldn't see how to prevent the jenkinsfile to run at all, unless changing the jenkins config server side).
The other branches should skip all steps.
> build: try to have build only run in case of 'master' or when PR

- .circleci/config.yml
- Jenkinsfile
Switch from gradle-circle publish to jenkins publish using kaniko build&publish container
Gradle still builds the app but the docker image is build and published  via kaniko ( triggerd from Jenkins )
- PR builds go to: docker.io/molgenis/ssr-catalogue-snapshot
- Master builds go to: docker.io/molgenis/ssr-catalogue
> chore: publish ssr-catalogue image via jenkins

- Dockerfile
Kaniko does not to be run from app folder ( like gradle) therefore run it from nuxt3 folder and update the file path for the copy
> chore: fix kaniko run

- backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/beaconv2/requests/BeaconRequestMeta.java
Added 'apiVersion' field to BeaconRequestMeta for compliance with https://github.com/ejp-rd-vp/vp-api-specs. Right now, requests as defined by the spec fail because they have apiVersion which cannot be parsed into the object structure.
> Add API version to request meta for compliance

- apps/nuxt3-ssr/gql/fragments/ontology.js
Due to the lack of recursive query possibilities the partial tree can not be reconstructed from the selected ontology items. This change works around this missing feature by fetching up to 8 levels up (from the selected ontology item). This is sufficient for the current ontologies used but does not solve te general case.
Closes https://github.com/molgenis/molgenis-emx2/issues/2044
Related to: https://github.com/molgenis/molgenis-emx2/issues/2047
> fix: fetch missing tree parts work-around

- apps/nuxt3-ssr/components/DefinitionList.vue
- removes the dot graphic if the list contains only single item
> fix: render list content with single item without list markup

- backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPointDistribution.java
Some null checks were missing on properties that are okay to be empty
> fix: add null checks for non required properties

- backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java
- backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqSchemaFields.java
If column is ref type column use the reference column to find the name
Closes #2175
> fix: Orderby on non 'root' table column fails #2175

- .jenkins/build-pod.yaml
- Jenkinsfile
- build.gradle
- helm-chart/questions.yaml
- helm-chart/templates/deployment.yaml
- helm-chart/templates/ingress.yaml
- helm-chart/templates/svc.yaml
- helm-chart/values.yaml
Edit helm chart to include ssr catalogue for use in preview.
- Setup ingress to proxy ssr-app requests to the node app 
- Add ssr-catalogue as a service to the chart
In Jenkins CI build replace rancher commands with direct helm and kubectl commands
- Add helm/kubectl container to Jenkins build 
- Fetch kubectl settings and auth from the vault
> chore: Add ssr-catalogue to helm template for preview

- apps/nuxt3-ssr/nuxt.config.ts
Compress assets using brotli
Longer build times due to compression 
Smaller assets ( css in particular ) leading to 25% increase on lighthouse performance for 'empty' page
> feat: enable build time compression of asset files

- apps/molgenis-components/src/client/client.ts
- apps/molgenis-components/src/client/queryBuilder.test.ts
- apps/molgenis-components/src/client/queryBuilder.ts
This fixes issue with graphql creating queries that kills server, by removing query expansion into fields that may return large lists of data (i.e. ref_array, ontology_array).
We still might choose to reduce default expandLevel from '2' to '1' to be safe, but I think we might be fine this way.
> fix(client): graphql query expansion bring server to its knees

- apps/molgenis-components/src/components/account/MolgenisSession.vue
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/controllers/OIDCController.java
related to [#9924](https://trac.molgeniscloud.org/ticket/9924) [new](https://trac.molgeniscloud.org/query?status=new&order=position&col=id&col=position&col=summary&col=status&col=type&col=milestone) [story](https://trac.molgeniscloud.org/query?status=accepted&status=assigned&status=new&status=reopened&type=story&order=position&col=id&col=position&col=summary&col=status&col=type&col=milestone)
_As data manager I want to be redirected to the schema overview when logging in with OIDC_
this pr sets up the 'default' behaviour, other PR can extend with passing a redirect location from (schema)settings
> feat: Return to location after OIDC login

- backend/build.gradle
- backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/AbstractDataLoader.java
- backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/AvailableDataModels.java
- backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/DataCatalogueCohortStagingLoader.java
- backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/DataCatalogueCohortStagingLoader3.java
- backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/DataCatalogueLoader.java
- backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/DataCatalogueLoader3.java
- backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/DataCatalogueNetworkStagingLoader.java
- backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/DataCatalogueNetworkStagingLoader3.java
- backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/FAIRDataHubLoader.java
- backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/PetStoreLoader.java
- backend/molgenis-emx2-datamodels/src/test/java/org/molgenis/emx2/datamodels/TestLoaders.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlColumnExecutor.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/RunMolgenisEmx2.java
- backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
motivation: increase test coverage, and make more robust. 
todo:
> build: refactor loaders to prevent conflicts and make sonar happy again

- apps/molgenis-components/src/client/client.ts
- apps/molgenis-components/src/components/tables/TableExplorer.vue
Fixes: #2277 
Note: 
- In the backend tableName is used, not a tableID 
- TableExplorer's property 'tableName' is a ID and not a name
> fix: truncate

- apps/nuxt3-ssr/app.vue
- apps/nuxt3-ssr/error.vue
In future release the public config will no longer be the default, therefore explicitly use the public path in reference to public config setting. Removes deprication warning during dev.
> chore: Update config ref

- apps/molgenis-components/src/components/forms/EditModal.vue
- apps/molgenis-components/src/components/forms/RowEditFooter.vue
point of draft is that it can be saved with errors, however, primary key is required
closes #2366
> fix(forms): can save draft when errors exist

- apps/molgenis-components/src/components/layout/MolgenisMenu.vue
fixes: #2341
Our main menu knows nothing about the routing done in our app. Still we want to be able to link to the inside of our apps like `tables/#/Subject`.
This fix makes it possible by forcing a reload if there is a '#' in the url.
> fix: force menu links with anchor reload

- apps/catalogue/src/views/VariableExplorer.vue
fixes: #2414
the filters use 'pid' but that data field is empty in the data, switched it to filter on 'id'
> fix: use id and not pid in cohort filter in variable explorer

- gradle.properties
Fixes the issue that local builds on windows show incorrect characters when using firefox
> fix: local builds on windows now show correct encoding with firefox

- backend/molgenis-emx2-semantics/src/main/java/org/molgenis/emx2/semantics/LinkedDataService.java
The linked data JSON-LD api was broken because it did not support ontology term lists, this has been fixed
> Fix: JSON-LD works again, supports ontology list

- backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestQuery.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java
Note: PR adds failing test to show issue
Note2: Inversion of control with simple unit test for branches (default, asc, desc, ref , no ref) could have prevented typo from reaching release
> fix: order by ref column sort order

- apps/molgenis-components/src/components/forms/RowEdit.vue
errorPerColumn should return empty object by default ( instead of undefined)
> fix: row edit

- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/index.vue
- docs/catalogue/cat_server_side-rendered.md
note: default label and text can be overridden via setting ( see docs )
> feat: Add datasets/subcohorts info card to landing

- apps/nuxt3-ssr/.gitignore
- apps/nuxt3-ssr/app.vue
- apps/nuxt3-ssr/custom-build.js
- apps/nuxt3-ssr/custom-dev.js
- apps/nuxt3-ssr/error.vue
- apps/nuxt3-ssr/package.json
- apps/nuxt3-ssr/utils/fingerprint.js
Generate empty fingerprint file for each dev run.
This way we can be sure there is a fingerprint file without having file in the repo
> fix: improve ssr style cache busting dev setup

- backend/build.gradle
This fixes the "SLF4J: No SLF4J providers were found." warning
Closes #2581
> fix: bump slf4j2 logger impl to allow 2.x logger

- apps/molgenis-components/src/components/tables/RenderValue.vue
- apps/molgenis-components/src/components/tables/RowCard.vue
Set of improvements to make cards work again as intended.
Before this PR: 
After this PR:
> fix: fix broken explorer cards

- backend/molgenis-emx2-datamodels/src/test/java/org/molgenis/emx2/datamodels/TestLoaders.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java
closes #2092 
This is using the most complex data model feature we have which we should add to our pet store somehow, that is having composite pkey (so multiple columns together make up the key) AND that at least two of these columns are a reference (type=REF) that also have composite keys AND these references have some overlap (i.e. their composite key has same reference) which is collapsed in the user interface using the ‘refLink’ feature. As a consequence when trying to find unique rows the bug was that same column was included more than once (in the example: ‘resource’) 
N.B. to test I have used the fact that TestLoaders actually loads the catalogue schema so we can directly test the example reported in #2092
> fix: groupBy with composite pkey containing refs are linked via refLink

- apps/catalogue/src/components/CohortCards.vue
- apps/molgenis-components/src/client/client.ts
previously, when using newClient(), so without specifying the schemaName, the schema would not be cached.
This potentially can still result in many calls.
with this fix, we give a special name when schemaName === undefined to also cache the current schema.
> fix: javascript client should also cache current (nameless) schema

- apps/molgenis-components/src/components/tables/TableMolgenis.vue
Make sure large tables e.g. catalogue -> databanks don't scroll away the molgenis application i.e. elements like the top bar menu.
> fix: make large horziontal tables not scroll out of the application

- .circleci/config.yml
- apps/build.gradle
motivation: 
* local builds now sometimes fails with yarn 'finished with non-zero exit value 139'
* we now set these options only on circleci and azure
* I don't know why but 'directory' build takes much memory
solution:
* move the options into gradle so runs everywhere
potential issues:
* might result in build issues on smaller systems.
> build: move NODE_OPTIONS environment into gradle into gradle

- apps/molgenis-components/lib/main.js
- apps/molgenis-components/src/client/client.ts
- apps/molgenis-components/src/components/forms/Info.vue
- apps/molgenis-components/src/components/forms/InputEmail.vue
- apps/molgenis-components/src/components/forms/baseInputs/BaseInputProps.ts
- apps/settings/src/components/Members.vue
- Email input in member settings nows has a email check and will also validate 'user' and 'anonymous'
- Added a information icon
- Fixed information icon to make sure it can display larger text and that the 'hidden' state would blok buttons below it.
- Fixed InputEmail. It was broken, the TS typing is not implemented completely at the vue side of things. No good workaround so we are back using vue typing for the props. 
See: https://github.com/vuejs/core/issues/4294 and https://github.com/vuejs/core/issues/8286 "If understand correctly this issue (which I also ran into) basically means that Vue 3 only supports "trivial" TypeScript types for props." - [gorankarlic](https://github.com/gorankarlic)
> fix(settings): Have a better email input in member settings

- apps/catalogue/package.json
- apps/central/package.json
- apps/directory/package.json
- apps/ern-reconnet/package.json
- apps/gportal/package.json
- apps/helloworld/package.json
- apps/molgenis-components/package.json
- apps/molgenis-viz/package.json
- apps/pages/package.json
- apps/reports/package.json
- apps/schema/package.json
- apps/settings/package.json
- apps/tables/package.json
- apps/tasks/package.json
- apps/yarn.lock
Reverts molgenis/molgenis-emx2#2656
Apparently nuxt3 doesn't like vue-router 4.2.4
> Revert "fix(deps): update dependency vue-router to v4.2.4"

- apps/molgenis-components/src/components/forms/InputRef.vue
- apps/molgenis-components/src/components/forms/InputRefItem.vue
- apps/molgenis-components/src/components/tables/TableRow.vue
Fixes warning from trying to overwrite computed (test: components library -> inputRef -> select some ref -> see console) and fixes an initialization bug where the rowkey would still be null when opening the modal view (test: in the component library -> goto inputRef -> click view as table at the last example)
> fix(molgenis-components): inputref

- apps/nuxt3-ssr/components/Pagination.vue
Closes #2562
Note: the down side of this solution / work around is that when the user used the browser-back-button ( on a page containing a Pagination component) the page gets reloaded from the server ( instead of having a spa data refresh). 
This workaround is need as the router does not react to query param updates ( triggered via the backbutton ), it does react to changes in the route itself ( going to a different location instead of only change the page number)
> fix: 2562 browser back button does not go back to previous page

- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/ZipApi.java
Headers moved up before generating and streaming content.
Closes #1211
> fix: Move streaming after headers. closes #1211

- tools/pyclient/README.md
- tools/pyclient/dev/dev.py
- tools/pyclient/src/molgenis_emx2_pyclient/client.py
- tools/pyclient/src/molgenis_emx2_pyclient/exceptions.py
This PR aims to prevent resource leaks. Usage of the Pyclient can cause sessions on a Molgenis server to be created without being properly closed, either due to an error occuring during execution, termination of the program or simply due to forgetting to call the signout() method.
The creation of too many sessions that are not closed causes memory problems on the server.
This PR fixes that by forcing the client to be used as a context manager. The context manager ensures that the signout and closing of the session are performed under normal use and also in the scenario's listed above.
> fix: ensure properly signing out of Pyclient session

- apps/catalogue/src/views/ResourceListView.vue
this fixes that ResourceDetails view gives aggregate instead of table view
Compare
- https://emx2.dev.molgenis.org/catalogue/catalogue/#/cohorts
- https://emx2.dev.molgenis.org/catalogue/catalogue/#/datasources
Agains the PR
- https://preview-emx2-pr-2749.dev.molgenis.org/catalogue-demo/catalogue/#/cohorts
- https://preview-emx2-pr-2749.dev.molgenis.org/catalogue-demo/catalogue/#/datasources
Hopefully closes #2743
> fix: catalogue shows aggregate instead of table view

- apps/molgenis-components/src/components/tables/RoutedTableExplorer.vue
- apps/molgenis-components/src/components/tables/TableExplorer.vue
- apps/nuxt3-ssr/app.vue
- apps/nuxt3-ssr/components/HyperLink.vue
- apps/nuxt3-ssr/components/content/ContentBlockIntro.vue
- apps/nuxt3-ssr/components/content/ContentGenericItem.vue
- apps/nuxt3-ssr/components/content/type/ContentTypeHyperLink.vue
- apps/nuxt3-ssr/package.json
- apps/yarn.lock
We have issue that we now can disable 'canView' to accomodate when user has 'aggregate' permission only. But default was 'false' which lead to random errors in other places using the table explorer. With this fix we disable that, however we must make sure this doesn't lead to errors in case user has only aggregate.
> fix: default of table explorer to be 'canView'

- backend/build.gradle
When running the WebApiSmokeTests on Windows, the following error would pop up:
"java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.util.Map java.lang.ProcessEnvironment.theCaseInsensitiveEnvironment accessible: module java.base does not "opens java.lang" to unnamed module". 
The issue is fixed by adding "--add-opens java.base/java.lang=ALL-UNNAMED" as a test JVM parameter in the build.gradle file on the backend.
> fix:emx2_testing_on_windows

- apps/nuxt3-ssr/components/CollectionEventDisplay.vue
A previous change renamed DefinitionList to CatalogueItemList The use of this component in the CollectionEventDisplay was not renamed
Closes #2892
> fix: Rename DefinitionList to CatalogueItemsList

- tools/pyclient/src/molgenis_emx2_pyclient/client.py
Addresses issue #2875.
Do you agree it should say `anonymous` when not signed in? I used this term as it shows the same schemas as the `anonymous` viewer in the UI would see, but I'm not entirely happy with the word
> fix: Pyclient status after signing out

- .circleci/config.yml
- ci-build-images/Dockerfile
use emx2 build images that has node and python installed
This means the node / python binarie  repositories only need to be reachable when a new image is build instead of each pr/master build.
> chore: use custom image for ci build

- backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/PetStoreLoader.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/TestDatabaseFactory.java
motivation: parallel tests get interactions sharing the same database because setActiveUser may lead to permission changes that break another test
drawback: this results in overhead in database instantiation (i.e. loading the metadata).
advantage: much more similar to our production environment where users don't share their database instance by having database instance per session.
> build: don't share database instance between tests because setActiveUser may results in build errors

- apps/settings/src/components/MenuDesign.vue
- apps/settings/src/components/MenuManager.vue
This request introduces a fix for issue #2739. Currently, when a the delete button is clicked, the first item in the list `items` is removed. This is not desirable as it does not take into account if the menu items were reordered or changed.
After testing various options (e.g., click event on the delete button, filtering the array `items` in the draggable component etc.), it was decided to emit the key of the target element (in `MenuDesign`) into the parent element (in `MenuManager`).
- New emit event `@delete`:  `items.splice(...)` is replaced by `$emits('delete', ...)`. 
- New method for removing items: In `MenuManager`, there is a new method for deleting menu links from `this.drafts`
- Fix undefined in html attributes: Before, the key was `idx`. However, this was always undefined. The …
> fix: created emit for deleting menu items

- apps/molgenis-components/src/client/IClient.ts
- apps/molgenis-components/src/client/client.ts
- apps/molgenis-components/src/components/forms/InputOntology.vue
Fixes #2898 by reducing the amount of data queried from the server.
Created function `fetchOntologyOptions` specifically for fetching ontology table for an ontology options list.
* fetchOntologyOptions generates a lean query to fetch an ontology without definition, ontologytermURI, nested parent/child data, mg metadata, etc.
* function is implemented in client.ts, IClient.ts, InputOntology.vue
> fix: improved ontology loading in options menu

- apps/molgenis-components/src/components/forms/RowEdit.vue
- backend/molgenis-emx2-sql-it/src/test/java/org/molgenis/emx2/sql/TestInherits.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/Migrations.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadataExecutor.java
- backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration13.sql
the bug was that a default for mg_tableclass was set. And then records added could use that default value, defaulting to the first subclass of a table. 
Until PR #2884 this bug didn't have effect because in row_edit form column default values are only applied to visible columns. However, in #2884 now default are applied to all columns, which include the mg_tableclass.
This PR removes that default for new mg_tableclass column instances, and has a migration to delete the defaultValue in existing mg_tableclass instances
closes #2926
> fix: mg_tableclass should not have default value. closes #2926

- docs/molgenis/use_schema.md
Breaking change: you cannot set refTable when your data type is not a ref(_array) or ontology(_array). 
This will break existing databases. Please download your data first and empty refTable in error cases and reload again. 
BREAKING CHANGE
> feat!: added check that refTable can only be set for refs

- azure-pipelines.yml
CI env is read by gradle during build, when set to true it uses the image node instead of downloading node on each build this should improve stability and reduce build times
> chore: Add CI = true env var to azure build

- backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RDFService.java
- backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/RDFTest.java
- test case for verify that the qb:dataSet predicate is used
- use IRI_DATASET_CLASS and IRI_DATASET_PREDICATE to distinguish between the class and the predicate
- fix the rowsToRdf method to use the IRI_DATASET_PREDICATE
Closes #2931
> fix: an instance of Pet should refer back to the collection of pets with qb:dataSet and not qb:DataSet

- apps/molgenis-components/src/components/tables/TableMolgenis.vue
- apps/schema/src/utils.ts
stepz2rep: 
go to the schema editor 
add a column to a table, without entering a label
save
look at the table, the column header is empty
> fix: columns headers of columns without labels were empty

- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/Migrations.java
- backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration14.sql
Some metadata columns might be corrupt due to data that was valid add the time of entry but later became invalid due added checks. Specifically; only ref type columns can have a non null value in the column_metadata.refTable column This migration remove all column_metadata.refTable entries for all non ref type rows
> fix: Add cleanup migration

- backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RDFService.java
- backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/RDFTest.java
fix #2928 
- Check if a column is a HYPERLINK or HYPERLINK_ARRAY and set it to be a owl:ObjectProperty
- Added unittest
> Fix #2928 columns of type HYPERLINK or HYPERLINK_ARRAY should be an owl:ObjectProperty

- backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RDFService.java
- backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/RDFTest.java
fixed #3048 Add an rdfs:label to all instances
- created a getLabelForRow that creates a label by concatenating all the primary key values for now
- add an rdfs:label predicate to a row in rowsToRDF for the data tables
- added a test
> Add an rdfs:label to all instances

- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/Column.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/HasLabelsDescriptionsAndSettings.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/TableMetadata.java
- backend/molgenis-emx2/src/test/java/org/molgenis/emx2/TestTableColumnLabels.java
closes #3036
To test, add a label using schema editor interface and then delete it again. 
(n.b. of course better solution would be to set to null but given that we have existing data this will also work for those cases)
> fix: when label is empty string it should return name. closes #3036

- backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java
to test:
* go to pet store
* edit a Tag to have label, e.g. 'color' = 'kleuren'
* edit Pet pooky and chose the 'kleuren'
* save
* reload
* then open pooky again and save without changes
before bug:
* error 
With this fix:
* save
N.B. we have loosened type constraints to ignore non-primary key values on reference fields. However, this might lead to expectation that any changes on those will also be changes which is not the case. Meanwhile this will make it easier to make clients for this API so we think this is a good compromise.
Alternative considered:
Alternative solution would be to filter non pkey fields in InputOntology.vue value on loading and emit that as model-value
> fix: ontologies with label set cannot be saved. closes #3031

- apps/meta-data-utils/package.json
Add the test-ci key to the script, this is the key the gradle task scans for
> chore: add test hook

- apps/schema/src/utils.ts
- apps/tables/src/components/ListTables.vue
- backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/json/Schema.java
- backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqlCrossSchemaRefs.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/SchemaMetadata.java
closes #3071
todo:
Sorry to have wasted your time with 'fundamental decisions' as you can see original bugfix was only 1 line.
> fix: table explorer showed schemas from other schemas. closes #3022"

- apps/molgenis-components/src/components/forms/InputOntology.vue
- apps/molgenis-components/src/components/forms/InputOntologySubtree.vue
the click handlers of the inputOntology where on the SVG tags, that works terribly. Wrapt a span around it that made the click way more consistent.
You can now also click on other parts than only the name to open en select Ontologies.
Also made the 'selected' not change type between boolean and string.
Note: deselecting in component-library still triggers an internal error. I was not able to fix that.
> fix(molgenis-components): have working click handlers in inputOntology

- apps/nuxt3-ssr/sample-nginx.conf
Add config to ssr-catalogue sample config 
If a catalogue needs to skilp the catalogue part ( i.e. should always use the /all route) then redirect the non-all routes to the all route version of the same route.
for example 
https://catalogue-acc.molgeniscloud.org/UMCG/ssr-catalogue/cohorts 
becomes 
https://catalogue-acc.molgeniscloud.org/UMCG/ssr-catalogue/all/cohorts
> chore: extend ssr nginx config with single catalogue workaround

- apps/nuxt3-ssr/interfaces/types.ts
- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
- apps/nuxt3-ssr/utils/errorLogger.test.ts
- apps/nuxt3-ssr/utils/errorLogger.ts
feat: log ssr data fetch resp errors 
Add util function the log data fetch errors and show api error response message 
- note still need to use everywhere (where needed )
- maybe wrap all gql data fetching in composable that includes error logging/handling
> feat: log ssr data fetch resp errors

- apps/directory/src/components/report-components/CollapseComponent.vue
fixes: #3083
This is a safari only render issue, updating the text in the summary tag removes the click state. 
Workaround is to add a span en change its content.
> fix: safari details render issue workaround

- tools/pyclient/README.md
- tools/pyclient/dev/dev.py
- tools/pyclient/requirements.txt
- tools/pyclient/src/molgenis_emx2_pyclient/client.py
- tools/pyclient/src/molgenis_emx2_pyclient/exceptions.py
- tools/pyclient/src/molgenis_emx2_pyclient/graphql_queries.py
- tools/pyclient/src/molgenis_emx2_pyclient/utils.py
This request addresses issue #2934 by adding new methods to the python client for managing schemas. Specifically, this includes the following methods:
- `create_schema`: create a new schema. Users can create an empty schema that will be populated by an external `molgenis.csv` file or using a schema template.
- `delete_schema`: delete a schema from an emx2 instance
- `update_schema`: update a schema's description
- `recreate_schema`: delete a schema and recreate it.
- `get_schema_metadata`: retrieve information about a schema
~~In addition, `sigout` was removed from the client as it is no an available graphql option.~~
Additional tasks?
> feat: expansion of the python client

- backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java
- backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqlSchemaFields.java
To reproduce, on master:
- use the junit test but without the fix, and then with the fix
OR
- load attached schema
- create a row in ProjectUnits
- notice error in console for refback 'planning' when opening ProjectUnits
Then do same in preview
- see the refback does load properly and you can add/edit some planning records
The example schema:
[molgenis.csv](https://github.com/molgenis/molgenis-emx2/files/13646140/molgenis.csv)
> fix: graphql key filter doesn't work when having names with spaces breaking refback.

- apps/molgenis-components/src/client/client.ts
- apps/molgenis-components/src/components/tables/TableMolgenis.vue
So the rules should be:
- labels are only used in forms
- the names are used in table explorer and csv upload/download
- the identifiers are use in API
Out of scope:
- a potential future feature request is to show identifiers in table view AND ability to set identifiers manually.
> feat: table explorer should show names instead of labels

- apps/directory/src/App.vue
- apps/directory/vite.config.js
fixes: https://github.com/molgenis/molgenis-emx2/issues/3110
made to replace: https://github.com/molgenis/molgenis-emx2/pull/3146
#3146 was getting ugly by trying to drill down the styling via the molgenis component, i kept finding more and more deeper issues. Just overriding the css is way cleaner. 
Note: The emx2 custom menubar color from the settings menu will not work within the directory app.
> feat: add bbmri styling via css override

- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/RDFApi.java
If the port is the well known port for the schema, i.e. 80 for http or 443 for https it should not be put in the url. 
fixes #3164
> Don't put the port in the URL if it is a well-known port

- apps/directory/src/router/index.js
- apps/directory/src/views/CollectionReport.vue
fixes: #3163
fixed by reloading the data after change in router state
Note: i also added a scroll to top after following a router link. I think this is a better user experience than having users be at the bottom of a page at random moments.
> fix: reload collectionReport on routeing change

- apps/directory/src/stores/collectionStore.js
Added the correct ID in the where clause of the factQuery in the collectionStore and the facts tables are now rendered properly in the collection reports. 
fixes: #2981
> fix: facts table on directory app

- apps/cranio-provider/src/components/ProviderSidebar.vue
- apps/cranio-provider/src/styles/variables.scss
In the `cranio-provider` vue app, there is a "Submit Patient" button in the sidebar component. It is currently disabled as the data model wasn't finished, but the button can be enabled. This request enables the button by redirecting users to the `Subjects` table.
To Do:
> fix: set url of "submit patient" button

- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/datasources/[datasource].vue
- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/datasources/index.vue
- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
- apps/nuxt3-ssr/utils/ontologyUtils.ts
how to test:
- this fixes that layout of CTA on overview pages was unequal. E.g. look at eosc4cancer. Proper fix should be to fix the layout itself.
- also fixes the logo of the 'network' cta
todo:
> fix(catalogue): make descriptions of cta on overview page about equal

- apps/ern-skin/src/components/CustomPageHeader.vue
- apps/ern-skin/src/styles/index.scss
- apps/ern-skin/src/views/view-about.vue
- apps/ern-skin/src/views/view-documents.vue
- apps/ern-skin/src/views/view-home.vue
- apps/molgenis-viz/src/styles/heightwidth.scss
Changes to the layout of the header component were made in the EMX1 version and approved. Now, these changes must be made to the EMX2 version. However, the implementation differs. In the EMX2 version, I created a new header component (`<CustomPageHeader`>) that stacks the header image and content (title and subtitle). For the time being, this will work as I do not wish to rewrite the existing page header component (although this might be useful in the future). 
This pull request contains the following changes to the `ern-skin` vue app.
> feat: redesigned header image and title

- apps/catalogue/src/components/VariableListItem.vue
- apps/catalogue/src/store/actions.js
how to test:
In catalogue-demo:
Brenda_ variable is een voorbeeld waarbij het niet werkt (maar in deze PR wel)
headcircage_0 is een voorbeeld waarbij wel het eerste time point is gemapped door een cohort en je wel door kan klikken naar de details
Please test:
closes #1894
close #2439
> fix: mappings not shown for repeated variables. closes #2439

- apps/directory/src/stores/checkoutStore.js
how to test:
- Directory App: Select collections, create the request and send to the negotiator. When pushing the send button, a create_request query is created. In this query there should be collectionId and biobankId instead of collectionID and biobankID.
todo:
> fix(directory): change ID to Id in the negotiator request

- apps/dev-proxy.config.js
- apps/schema/package.json
- apps/schema/src/components/ColumnEditModal.vue
- apps/schema/src/components/SchemaToc.vue
- apps/schema/tsconfig.json
Currently it is possible to have a computed that is required by first setting required to true and then adding a computed expression.  Having a computed expressions should set required to false to prevent saving problems in forms.
Additionally: 
- This pr sets default for required to false instead of expression, since that is a more sensible default.
- Fixes a bug where creating/editing an AUTO_ID column let the visibility field visible and some other side effect related to auto id in the schema editor.
- Fixes a bug where you can't add columns to a new table that is not saved yet.
how to test:
- Go to the schema editor 
- Add a column
- Set required to true / condition
- Note that the computed field is hidden
- Set required to false
- Add a computed expression
- See that the required …
> fix: required computeds

- apps/molgenis-components/src/client/IClient.ts
- apps/molgenis-components/src/client/client.ts
- apps/molgenis-components/src/components/tables/AggregateTable.vue
- aggregate function can only be computed for a single field
- field must be of type int,dec,long
- hide option if table does not include and aggregate fields
https://github.com/molgenis/molgenis-emx2/assets/47183404/5921925c-c43b-446e-9d87-9d282960104f
> feat: Add option to select (sum) function in aggregate table

- e2e/tests/catalogue/catalogue-test_1.spec.ts
- added Playwright tests based on [catalogue test setup](https://github.com/molgenis/molgenis-emx2/pull/3399)
how to test:
- In vscode navigate to `/e2e/`
- Open the README.md and run `yarn install` and `npx playwright test` (run once)
- Make sure you have installed the vscode plugin 'Playwright Test for VSCode'
- Navigate to `/e2e/tests/catalogue/catalogue-test_1.spec.ts` to review the test code
- Use the playwright plugin to run the test (Flask icon) and run this specific test
> Chore: e2e add catalogue test 1

- apps/directory/src/property-config/initialCollectionColumns.js
fixes #3086
The collaboration information (commercial and non-for-profit) are now displayed in the collection report.
> fix: missing collaboration information on collection report

- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/index.vue
- e2e/tests/catalogue/navigate-to-next-page-on-cohorts-list-page.spec.ts
- keep query reactive, do no read value during fetch
Closes #3415
how to test:
todo:
> fix: fix cohorts paging reactivity

- apps/nuxt3-ssr/package.json
- apps/yarn.lock
@types/node 16.x is no longer used
> chore: remove dep, no longer needed with current nuxt setup

- apps/build.gradle
excludes more output folders during js build in order to be able to build on windows.
how to test:
todo:
> fix: exclude folders on build

- apps/nuxt3-ssr/components/CohortCard.vue
- apps/nuxt3-ssr/components/DataSourceCard.vue
- apps/nuxt3-ssr/components/NetworkCard.vue
- apps/nuxt3-ssr/components/ReferenceCard.vue
- apps/nuxt3-ssr/components/ResourceCard.vue
- apps/nuxt3-ssr/components/content/ContentBlock.vue
- apps/nuxt3-ssr/components/content/ReadMore.vue
- apps/nuxt3-ssr/components/content/type/ContentTypeText.vue
- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
- e2e/tests/catalogue/catalogue-description.spec.ts
- Pass readmore as prop instead of slot, it only takes props
- Fix readmore style on landingpage in header, extract style to enable reuse
Closes #3459
how to test:
todo:
> fix: 3459 missing settings text

- apps/nuxt3-ssr/components/SearchResultsCount.vue
- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/datasources/index.vue
- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/networks/index.vue
- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
- e2e/tests/catalogue/search-results-count.spec.ts
This PR is a continuation of #3469 which added a component to display the number of search results in each view. Search results are now displayed in each view (cohorts, data sources, and variables) and e2e testing is available for all pages.
how to test:
- Navigate to the preview:
- Navigate to the Cohorts, Data Sources, and Variables pages
- Note the counts above the results
- Apply filters and note the change
todo:
> feat: list view counts

- apps/nuxt3-ssr/components/VariableCard.vue
This request address issue #3418. To prevent variable names from going out of bounds, names are now broken when they reach the width of the parent element. Names and labels are kept in the same column arrangement.
how to test:
- Navigate variables view in the preview
- Note the word breaks
todo:
- ~~updated docs in case of new feature~~
- ~~added tests~~
> fix: added word break to variable names

- tools/pyclient/src/molgenis_emx2_pyclient/client.py
- tools/pyclient/src/molgenis_emx2_pyclient/metadata.py
I forgot to make the imports of the exceptions in metadata.py relative.
This causes an import error when using the client, as parts of metadata.py are automatically imported in the client.py module
how to test:
- build and install the Python package
- run the dev.py script
- see that it is possible to import the exceptions from the correct file within the package again
todo:
> fix: relative import of exceptions in metadata.py

- apps/nuxt3-ssr/components/SettingsMessage.vue
- apps/nuxt3-ssr/components/content/ContentBlockIntro.vue
- docs/molgenis/dev_messageapi.md
Closes #3504
how to test:
1. Find cohort with contact email set, and view the contact modal ( click on the Contact button)
2. Sign in as admin and add/edit a setting with key: 'CATALOGUE_BCC_MSG' and some message as value
3. Find cohort with contact email set, and view the contact modal ( click on the Contact button), message should be shown
4. Sign in as admin and remove the setting with key: 'CATALOGUE_BCC_MSG' 
5. Find cohort with contact email set, and view the contact modal ( click on the Contact button), message should no longer be shown
note: the message fetch is only done client side to avoid initial ssr page render performance impact
todo:
- ~[ ] added tests~ skipped, small feature, depends on settings config, settings config is test elsewhere 
Closes #3504
> feat: Show CATALOGUE_BCC_MSG value if set

- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/index.vue
Deleted example on catalogue homepage, because it created confusion.
> chore: edit project catalogue text

- apps/directory/src/functions/viewmodelMapper.js
fixes #3497
When certain filters would be applied, the directory app would not retrieve collection details for some biobanks due to parent collections being filtered away. The fix solves the issue by filtering also parent collections.
> fix: collection details not shown in the directory app

- apps/nuxt3-ssr/components/BottomModal.vue
- apps/nuxt3-ssr/components/FilterWell.vue
- apps/nuxt3-ssr/components/SideModal.vue
- apps/nuxt3-ssr/components/harmonization/HarmonizationLegendDetailed.vue
- apps/nuxt3-ssr/components/harmonization/HarmonizationLegendMatrix.vue
The VDropdown component from the floating-vue lib results in a hydration errors due to the way the lib edits the dom issue is reported: https://github.com/Akryum/floating-vue/issues/1006
Workaround implemented as proposed in: https://github.com/Akryum/floating-vue/issues/1006#issuecomment-2007638042
how to test:
- load nuxt app page that contains VDropdown component in dev mode before this pr and check the console log; lots of warnings about hydration mismatch in vdropdown ( popper )
something like: <img width="627" alt="Screenshot 2024-03-20 at 14 53 02" src="https://github.com/molgenis/molgenis-emx2/assets/47183404/d9013e83-ead3-4e05-a643-f6a0ab5f26bc">
- load nuxt app page that contains VDropdown component in dev mode from pr and check the console log; hydration error related to …
> fix: floating vue hydration mismatch

- tools/pyclient/src/molgenis_emx2_pyclient/client.py
- tools/pyclient/src/molgenis_emx2_pyclient/graphql_queries.py
GraphQL queries that modify tables in a schema need the tables' _id_ in the request URL instead of the _name_. This PR addresses this oversight in the initial versions of the Pyclient and provides a fix.
how to test:
todo:
> fix: Pyclient query URLs

- .circleci/config.yml
This PR fixes the release of the molgenis-emx2-pyclient to (test)PyPI. Currently only a new version is release if the commit-message contain (emx2-py-client).
Scenarios to test:
> build: fix python release

- apps/cranio-provider/README.md
- apps/cranio-provider/src/App.vue
- apps/cranio-provider/src/components/AppFooter.vue
- apps/cranio-provider/vite.config.js
- apps/cranio-public/src/views/view-documents.vue
- apps/molgenis-viz/src/components/display/FileList.vue
This PR addresses the issues listed in #3550. Specifically, this fixes the handling of images and organisation-level metadata in the `cranio-provider` vue application, as well as the display and download for documents.
how to test:
- Go to the preview
- Click on the `ErnCranioStats` schema -> Documents. Note documents displayed on the page
- Click on the `BE1` schema: note the image displayed at the top of the page. This should match the name of the file listed in the table ErnCranioStats >> Organisations
- In the `BE1` schema, go to the advanced settings page. Note the value for the setting `CRANIO_PUBLIC_SCHEMA`. Log in as admin, change the value, and refresh, and navigate back to the home page for the `BE1` schema. There should be no image and an error should be shown. Undo the change …
> fix: cranio app file handling

- apps/nuxt3-ssr/components/SubCohortDisplay.vue
- apps/nuxt3-ssr/components/content/cohort/GeneralDesign.vue
- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/[cohort]/subcohorts/[subcohort].vue
Rename Population to Counties
Closes #3533
how to test:
- see issue details
> fix: 3533 erroneously labelled "Population"

- apps/central/src/components/SchemaEditModal.vue
The edit schema modal has been broken for some time. The only way to update the description is through the GraphQL interface. This has created a blockage for some projects. I had a look into this and it is an easy fix.
The issue was caused by a conflict in the prop names. In the `apps/central`, the component `Groups` uses the component `SchemaEditModal`. Here the prop `schemaId` is declared, but it isn't defined in the component. I'm guessing this is leftover from the ID-name fixes. I'm guessing the use of ID is preferred so I changed the prop to `schemaId` instead of `schemaName`.
It looks like this addresses the following issues: #3468, #3107, and #3336
how to test:
- Log in to the preview
- Sign in as admin
- Click the edit button for any schema and add/change the description.
- Save …
> fix: update schema modal

- apps/directory/src/stores/biobanksStore.js
- apps/directory/src/stores/filtersStore.js
fixes: #3324
When loading the initial page of the directory app, the filters would be available for use. If a filter was applied while the home page was still loading, the directory app would display all the biobanks and not the results matching the selected filter. Note: to test the initial issue you need to simulate a slower internet connection.
The issue is fixed by timestamping the requests. This is used to ensure that only the most recent request updates the page, preventing race conditions where older requests (e.g., loading the initial page) might overwrite newer ones (applying filters).
In addition, the functions getBiobankCards() and updateBiobankCards() have been refactored.
> fix: race condition in directory app

- apps/molgenis-components/src/components/forms/ArrayInput.vue
fixes an issue in which array inputs (for e.g. strings/numbers) would not show if there wasn't an initial input
how to test: 
- Go to the pet store
- In the schema editor add a string_array column to one of the tables and save
- Got the the table and add a column
- See that nothing can be input to the string_array 
todo:
> fix: empty array input

- apps/nuxt3-ssr/components/header/Catalogue.vue
- e2e/tests/catalogue/about-link-visibility.spec.ts
Only show link if about page existest and info in page is describes catalogue
Closes #3555
how to test:
- tested via e2e test in pr
> fix: hide link to non existent about route

- apps/directory/package.json
- apps/yarn.lock
how to test:
- Go the directory app on Firefox (other browsers should not have this issue)
- Open dev-console
- There is a warning about    `downloadable font: Glyph bbox was incorrect`
On this pr the warning should no longer show.
> chore: update FA so it now longer throws warnings in FF

- apps/nuxt3-ssr/components/content/ContentBlockIntro.vue
- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/cohorts/index.vue
- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/datasources/index.vue
Closes #3551
how to test:
- Check that 'contactRecipientsQuery' has been set for this server and schema; click the contact btn, a message should be send.
- optional , save the value from 'contactRecipientsQuery' to put back later
- remove the 'contactRecipientsQuery'  setting for this server and schema; click the contact btn, a adress to send an email to should be shown.
- Add / putback the 'contactRecipientsQuery' values ( make sure it is a valid value)  for this server and schema; click the contact btn, a message should be send.
-
todo:
> feat: only use email service if message selector is configured

- apps/directory/src/stores/biobanksStore.js
fixes: #3622
how to test:
1) Filter strongly resulting in zero results. 
2) Notice that now "No biobanks were found" is shown
todo:
> fix: dont crash on empty result set

- apps/cranio-public/src/views/view-documents.vue
- apps/molgenis-viz/src/components/display/FileList.vue
- apps/molgenis-viz/tsconfig.json
In the molgenis-viz library, the component `FileList` is used to display files listed in any table. The one limitation is that the displayed file name is dependent on the name of the file that is uploaded. It would be nice to give users the option to change the name of the file without having to re-upload the file.
how to test:
- And open the demo documents page: `/demo/cranio-public/#/documents`
- Sign in and navigate to the files table: `/demo/tables/#/Files`
- Create a blank text file or import and random file into the table. Give the record a name that is different than the file name
- Navigate back to the documents (`demo/cranio-public/#/documents`) to view the new file(s)
> Add support for file names

- backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/BiobankDirectoryLoader.java
- Currently the anonymous viewer role was set both for staging areas as well as the Directory schema when using the templates. In this PR, this default setting for the staging areas template has been removed.
how to test:
- Goto https://preview-emx2-pr-3668.dev.molgenis.org/
- Create a schema using the BIOBANK_DIRECTORY template => check that it's available in the list with schema when not logging in.
- Create a schema using the BIOBANK_DIRECTORY_STAGING template => check that it's not visible when not logged in.
todo:
> chore(directory): staging areas by default private

- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
- this results in consistent counts between the landing page and list view
how to test:
- check count for variable on landing page ( overall and sub catalogue)
- compare counts from landing page with counts from list view ( without any user filters ), these should now be the same
> fix: only include variables that that part of a model

- apps/molgenis-components/src/components/layout/Molgenis.vue
- make sure the molgenis footer is always shown under custom footers.
how to test:
- see components styleguide example of Molgenis.vue
todo:
> fix: always show molgenis footer

- docker-compose.yml
clear postgres test/healtcheck warning message while running docker compose
#3685
- Pass the user `POSTGRES_USER` to pg_ready instead of the database `molgenis`
how to test:
- run the docker compose: `docker compose up -d`
- You should **not** get the messages like: _FATAL: role "root" does not exists_
- `docker ps` to check the health status of postgres
todo:
> Chore: clear postgres test warning message

- apps/molgenis-components/src/client/IQueryMetaData.ts
- apps/molgenis-components/src/client/client.ts
- apps/molgenis-components/src/client/queryBuilder.ts
- apps/molgenis-components/src/components/forms/InputRefList.vue
- docs/molgenis/use_schema.md
partial solution to #3652 (probably need to combine with other PR to fix completely => I suppose limits on ref_array and ref_back would help a lot)
- added expandLevel to functions where it might be used
- to reduce performance issues set default expandLevel = 1 (was 2!!!!)
- refactor expandLevel to be in properties
- include all key fields in level 0 so labels can be based on key fields (e.g. a hidden computed field)
how to test:
- should create much smaller graphql queries everywhere, in particular in refInput/refBack lookups
todo:
> fix(client): reduce default expandLevel to 1 to prevend unnecessary huge queries

- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTable.java
- server side computed and validation expressions did not have the key (and readonly) columns data to use. It's added now.
how to test:
- have computed /validation expression use key or readonly fields.
todo:
> fix: add keys to server side computed expression

- apps/directory/src/functions/applyFiltersToQuery.js
fixes: #3682
When initially applying a "diagnosis available" filter, the directory app would retrieve all the existing biobanks. The query of the ontology filter has been fixed, so that the application retrieves only the biobanks matching the applied filter.
> fix: query for ontology filter in directory app

- apps/molgenis-viz/src/components/layouts/Page.vue
In the molgenis-viz library, the page component generates a `<main>` element. This was done as it did not exist in the general molgenis components library. In PR #3683, the main element was added. A html page should only have one main element. This PR removes the main element that is created by the page component.
how to test:
- View any app using the pet store schema: `/pet store/cranio-public/`, `/pet store/gportal/` etc.
- Right click and go to "Inspect the element". In the html inspector, you will have to expand the body > div#app > div > div > div. If you expand the last div, you will see the main element. Expand the main element and you will see another div rather than a main element.
- Alternatively, you can run this js …
> fix: dropped main element

- apps/directory/src/functions/viewmodelMapper.js
fixes: #3687
- The network overview link on the side cards prompts you to the network report instead of getting stuck on a loading spinner and throwing errors on the console. 
how to test:
- Click on a biobank
- Click on the network overview link
- The link prompts you to the network report
> fix: network report in directory app

- apps/directory/src/stores/biobanksStore.js
fixes: #3697
- Adjusted the waitingForResponse ref in the biobank store.
how to test:
- Select a filter in the directory app
- Copy the url with the filter parameter in a new tab
- Check that the directory app displays the biobanks matching the filter without displaying "Loading state" and "No biobanks found" messages upfront.
> fix: state messages in directory app

- apps/nuxt3-ssr/composables/useHeaderData.ts
- e2e/tests/catalogue/header-items.spec.ts
Closes #3630
- if not subcatalogue is selected still to the query, just skip the models part
how to test:
todo:
> fix: 3630 fix header query builder

- apps/nuxt3-ssr/components/content/cohort/GeneralDesign.vue
Change label from 'Age group at inclusion' to 'Population age groups' Closes #3493
how to test:
todo:
> feat: 3493 update age group field label

- .docker/initdb.sql
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlUserAwareConnectionProvider.java
- docs/molgenis/run_java.md
- helm-chart/templates/postgres-config.yml
- replace the manual jit=off by a per connection jit=off so we don't have added complexity for sysadmins
how to test:
- see if there are regressions for #3652 
- see if there are regressions for #3476
todo:
> chore: set jit=off per request instead of global settings to prevent breaking servers

- backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/TaskService.java
- backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/TaskServiceInDatabase.java
- backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/TaskServiceInMemory.java
- backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/TaskServiceScheduler.java
- backend/molgenis-emx2-tasks/src/test/java/org/molgenis/emx2/tasks/TestTaskServiceScheduler.java
closes #3372 
- resubmit cron scripts on restart
how to test:
- submit a script with cron that runs reguarly
- restart your server
- see that the script is re-scheduled execute on cron time
todo:
> fix: task services load on startup, closes #3372

- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/datasources/index.vue
- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/networks/index.vue
- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
- e2e/tests/catalogue/reset-page-on-filter-change.spec.ts
Closes #3718
- instead of keeping local state in components and page store state via query-param, and computed values to use in page and query
how to test:
todo:
> fix: 3718 make page and active tab computed

- tools/pyclient/dev/demodata/Pet.csv
- tools/pyclient/dev/dev.py
- tools/pyclient/src/molgenis_emx2_pyclient/client.py
- changed the way `pandas` handles 'na' values when creating a DataFrame from either a csv or list/dict data
- the values 'NA', 'na', 'Na' are now processed as they are
- actual _not available_ values are stored as empty strings
- float and int values are not affected
- additionally, the handling of errors in request responses is improved by including more checks in the `_validate_graphql_response` method
how to test:
- the dev script now includes an extra pet that is saved (and deleted) in a schema in the `save_schema` tests, named 'NA' with status `numpy.nan`. You can verify that the name is stored as 'NA', and the status is left empty 
todo:
> fix: proper handling of 'na' values

- apps/molgenis-components/public/theme.css
- backend/molgenis-emx2-webapi/src/main/resources/theme/bootstrap46/_breadcrumb.scss
There is always a white space between breadcrumbs and the main content (router-view)
This PR removes the bottom margin so that the main content sits directly below the breadcrumbs.
todo:
> fix: removed bottom margin in breadcrumbs

- apps/molgenis-viz/src/App.vue
- apps/molgenis-viz/src/components/layouts/PageFooter.vue
- apps/molgenis-viz/src/styles/resets.scss
In PR #3683, the primary router view was changed to a `<main>` element and a primary `<footer>` element was added. This was important for other reasons listed in the PR. As a result, a few changes to molgenis-viz library is needed. These are -
- Update `resets.scss`: need to be make sure the css selector points to the main element
- Remove footer element generated by the `<PageFooter>` component.
how to test:
- navigate to the preview.
- in the pet store schema, navigate to any of the dashboard apps. (e.g., `pet store/gportal`, `pet store/cranio-public`, etc.)
- There should be: 1) no more left and right padding, 2) the custom footer should be displayed instead of the default molgenis one
todo:
> fix: updated css resets; changed footer element

- apps/nuxt3-ssr/components/layouts/SearchPage.vue
Closes #3592
- remove max width 
how to test:
todo:
> fix: 3592 Catalogue List page layout gets shifted on macbook screen

- apps/directory/src/stores/biobanksStore.js
- apps/directory/vite.config.js
- fixed the directory app breaking when no biobanks where found
how to test:
- go to the directory-demo
- select Biobanks Services filter
- select the first option
- On master this break, on the preview it no longer does.
> fix: don't break when no biobanks are found

- apps/directory/src/stores/biobanksStore.js
fixes: #3782
- filtering certain filters fail if there are no results
how to test:
- Filter on directory demo set on "Australia" 
- We will now not have a error show.
todo:
> fix: quickfix filter undefined error

- apps/molgenis-components/src/components/layout/Molgenis.vue
- Removed the extra prefixed `v` for the version URL going to github (as version already contains the `v` this turned into https://github.com/molgenis/molgenis-emx2/releases/tag/vv10.73.0 which should have been https://github.com/molgenis/molgenis-emx2/releases/tag/v10.73.0)
how to test:
- Check if Github tag URL contains exactly 1 `v` in the version
todo:
> fix: footer version URL

- backend/molgenis-emx2-fairdatapoint/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPointCatalog.java
Fixed triples being assigned to subject `/api/fdp` in `/api/fdp/catalog/<fair_database_name>/<catalogId>` instead of the individual catalogs. In some cases it’s also very clear that these referred to columns belonging to the catalog table. 
References:
* [DCAT-summary-all-attributes](https://www.w3.org/TR/vocab-dcat-2/images/DCAT-summary-all-attributes.png)
* https://specs.fairdatapoint.org/images/FDPmetadatadiagram.png
**The triples that were moved from `/api/fdp` to the individual catalog (using the `catalogId01` from the example data)**
```
dcterms:license <https://www.gnu.org/licenses/lgpl-3.0.rdf>;
dcterms:conformsTo <http://localhost:8080/api/fdp/catalog/profile>;
dcat:themeTaxonomy <http://purl.obolibrary.org/obo/NCIT_C71899>;
dcterms:issued "2024-05-28T13:49:57"^^xsd:dateTime; …
```
> fix: triples having the FDP as subject instead of the catalog

- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/Migrations.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQueryBuilderHelpers.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlSchemaMetadataExecutor.java
- backend/molgenis-emx2-sql/src/main/resources/org/molgenis/emx2/sql/migration19.sql
- backend/molgenis-emx2-sql/src/test/java/org/molgenis/emx2/sql/SqlQueryBuilderHelpersTest.java
- backend/molgenis-emx2-sql/src/test/java/org/molgenis/emx2/sql/TestOrderByWithCollation.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/ColumnType.java
- Add new 'numeric' collation to molgenis schema, via migration 19 
-  Use numeric collation on orderby, this ensures 'var_2' comes before 'var_13'
how to test:
- Create a column ( add rows unsorted), containing string items that are a combination of alphabetical chars and numbers ( for example var_13, var_3 ), fetch this field and sort by the col containing the described string; 'var_3' should now come before 'var_13'
todo:
> feat: Add custom numeric collation

- data/biobank-directory/ontologies/MaterialTypes.csv
- The content of the "code" column in material types was not correct (probably wrongly copy/pasted). In this PR the content is moved one row down and now the codes belong to the corresponding type again.
how to test:
- Goto the MaterialTypes table in the DirectoryOntologies schema and check that f.e. PATHOGEN has PATHOGEN code and not RNA code (as is https://directory-emx2-acc.molgenis.net/DirectoryOntologies/tables/#/MaterialTypes).
todo:
> chore(directory): adjust material type codes

- backend/molgenis-emx2-fairdatapoint/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPoint.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/FAIRDataPointApi.java
- backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
**Sidenote:** Not that familiar with sparkjava yet, so if there's something obvious I overlooked, do let me know.
1. Fixed a bug where `/api/fdp` didn’t work if metadata was missing and being accessed by non-MANAGER. New behaviour simply returns the default String (and has a try-catch to set the metadata that fails until a MANAGER tried accessing it at least once).
2. Fixed a bug where `/api/fdp/` returned the output instead of `/api/fdp`  (the latter one should be the actual URL according to the [MOLGENIS documentation](http://localhost:8080/apps/docs/#/molgenis/dev_fairdatapoint?id=api-structure-and-traversal)). Additionally, **the non-slash version is used as IRI within the triples to indicate the FAIR data point**.
* OLD behaviour:
* wget …
> fix: FDP API various fixes

- apps/molgenis-viz/lib/main.js
- apps/molgenis-viz/src/components/viz/BarChartEmx.vue
- apps/molgenis-viz/src/components/viz/ColumnChartEmx.vue
- apps/molgenis-viz/src/components/viz/DataTableEmx.vue
- apps/molgenis-viz/src/components/viz/GeoMercatorEmx.vue
- apps/molgenis-viz/src/components/viz/GroupedColumnChartEmx.vue
- apps/molgenis-viz/src/components/viz/PieChart2Emx.vue
- apps/molgenis-viz/src/components/viz/ScatterPlotEmx.vue
- apps/molgenis-viz/src/interfaces/viz.ts
- apps/molgenis-viz/src/utils/index.ts
In a previous PR, a new set of components were introduced to establish a connection between a chart and a table in a schema. However, this limited users to a specific schema making it difficult to build visualisations where data is stored in different schemas. This PR adds the parameter `schema` to all emx visualisation components allowing developers to pull data from a known schemas. 
how to test:
Note: this PR adds the functionality to connect to schemas/tables. The PR referenced below will provide an example. A code review is needed here.
todo:
> fix: allow charts to query data in other schemas

- backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java
- backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestSumQuery.java
closes #3822
- enable group by to work on non-ref fields. Required only extension of the graphql api
- efactored graphql api so the field creation can be reused (future: merge the sample and sample_groupBy)
how to test:
- see test
todo:
> feat: enable group by on non-ref fields. closes #3822

- data/_demodata/applications/gdi/Individuals.csv
- Changed the ages of the gdi individuals demo data to the proper type
how to test:
- Load the gdi demo data and see no errors
> fix: changed gdi demo data iso8601 durations to proper type

- backend/molgenis-emx2-datamodels/src/test/java/org/molgenis/emx2/datamodels/TestLoaders.java
- data/_models/shared/Distribution.csv
- data/_profiles/test-only/DCAT-basic.yaml
- A profile with `DCAT` but without `DCAT files add-on` would fail with an error:
```
Transaction failed: Add column 'Distribution.files' failed: 'refTable' required for columns of type REF, REF_ARRAY, REFBACK (tried to find: dcat_test:Files): Add column 'Distribution.files' failed: 'refTable' required for columns of type REF, REF_ARRAY, REFBACK (tried to find: dcat_test:Files)
```
This PR makes 2 columns belong to `DCAT files add-on` instead of `DCAT`:
- `files` (as there are literally no files without the add-on and caused the error)
- `DistributionType` (as without the files add-on there can only be a single type hence the column is obsolete)
how to test:
- `test16DCATBasic` should fail pre-changes and work post-changes.
> Fix: dcat profile (without files add-on) fails

- apps/molgenis-components/src/components/forms/ArrayInput.vue
- apps/molgenis-components/src/components/forms/FormInput.vue
- FormInput now uses InputEmail for email inputs (#3823)
how to test:
- Go to the pet store
- Go to the pet table
- Enter a new row
- Check that the email input field validates the entered adres
todo:
> fix: use InputEmail instead of InputString for email

- apps/directory/src/stores/filtersStore.ts
- backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlTableFieldFactory.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlQuery.java
- backend/molgenis-emx2-sql/src/test/java/org/molgenis/emx2/sql/TestFullTextSearch.java
closes #3850 
- when using search as filter (not as part of seperate search parameter) it returned (term1 OR term2). Desire is to have it term1 AND term2
- TEXT_SEARCH operator should be used in graphql api until TRIGRAM_SEARCH is better understood
how to test:
- test search in variables user interface which uses this feature
- see unit test
todo:
> fix: search should work as (term1 and term2)

- apps/directory/src/stores/settingsStore.js
- changed negotiator url from negotiator-dev to negotiator.acc as the dev server does not work properly.
how to test:
- GoTo the directory-demo schema, select one or more collections, push the request button and check that (after login) you get to the negotiator
todo:
> chore(directory): change default negotiator URL

- backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RDFService.java
Using RDF API where `PERIOD` datatype was used caused an error:
```
Transaction failed: RDF export failed due to an exception: ColumnType not mapped: PERIOD
```
Literal should now return something like:
```
"P89Y"^^xsd:duration
```
- Calling RDF API on f.e. demodata filled FAIR_DATA_HUB should not throw an error anymore but contain `xsd:duration` literals
> fix: PERIOD datatype not working in the RDF API

- backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/filter/Filter.java
- backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/filter/FilterParser.java
- backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/filter/FilterParserVP.java
- backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/filter/VariantFilterParser.java
- backend/molgenis-emx2-beacon-v2/src/test/java/org/molgenis/emx2/beaconv2/entrytypes/BeaconIndividualsTests.java
- When filters have an array with multiple arguments as values, OR queries wil be created by default.
how to test:
- See added unit test 
todo:
> feat(beacon): OR filtering for filters with multiple arguments as value.

- apps/directory/src/components/report-components/FactsTable.vue
closes #3970
I removed from the computation the rows where asterisk is present
how to test:
load Ontologies.zip (that contain the ontologies from github emx2+*
load Fact.zip that contains the fact table with (3 and 4) asterisks
[Fact.zip](https://github.com/user-attachments/files/16111711/Fact.zip)
[Ontologies.zip](https://github.com/user-attachments/files/16111712/Ontologies.zip)
when all Split by are enabled:
select * on all dimensions. The result is 620 samples for biobank 76823
Now uncheck "Split by" in all columns.
Leaves "all" for all the dimensions. The result should be 620 and no asterisks should be shown. In the incorrect …
> fix(directory): asterisks in fact table cause wrong number of sampl… closes #3970

- apps/tailwind-components/app.vue
- chosen theme state persists after reload, making the workflow of adding new components less of a hassle
how to test:
set the theme in the menu, reload the page.
The same theme should still be active
> feat(tailwind-components): persist theme state

- apps/directory/src/components/Footer.vue
- Replaced the privacy policy link in the footer
how to test:
- Goto the preview and click on the privacy policy and see that it resolves to https://www.bbmri-eric.eu/privacy-notice/
todo:
> fix(directory): replace privacy policy link in footer

- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/BeaconApi.java
- Added a mapping for the beacon root api without a trailing /
how to test:
- Create a schema with a beacon data template
- Go to "severpath/schema_name/api/beacon" and see it working
> fix(beacon): added mapping for root path without "/"

- apps/.gitignore
- apps/central/vite.config.js
- apps/cranio-provider/vite.config.js
- apps/cranio-public/vite.config.js
- apps/dev-proxy.config.js
- apps/ern-genturis/vite.config.js
- apps/ern-ithaca/vite.config.js
- apps/ern-reconnet/vite.config.js
- apps/ern-skin/vite.config.js
- apps/imdhub-public/vite.config.js
- apps/molgenis-viz/vite.config.js
The purpose of this PR is to expand the current dev proxy to eliminate the number of per-app configurations. This includes:
- Revised graphql and file endpoints
- Added support for cross schema querying when developing UIs
- Added proxy for file endpoint
To use, import it into your `vite.config.js` file. In your request, you can write your URLs like so:
1. `../api/graphql`: query within the current schema (`/graphql` should also work)
2. `/<schema>/api/graphql`: query a table in another schema
how to test:
todo:
Considerations:
I would love to turn this into a function rather than using module.exports. This would eliminate the need to configure the dev-proxy server for every PR and allow me to avoid using `.env` files to change the host/schema. 
```js
// …
```
> feat: expanded dev proxy

- apps/molgenis-components/src/components/forms/formUtils/formUtils.ts
fixes: #3752
- when creating a new record, expressions did not have access to "mg_tableclass" property
- Now if it does not exists it will be recreated (for the expressions).
How to test:
- have in a string field the validation expression:`mg_tableclass`
- update the string field, it will return the current `mg_tableclass` value in the error field.
- make sure mg_tableclass is a valid value on a new record and on a preexisting record.
> feat(molgenis-components): expressions recreate mg_tableclass

- .gitignore
- e2e/README.md
- e2e/playwright.config.ts
- e2e/tests/admin!example.spec.ts
- e2e/tests/auth.setup.spec.ts
- e2e tests now don't have to login manually (which would need to be done for each test individually), but can use a shared authentication
- updated README regarding the above & some general fixes/improvements I ran into while trying to get it to work
how to test:
- In VS code, run `auth.setup.spec.ts` and then `admin!example.spec.ts`
- Check if `admin!example.spec.ts` succeeds in CI
todo:
> chore: e2e admin login + improved README

- backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/endpoints/Info.java
- backend/molgenis-emx2-beacon-v2/src/test/java/org/molgenis/emx2/beaconv2/Beaconv2_InfoTest.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/BeaconApi.java
- To always make the informational endpoint available, data is fetch directly via sql
todo:
> fix(beacon): get information endpoint data via sql query

- backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/requests/BeaconQuery.java
- backend/molgenis-emx2-beacon-v2/src/test/java/org/molgenis/emx2/beaconv2/entrytypes/BeaconGranularityTests.java
- docs/molgenis/dev_beaconv2.md
- Added the requestedGranularity parameter for get GET request to beacon api
- Added tests en docs
how to test:
- load a beacon data profile
- <schema>/api/beacon/individuals?requestedGranularity=count 
- <schema>/api/beacon/individuals?requestedGranularity=boolean 
now also works
todo:
> fix(beacon): added granularity for get requests

- apps/directory/src/components/report-components/FactsTable.vue
- data/biobank-directory/ontologies/AgeRanges.csv
- data/biobank-directory/ontologies/DiseaseTypes.csv
- data/biobank-directory/ontologies/MaterialTypes.csv
- data/biobank-directory/ontologies/SexTypes.csv
- Added asterisks (*) as codes to AgeRanges, DiseaseTypes, MaterialTypes and SexTypes biobank-directory ontology tables
how to test:
- Go to the preview and check the above mentioned tables and see the * as a record
todo:
> chore(directory): add asterisks to ontology tables

- backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/QueryEntryType.java
- backend/molgenis-emx2-beacon-v2/src/test/java/org/molgenis/emx2/beaconv2/entrytypes/BeaconCohortsTests.java
- Added a missing break statement, resulting in duplicate entries showing up when performing count request
> fix(beacon): added missing break statements when querying

- .circleci/config.yml
- apps/directory/src/components/popovers/NegotiatorSelection.vue
- apps/directory/src/stores/checkoutStore.js
This PR replaces #4094, as that one is a bit messed up after trying to solve conflicts with master.
fixes https://github.com/molgenis/molgenis-emx2/issues/4023
**What are the main changes you did:**
Added local storage for preserving the state of the negotiator
**How to test:**
- Go to the directory app
- Add a collection to the negotiator selection
- Reload the page
- The collection remains within the negotiator selection
> fix: preserving the state of the negotiator

- apps/directory/src/components/configuration/FilterEditor.vue
- apps/directory/src/components/configuration/JsonEditor.vue
- apps/directory/src/views/ConfigurationScreen.vue
- Changed the hotkey for formatting to ctrl-alt-f because ctrl-f opens the search box of the browser for non-mac users.
- closes #4089 
how to test:
- go to the directory app
- login
- press settings
- go to the json editor tab
- add some whitespace
- press ctrl + alt + f
- see that it formats
> chore(directory): change formatting hotkey

- apps/molgenis-components/src/components/utils.ts
fixes: #4130
- When the rows are still being loaded the computed expressions handler crashes 
how to test:
- create a new petstore
- successfully try to add a new record in "Pet"
> fix(molgenis-components): handle computed with rows not yet loaded

- docs/molgenis/use_usingpyclient.md
- tools/pyclient/dev/dev.py
- tools/pyclient/src/molgenis_emx2_pyclient/client.py
- tools/pyclient/src/molgenis_emx2_pyclient/utils.py
- I changed the way the URLs are handled in object initialization. I removed the `parse_url` utility function. Instead I added the `_validate_url` method that checks whether the URL as it is passed is valid for Pyclient usage. This enables the usage of `localhost` as an URL. Additionally, it makes the client very strict in enforcing prepending the URL with `https://` by the user for other URLs.
- Besides this change, I moved the token header to the requests.Session header in the initialization and removed it elsewhere from methods
how to test:
- create a script that creates a Pyclient object for a URL both with and without `https://`
todo:
> fix(pyclient): use 'localhost' as server for Pyclient

- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
Changes force link from `/Aggregates/aggregates/` to `/Aggregates/aggregates/#/`
> fix: use correct force aggregate button link

- apps/molgenis-components/src/components/layout/MolgenisMenu.vue
- apps/settings/src/components/MenuDesign.vue
Fixes: [#3980](https://github.com/molgenis/molgenis-emx2/issues/3980)
- Added a !anonymous option for menu visibility
how to test:
- Log in as admin.
- Change the visibility of a menu item to !anonymous in the settings > menu.
- Log out and see that the menu item is not visible for anonymous users
> feat(user): extra setting option for menu visibility for anonymous user

- apps/molgenis-components/src/components/tables/RoutedTableExplorer.vue
- apps/tasks/src/components/ListJobs.vue
Fixes https://github.com/molgenis/GCC/issues/571
- Made sorting in the RoutedTableExplorer configurable
- Added default sorting to ListJobs.vue
how to test:
- Start a few jobs (e.g. by loading some data profile)
- Go to Jobs&Scripts > Jobs
- See the default ordering of the jobs
> fix(jobs): default sorting of jobs in ui

- backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlDatabaseFieldFactory.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSessionManager.java
Fixes [#3902](https://github.com/molgenis/molgenis-emx2/issues/3902)
- The MolgenisSessionManagerDatabaseListener was not added to Session based on tokens I added this
- Therefore the python client - when used via a token - did not update the meta data when changes were made
how to test:
- Go to the webinterface
- Add metadata using the py client using token based authorization
- See the meta data update without needing to log in again
todo:
> fix: added session db listener to sessions based on tokens

- apps/tasks/src/App.vue
- backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/endpoints/Map.java
- backend/molgenis-emx2-beacon-v2/src/main/java/org/molgenis/emx2/beaconv2/requests/BeaconRequestBody.java
- backend/molgenis-emx2-fairdatapoint/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPoint.java
- backend/molgenis-emx2-fairdatapoint/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPointCatalog.java
- backend/molgenis-emx2-fairdatapoint/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPointDataset.java
- backend/molgenis-emx2-fairdatapoint/src/main/java/org/molgenis/emx2/fairdatapoint/FAIRDataPointDistribution.java
- backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RDFService.java
- backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/ScriptTask.java
- backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/Task.java
- backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/TaskService.java
- backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/TaskServiceInDatabase.java
- backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/TaskServiceInMemory.java
- backend/molgenis-emx2-tasks/src/test/java/org/molgenis/emx2/tasks/TestScriptTask.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/TaskApi.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/utils/URIUtils.java
Fixes [#4177](https://github.com/molgenis/molgenis-emx2/issues/4177)
To provided more context on failing jobs a link to the job is provided in the failure mail
- Added the server url to ScriptTasks
- Added a link to to job in the failure email template
The title of the mail is:
`Molgenis script <script name> failed on <server name>`
The content is:
```
Molgenis script <script name> failed with error:
<error>
<link to the job>
```
Preview link:
https://preview-emx2-pr-4179.dev.molgenis.org/_SYSTEM_/tasks/#/jobs?id=9a5c51c9-d5e3-4d53-9bb2-995ae35bbc12
how to test:
- Submit a job with an error and a failureAddress
- Receive an email with a link to the job
> feat(tasks): added link to job in failure mail

- .circleci/config.yml
- updated the playwright version from 1.46.0 to 1.47.0.
how to test:
- e2e tests should work again
todo:
> chore: update playwright version

- apps/directory/src/stores/checkoutStore.js
- Negotiator V3 Api response includes a redirectUrl instead of redirect_uri which was in the preview API version. 
old:
new:
Hopefully this solves the issue that sending a request fails with negotiator V3 API (redirect does not work).
how to test:
- Check the code => unfortunately sending requests to the negotiator doesn't work in a preview.
todo:
> fix(directory): change redirect_uri to redirectUrl

- apps/tailwind-components/components/filter/Search.vue
- Created a unique identifier for the `FilterSearch` component
- Added a visually hidden label that describes the input and linked the elements using a unique identifier
how to test:
- Install the [WAVE Browser Extension](https://wave.webaim.org/extension/)
- Open the preview and navigate to the tableEmx2 story: https://preview-emx2-pr-4192.dev.molgenis.org/apps/tailwind-components/#/FilterSearch.story
- Open the WAVE Browser Extension. No errors should appear on the FilterSearch component
- Alternatively, click inspect element on the filter search component. In the HTML structure, note the unique ID and the label for the input
todo:
> fix: added missing label and identifier in `FilterSearch` component

- docs/molgenis/dev_quickstart.md
* docs command was missing `&&` for clearing gradle cache.
* clearing gradle cache was insufficient if changing something in an app that other apps build on, so added section about clearing cache of all apps (as clearing gradle cache does not work for this).
how to test:
1. Run `./gradlew run`
2. Make a change, f.e. `molgenis-emx2/apps/molgenis-components/src/components/forms/InputString.vue` the line `@input="updateModelValue($event.target.value)"` to `@input="updateModelValue('test')"`
3. Run `./gradlew run`
http://localhost:8080/apps/molgenis-components/#/component/InputString: new behaviour
http://localhost:8080/apps/central/#/ -> login: old behaviour
4. Run `rm -rf ./apps/*/dist/`
5. Run `./gradlew run` …
> docs: fixed docs & updated with apps cache reset (when running through gradle)

- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTypeUtils.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/utils/TypeUtils.java
Fixes [#4156](https://github.com/molgenis/molgenis-emx2/issues/4156)
- Added the mg_tableclass to the variable map/graph before validation.
- It is available on the row but is ignored because it's not in the column list
- Added extra handling for a computed value when the column is an ontology
how to test:
- Use the mg_tableclass variable for an expression on a column.
todo:
> fix: added 'mg_tableclass' for expressions in de backend

- apps/molgenis-components/src/components/account/Interfaces.ts
- apps/molgenis-components/src/components/account/TokenManager.vue
- apps/molgenis-components/src/components/tables/TableExplorer.vue
- apps/molgenis-components/src/components/utils.ts
- fix: #3700 (show tokens and allow deletion
- fix: no longer allow user to create tokens with already existing names. Swapped the create button and the input due to error message layout. Didn't want to spend a lot of time on the layout so went for the easy fix (keeping the upcoming tailwind migration in mind).
how to test:
- see issue, tokens should now show and be deletable (refresh not needed).
- enter a token name that already exists and see that the button is disabled and an errormessage is displayed.
> fix: show application tokens and allow deletion for users

- apps/tailwind-components/components/input/TextArea.vue
- apps/tailwind-components/pages/input/TextArea.story.vue
- e2e/package.json
- e2e/tests/tailwind-components/input/textarea.spec.ts
- Added additional props for managing state input: valid, error, disabled, placeholder
- Updated InputTextArea story by adding additional optional to change the demo input
- Minor HTML adjustments for improving semantics and accessibility
- Added e2e test and command for running tests on tailwind components
how to test:
- Navigate to the InputTextArea story: http://preview-emx2-pr-4218.dev.molgenis.org/apps/tailwind-components/#/input/TextArea.story
- Tick the different boxes to change the state of the input. Note the style changes
- Test the placeholder input
> fix: expanded InputTextArea component

- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
- apps/nuxt3-ssr/tests/network-of-networks.spec.ts
to test:
- go to variables screen and see that filter name is named 'sources' (matching the 'source' in mappings table)
> fix(catalogue): in variables screen rename filter 'resources' to 'sources'

- backend/molgenis-emx2-run/src/test/java/org/molgenis/emx2/AToolToGenerateTypeScriptTypesTest.java
- backend/molgenis-emx2-sql/build.gradle
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/AToolToCleanDatabase.java
- backend/molgenis-emx2-typescript/build.gradle
- backend/molgenis-emx2-typescript/src/main/java/org/molgenis/emx2/typescript/AToolToGenerateTypeScriptTypes.java
- backend/molgenis-emx2-typescript/src/test/java/org/molgenis/emx2/typescript/AToolToGenerateTypeScriptTypesTest.java
- backend/molgenis-emx2-webapi/build.gradle
- build.gradle
- docs/molgenis/dev_basics.md
- docs/molgenis/dev_quickstart.md
- docs/molgenis/run_updates.md
- added 'dev' tasks
-  moved dev, cleandb and generateTypes to modules to make them start faster again bypassing javascript build
how to test:
- see docs changes
> build: add 'gradle dev' task to run in headless mode without building javascript

- docs/molgenis/use_schema.md
Added docs describing the following scenarios:
1. Validating that a field must be filled
https://github.com/user-attachments/assets/967ed813-acb9-4db9-9e1f-6ef13707a3f3
2. Validating that a field must be empty
https://github.com/user-attachments/assets/3f3637e9-374e-4e54-a7ae-0fdddfbabd9d
how to test:
- Create schema/table where `c2` has the validation as mentioned in the docs referring to `c1` (see also videos where the error message also shows the used expression).
todo:
> docs: Added expressions for validating if a field is empty or not

- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/[resourceType]/[resource]/index.vue
Before:
- FAIL https://emx2.dev.molgenis.org/catalogue-demo/ssr-catalogue/testNetwork1/networks/testNetwork1 
After:
- SUCCESS https://preview-emx2-pr-4347.dev.molgenis.org/catalogue-demo/ssr-catalogue/testNetwork1/networks/testNetwork1
> fix(catalogue): resource details page not rendering when resource.peopleInvolved is empty

- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/[resourceType]/[resource]/index.vue
To reproduce:
Ga naar https://data-catalogue-acc.molgeniscloud.org/catalogue/ssr-catalogue/STAGE/cohorts
click on ALSPAC in de lijst
Before: endless loop because of reactivity
After: should not result in endless loop because array is copied first
> fix(catalogue): sort of people involved has side effects

- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTypeUtils.java
- backend/molgenis-emx2-sql/src/test/java/org/molgenis/emx2/sql/TestSqlTypeUtils.java
- Fixed the bug
- Added test:
- Pre-fix keySet: `[STRING array, sTRINGArray]`
- Post-fix keySet: `[sTRINGArray]`
how to test:
- Ensure all tests succeed
Sidenote: Weird camelCasing. Would expect `stringArray` instead. Perhaps worth fixing as well, though not sure if this would break things. Either way, out-of-scope for this PR.
todo:
> fix: Arrays failed to validate using their `validationRegexp`

- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/utils/TypeUtils.java
Closes #4398
- Added FILE to the getTypedValue switch , have it resolve as string as file name is string 
how to test:
todo:
> fix: 4398 save row with required file field

- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
closes https://github.com/molgenis/molgenis-emx2/issues/4422
fixes for cohortOnly
todo:
Below the expected based on production
And what you see now
> fix: cohortOnly switch

- apps/tailwind-components/components/BreadCrumbs.vue
- apps/tailwind-components/pages/BreadCrumbs.story.vue
- Refactored breadcrumbs component to ensure good semantic HTML practices. This includes: using `nav` and `ol` elements, removing templates, adding aria properties where necessary, removing duplicate code (i.e., multiple svg calls, etc.) 
- Simplified `v-if` statements
- `current` page property is now rendered in a separate `li` element
how to test:
- Navigate to the breadcrumbs story: https://preview-emx2-pr-4407.dev.molgenis.org/apps/tailwind-components/#/BreadCrumbs.story
- View examples and resize the browser to view the alternate layouts
todo:
> fix(tw): refactor breadcrumbs component

- docs/molgenis/use_scripts_jobs.md
Update documentation for jobs to clarify that disabled means that scheduling the job in cron is disabled.
closes #4388
> Update documentation for jobs

- apps/molgenis-components/src/components/forms/RowEdit.vue
fixes: #4027
Have auto-id fields respect the pages it should not be displayed.
Review comments: Notice that the 'showColumn' was returning a pkey for auto-id and the function needed to return a boolean.
how to test:
- Add an auto-id field to Pet in pet store.
- Make sure only one auto-id field is visible in all chapters.
> fix(molgenis-components): multiple auto-id fields in chapters

- apps/reports/src/components/ViewEditReport.vue
- backend/molgenis-emx2-datamodels/src/main/java/org/molgenis/emx2/datamodels/PetStoreLoader.java
- backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlSchemaFieldFactory.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/JsonApi.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisWebservice.java
- backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
- docs/molgenis/use_reports.md
Fixes: [#4360](https://github.com/molgenis/molgenis-emx2/issues/4360)
- Added a JSON api mapping for reports
- Added a json download button to the reports view
how to test:
- Go to the pet store schema
- Click on reports, and select the first one
- Click on the download as json button
- See the json
todo:
> feat(emx2): JSON api for reports

- backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/graphql/GraphqlDatabaseFieldFactory.java
- removed 2 functions from the backend that where not being used anywhere
how to test:
todo:
> chore: remove usused functions

- backend/molgenis-emx2-graphql/src/test/java/org/molgenis/emx2/graphql/TestGraphqlAdminFields.java
- Included formatting automatically done when building.
> chore: auto-formatting

- docs/molgenis/use_usingpyclient.md
- added surrounding quotes around the jobId parameter in the Python EMX2 client documentation
- check the docs
- might start a job on a server with the job=${jobId} without quotes => get `Syntax Error Invalid decimal literal` Then start one including the quotes and see that these are really necessary!
> chore(docs): add quotes around jobId parameter

- docs/molgenis/dev_apps.md
- docs/molgenis/dev_quickstart.md
> chore(docs): updated docs to use `yarn dev` instead of `yarn serve`

- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/StaticFileMapper.java
Currently running EMX2 on windows return a white webpage because of incorrect mime type of js files.
- Hardcode the mime type of js files because you can't assume it is correctly set in the windows registry.
- Run the application on windows
- go to localhost:8080
- the application should load 
- it should make no difference on unix machines
> fix: use correct mime-type when windows doesn't recognize it

- backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/ScriptTask.java
- backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/TaskService.java
- backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/TaskServiceInDatabase.java
- backend/molgenis-emx2-tasks/src/main/java/org/molgenis/emx2/tasks/TaskServiceInMemory.java
- backend/molgenis-emx2-tasks/src/test/java/org/molgenis/emx2/tasks/TestTaskServiceDatabaseBacked.java
- backend/molgenis-emx2-tasks/src/test/java/org/molgenis/emx2/tasks/TestTaskServiceScheduler.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisWebservice.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/TaskApi.java
Fixes #4542 
- Fixed sending failure mails when failing jobs are scheduled
- By storing the host url in WebService and passing it the TaskService
- Can only be tested on prod/acc server
-
> fix(tasks): also send failure mails when failing jobs are scheduled

- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java
Change the OIDC variable in the database class, when the isOidcEnabled setting is changed.
> fix(oidc): database class variable is not updated when oidc setting is changed

- apps/molgenis-components/src/components/forms/InputBoolean.vue
fixes: #4580
- a boolean input had a broken state. It will now start unselected until a user choses a state for it.
- have a boolean field, see that the boolean is unselected when creating a new record.
> fix: add boolean null state

- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/Migrations.java
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java
- Renamed constants to have a semantic name, which though longer, would make it easier to find.
- If it compiles it is otherwise equal to the current main branch, so no additional tests are needed
None of these tasks were relevant:
> chore: use semantic name for constants

- tools/directory/CHANGELOG.md
- tools/directory/pyproject.toml
- tools/directory/setup.cfg
- tools/directory/setup.py
- tools/directory/src/molgenis_emx2/directory_client/__init__.py
- tools/directory/src/molgenis_emx2/directory_client/directory.py
- tools/directory/src/molgenis_emx2/directory_client/directory_client.py
- tools/directory/src/molgenis_emx2/directory_client/model.py
- tools/directory/tests/conftest.py
- tools/directory/tests/resources/services.json
- tools/directory/tests/resources/studies.json
- tools/directory/tests/test_model.py
- tools/directory/tests/test_publisher.py
- tools/directory/tests/test_stager.py
- tools/directory/tests/test_transformer.py
- tools/directory/tests/test_validator.py
- Included the Services table in the list of tables to be published
- Also included QualityInfoServices data which is used in the check if a service can be removed
- Either run dev.py locally
- Or use the 1.2.0-dev0 version from [testpypi](https://test.pypi.org/project/molgenis-emx2-directory-client/1.2.0.dev0/)
Some output from test-runs:
=> add new service:
=> Delete a service which has a quality:
🧼 Cleaning up removed data in Directory tables
⚠️ Prevented the deletion of a row that is referenced from the quality info: services bbmri-eric:serviceID:NL_test.
=> Delete a service without any qualities:
> feat(directory): Publish Services

- apps/central/src/components/admin/ManageUsers.vue
- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java
- backend/molgenis-emx2-sql/src/test/java/org/molgenis/emx2/sql/TestUsersAndPermissions.java
- fixes #4575 
- log in as admin
- Go to the admin settings
- Confirm that the user 'user' no longer has a delete and edit button (like admin and anonymous)
> fix: don't allow deleting the user 'user'

- tools/pyclient/src/molgenis_emx2_pyclient/graphql_queries.py
In https://github.com/molgenis/molgenis-emx2/pull/4586 the attributes `schemaName` and `schemaId` were removed from the MolgenisTableType in the GraphqlSchemaFieldFactory. 
These attributes were still present in the GraphQL query for retrieving a schema's metadata.
Posting this query to the latest versions of EMX2 causes errors as these attributes cannot be found.
This PR fixes this issue and makes the query in line with the schemas built by the backend.
- grab the raw query from the method `list_schema_meta` in graphq_queries.py and paste it in [the Graphql playground on the catalogue-demo schema on the test server](https://emx2.dev.molgenis.org/catalogue-demo/graphql-playground/)
> chore(pyclient): updated GraphQL metadata query to be in line with current metadata model

- backend/molgenis-emx2-io/src/main/java/org/molgenis/emx2/io/tablestore/TableStoreForXlsxFile.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/ExcelApi.java
- Changed the excel api code so that error messages in the excel api are properly handled.
- Added a more explicit error message in the XlsTableStore when writing values to excel cells.
- Go to the preview server and try to download the catalogue schema using the xls api
- See the error message.
> fix: Excel API exception handling. 

- apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
> fix(catalogue): reused variables should be included in count of catalogue landingpage. closes #4480 

- docs/molgenis/dev_rdf.md
- Added docs to explain `custom_rdf` advanced setting
- check if docs correct?
> docs(rdf): included `custom_rdf` advanced setting

- apps/metadata-utils/src/types.ts
- apps/molgenis-components/src/client/client.ts
- apps/molgenis-components/src/components/forms/InputSelect.vue
- apps/schema/src/components/ColumnEditModal.vue
> fix(schema-editor): can Change refSchema and Select refTable in Schema Editor. closes #3581

- backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/ColumnTypeRdfMapper.java
- backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RDFService.java
- backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RdfUtils.java
- backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/RdfUtilsTest.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/GraphGenomeApi.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/RDFApi.java
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/Constants.java
- Simple code maintenance to reduce duplicate code
- Added tests
- All tests should succeed.
> fix(rdf): code quality improvements

- apps/tailwind-components/components/input/Email.vue
- apps/tailwind-components/pages/input/Email.story.vue
- apps/tailwind-components/tests/components/form/inputEmail.spec.ts
- Added input email to en tailwind components.
- Note: this uses the regex currently used in the old version of the forms. This does not yet use the more lenient version that was requested.
> feat: add input email to tw

- apps/directory/src/components/filters/OntologyFilter.vue
- apps/directory/src/stores/filtersStore.ts
fixes: [#906](https://github.com/molgenis/GCC/issues/906)
- selecting "Diagnosis available" is limited to 50 items
- having 50 selected items shows a warning box to limit your selections
- select a root "Diagnosis available" filter, notice that only the first 50 are selected and a info box is shown
> fix(directory): don't select more than 50 ontology items

- apps/ern-genturis/src/views/view-contact.vue
- apps/ern-genturis/src/views/view-documents.vue
- apps/ern-ithaca/src/views/view-documents.vue
- apps/ern-reconnet/src/styles/index.scss
- apps/ern-reconnet/src/views/documents-page.vue
- apps/ern-skin/src/views/view-documents.vue
- replace "under construction warning" in documents overview in SKIN dashboard by and actual select files statement
- solve the error in documents overview in GENTURIS dashboard by adjusting the column names.
- fix missing address on GENTURIS contact page
- Goto preview server, login and create a schema using ERN_DASHBOARD template
- goto schemaName/tables and create records in the files table
- goto schemaName/ern-genturis => click documents tile => see that the uploaded documents are shown
- goto schemaName/ern-skin => click at the bottom of the page the Documents link and see that no longer an "under construction warning" is shown, but the files that were added to the files table.
- goto schemaName/ern-genturis/#/contact and see that the UMCG address is shown (was currently missing)
- …
> fix: documents visible in SKIN and GENTURIS dashboards

- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/utils/TypeUtils.java
This is a lucky guess to fixing #4673
> fix(forms): List.isEmpty on "list" error when a ref_array is null

- apps/molgenis-components/src/components/forms/InputEmail.vue
- apps/molgenis-components/src/components/forms/InputHyperlink.vue
- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/utils/TypeUtils.java
It was not possible to use EmailArray and HyperlinkArray in forms as the EmailInput and HyperlinkInput field types lacked the property to append values.
See: https://emx2.dev.molgenis.org/apps/molgenis-components/#/component/ArrayInput
- added missing properties to EmailInput and HyperlinkInput
- add the [type test schema](https://emx2.dev.molgenis.org/type%20test/tables/#/) and see that the inputs now work and can be saved
~- [ ] updated docs in case of new feature~
~- [ ] added/updated tests~
~- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation~
> fix: enabled email array and hyperlink array types in forms

- apps/tailwind-components/assets/css/main.css
- apps/tailwind-components/assets/css/theme/molgenis.css
- apps/tailwind-components/components/Message.vue
- invalid: Changed text and border color from `red-500` to `red-700`
- success: added `green-900: #075F32` for text and border color. Used `*-900` as it is darker than 800. Contrast is now `6.86` and meets [AA threshold](https://www.w3.org/TR/WCAG22/#contrast-minimum).
- adjusted valid and invalid config in other themes
- View the styles in the Message story and in the Forms
- Run the WAVE browser extension. No more contrast errors in the message story
> fix(tw): fixed color contrast in message component 

- apps/directory/src/components/checkout-components/CollectionSelector.vue
- apps/directory/src/components/partial-views/ApplicationHeaderPartialView.vue
- fixes a crash when pressing select all collections/services when there is a biobank that has none.
- closes #4699 
- see ticket (can also test on demo set, since biobank 3 has no collections)
> fix: select all collections/services when biobank has none

- apps/cranio-provider/package.json
- apps/cranio-provider/src/utils/index.ts
- apps/cranio-provider/src/utils/parseChartTitle.ts
- apps/cranio-provider/src/views/provider-cs-all-general.vue
- apps/cranio-provider/src/views/provider-cs-center-general.vue
- apps/cranio-provider/src/views/provider-overview.vue
- apps/cranio-provider/tests/parseChartTitle.test.ts
1. Navigate to the preview and login as admin
2. Go to the demo schema: `AT1`
3. On the home page, view the value showcase component (e.g., "_n_ patients submitted")
4. In the Charts table, edit the chart titles for this component. Use the pattern "${value}" to indicate where the value should be placed in the string. E.g., `The current value is ${value}.` 
5. To confirm the sorting, view both "General overview" pages in the Craniosynostosis dashboard. Click the filter that says "Filter data by year of birth". The order should be "All patients" followed by year ranges in order.
> fix: connected value showcase to charts table

- apps/cranio-provider/src/views/provider-clp-your-center.vue
- apps/cranio-provider/src/views/provider-cs-all-general.vue
- apps/cranio-provider/src/views/provider-cs-center-general.vue
- apps/cranio-provider/src/views/provider-cs-center-surgical.vue
- Navigate to the preview and sign in as admin
- Go to [craniosynostosis all centers general overview](https://preview-emx2-pr-4733.dev.molgenis.org/AT1/cranio-provider/#/cs/all-centers-general). Select a different age group (2005-2009, etc.). The chart should redraw with different values. (**NOTE**: not all values may have data as this is a test dataset.)
- Go to the [craniosynostosis you center overview](https://preview-emx2-pr-4733.dev.molgenis.org/AT1/cranio-provider/#/cs/center-general). Like the preview page, select a different age group and note the changes in the chart. (Not all charts will render as data isn't available for every category.)
- Got the [cleft lip and palate center overivew](https://preview-emx2-pr-4733.dev.molgenis.org/AT1/cranio-provider/#/clp/center). The order …
> fix: fixed sorting and filtering issues

- apps/tailwind-components/components/input/CheckboxIcon.vue
- apps/tailwind-components/components/input/Listbox.vue
- apps/tailwind-components/components/input/Tree.vue
- apps/tailwind-components/components/input/TreeNode.vue
This PR is part of molgenis/GCC#279
> [!NOTE]
> There is still an issue with the styling of the expand group button icon. In the light theme, the text color does not change. In a future PR, this will be fixed (likely after the input style and button refactoring)
- View the InputListbox component story. Select the "disabled" state and click the listbox component. It should no longer open.
- View the InputTree story. The right border of the check should be trimmed. The horizontal line in the checkbox should be visible when one node in a group is selected.
> fix(tw): added missing classes to tree input

- apps/tailwind-components/components/Message.vue
- apps/tailwind-components/components/form/Field.vue
The purpose of this PR is to fix the broken aria references in the field component. This component controls the input and the corresponding text elements (label, description, errors, etc.). The text elements are displayed correctly, but the references are broken as text elements are dynamically shown/hidden. If an element is hidden, then it cannot be linked to the input element.
This PR is part of molgenis/GCC#279
- Go to the preview
- View the Forms story and run the WAVE extension. There should be no more broken reference serrors on the input elements
- View the Message story and run the WAVE extension. No more reference errors should be thrown.
> fix(tw): broken references in field component

- apps/tailwind-components/components/input/CheckboxGroup.vue
- apps/tailwind-components/components/input/InputGroupContainer.vue
- apps/tailwind-components/components/input/RadioGroup.vue
- apps/tailwind-components/pages/input/CheckboxGroup.story.vue
- apps/tailwind-components/pages/input/RadioGroup.story.vue
This PR adds focus and blur events to input groups. In the previous version, events are trigger at the input level (i.e., checkbox, radio) which caused validation to occur when a user tabbed between input elements. Instead, these events should be triggered when the group no longer has focus. Now, the components will trigger a focus when their is an active element within the component and blur when there is no longer an active element within the group. 
This PR is part of molgenis/GCC#279
- Go to the Forms story and select the following schema: `patient registry demo` and table `Subject`. In section 2 "Personal Information", select one of the radio checkbox group inputs (e.g., sex at birth, country of birth, etc). Clear the default value and move to another input. …
> fix(tw): added blur and focus emits to input groups

- apps/tailwind-components/components/input/File.vue
- apps/tailwind-components/pages/input/File.story.vue
- In the tw component gallery, go to the file input story.
- Click anywhere in the input component to open the file menu (new functionality)
- Select a file. Click anywhere in the component (except the file button) to reopen the file selector
- Click the file button to remove the file (file selector should not open)
I have confirmed that this component works in the following browsers.
> fix(tw): fixed file input click events

- data/_ontologies/FileFormats.csv
- go to data > _ontologies folder
- go to FileFormats.csv
- Check if md5 is added (correctly)
> fix(rd3): md5 added as file format in the ontology table

- backend/molgenis-emx2-webapi/build.gradle
- see title
- this change should in practice not change anything as according to `./gradlew dependencies` the webapi already uses 5.0.1
> chore: removed dependency already defined in parent `build.gradle`

- apps/tailwind-components/assets/css/main.css
- apps/tailwind-components/components/input/listbox/List.vue
- apps/tailwind-components/components/input/listbox/ListItem.vue
- apps/tailwind-components/components/input/listbox/Toggle.vue
- apps/tailwind-components/pages/input/Listbox.story.vue
- apps/tailwind-components/tailwind.config.js
In this PR, I replaced the listbox styles with the general input styles defined in the tailwind config. This allows the listbox styling to behave like other inputs (e.g., hover, focus, selected, etc.).
(this PR is part of molgenis/GCC#279)
1. Go to the preview and view the listbox story
2. View the component in other themes. Make new selections, focus/hover over the component, etc. Note the styling changes and compare it to the other input elements.
> fix(tw):added general input styles to the listbox component

- data/scripts/catalogue/publish/delete_resource.py
- data/scripts/catalogue/publish/publish_resources.py
- tools/staging_migrator/src/molgenis_emx2_staging_migrator/migrator.py
Corrected an oversight in the staging migrator tool where a check for table ids in a list of table file names failed due to differences between table ids and table names for table names with spaces.
1. On localhost or test server clone the schemas _testCohort_ and _testCatalogue_  from the data catalogue production server.
2. Create a task in the server's \_SYSTEM\_ environment from the _publish\_resources.py_ script located in data/scripts/catalogue/publish , with dependency `molgenis_emx2_staging_migrator>=11.54.8`. Change the `CATALOGUE` parameter in the script to `testCatalogue`
3. Run this script with `testCohort` as script parameter
4. See that tables with spaces in their name (e.g. Collection events, Subpopulation counts) were not correctly migrated
1. Modify the …
> chore(staging-migrator): corrected mismatch between table ids and table file names

- apps/catalogue/package.json
- apps/tailwind-components/package.json
- re-added the CI only clause for nuxt postinstall, because emx2 doesn't build in windows machines otherwise.
- run gradlew clean run --rerun-tasks
> fix: only do postinstall on ci

- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlTableMetadata.java
Fixes #2842
Where new items cannot be inserted after a column is dropped. This seems to be related to the search trigger.
- update search trigger after column drop
- Not sure if this is the right place to do it
See issue:
https://github.com/molgenis/molgenis-emx2/issues/2842
> fix(emx2): update search trigger after column drop

- apps/molgenis-components/src/components/tables/cellTypes/FileDisplay.vue
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/FileApi.java
Fixes #4833 where files with certain extensions cannot be download
- Added default mimetype for files downloaded via file api
See issue [4833](https://github.com/molgenis/molgenis-emx2/issues/4833)
> fix: added default mimetype when downloading files

- backend/molgenis-emx2-io/src/main/java/org/molgenis/emx2/io/emx2/Emx2Tables.java
- backend/molgenis-emx2-io/src/main/java/org/molgenis/emx2/io/tablestore/TableStoreForCsvInMemory.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/CsvApi.java
- backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
Fixes #1682 
- Always add the mg_draft column when outputting tables via download api's
- go to: https://preview-emx2-pr-4948.dev.molgenis.org/
- create a draft record with validation errors
- download the table or schema via the excel zip or csv api.
- upload the data via the up/download app 
- see the draft records in the table explorer
> fix: always add mg_draft to table output

- tools/directory/CHANGELOG.md
- tools/directory/Pipfile.lock
- tools/directory/README.md
- tools/directory/setup.cfg
- tools/directory/setup.py
- tools/directory/src/molgenis_emx2/directory_client/__init__.py
- tools/directory/src/molgenis_emx2/directory_client/directory_client.py
- Currently the directory-emx2-client contains a work-around to account for data-types, this work-around is not compatible with the latest EMX2-pyclient => adding two lines of code to the filter definition makes the client work with the latest EMX2-pyclient again.
- Run the code, make sure that the EMX2-pyclient is the latest version
> fix(directory): make directory-client compatible with latest pyclient

- docs/catalogue/cat_data-manager.md
- Fix broken links in captions of figures in data manager page of catalogue guide
> fix(catalogue): Fix links in figure captions in docs

- backend/molgenis-emx2-graphql/src/main/java/org/molgenis/emx2/settings/ReportUtils.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/JsonApi.java
Fixes #4930
- Added functionality to fetch reports as objects in back-end
fetch multiple reports via json api:
- https://preview-emx2-pr-4968.dev.molgenis.org/pet%20store/api/reports/json?id=report1,report3
see the difference from master:
- https://emx2.dev.molgenis.org/pet%20store2/api/reports/json?id=report1,report3
> fix(reports): return multiple reports as json

- backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/IriGenerator.java
- backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/PrimaryKey.java
- backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/ColumnTypeRdfMapperTest.java
- backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/IriGeneratorTest.java
- backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/PrimaryKeyTest.java
- backend/molgenis-emx2-rdf/src/test/java/org/molgenis/emx2/rdf/RDFTest.java
- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/RDFApi.java
- backend/molgenis-emx2/src/test/java/org/molgenis/emx2/TestTypeUtils.java
- data/_demodata/applications/datacatalogue/Container.csv
- data/_demodata/shared-examples/Container.csv
- rowId is now part of path instead of query
- ensure character escaping adheres to this
- The column name in a KeyPair still needs to be converted to pascalCase, but this will be a separate PR.
> feat(RDF): RDF rowId is now part of path instead of query

- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/TableMetadata.java
- backend/molgenis-emx2/src/test/java/org/molgenis/emx2/TestTableMetadata.java
- `getColumnByIdentifier()` now checks if column identifier exists in parent tables if not present in itself (similar to `getColumn()`):
https://github.com/molgenis/molgenis-emx2/blob/d9a618676da119865d08a255a6d8a86a12cc6883/backend/molgenis-emx2/src/main/java/org/molgenis/emx2/TableMetadata.java#L329-L336
- tests should succeed
> fix: getColumnByIdentifier now does a recursive check for inherited tables (similar to `getColumn()`)

- apps/nestor-public/src/pages/view-about.vue
- apps/nestor-public/src/pages/view-home.vue
- changed tumor to tumour on several places on home and about pages
- fixed typo in NESTOR RESGISTRY on about page
- create new schema with ERN_DASHBOARD template
- go to the schema and add /nestor-public behind the schema name 
- Check home page for tumor (shouldn't be found)
- Check About page for tumor (shouldn't be found)
- See that the header of the About page is now OK (NESTOR REGISTRY)
> fix: several typos in NESTOR app

- apps/dev-proxy.config.js
- apps/molgenis-components/src/components/tables/RefSideModal.vue
- apps/yarn.lock
- fix: https://github.com/molgenis/molgenis-emx2/issues/4964
- see issue
> fix: ref modal with external schema

- apps/nestor-public/src/pages/view-about.vue
- apps/nestor-public/src/pages/view-documents.vue
- Up till now the documentation page of the nestor-public app, showed an "under construction" message, updated the app to show files that are in the files table
- fix a small typo on the About page (added 'the')
- Create a schema with the ERN_DASHBOARD template
- Upload a file in the files table within that schema
- Goto "yourSchema"/nestor-public/#/documents and see that the file is shown and can be downloaded
> fix: make files available in the NESTOR documents page

- apps/directory/src/components/filters/OntologyFilter.vue
- apps/directory/src/components/filters/base/TreeBranchComponent.vue
- apps/directory/src/components/filters/base/TreeComponent.vue
- fix: #3344 
- known issue: when setting filters through bookmarks (e.g. refreshing) doesn't correctly update the parent of a parent. 
> fix(directory): partial selected state stays partialy selected

- backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java
- backend/molgenis-emx2-webapi/src/test/java/org.molgenis.emx2.web/WebApiSmokeTests.java
- When clearing caches use jooqAsAdmin instead of reusing the current connection. Elevating the admin rights on the current connection gives issues.
- Added a unit test with 10 threads to login simultaneously and check which user is logged in by querying the session
- Delegated getActiveUser to connectionProvider, as some test failed because there was no active user on the connection. I don't understand why this logic existed in the first place? Why parse the postgress user, instead of using the user on the connectionProvider?
- Try the added unit test without the changes to clearCache and see it fail in some cases
> fix: set clearing caches to use separate db connection

- backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/RDFService.java
Minor fixes to RDF API so that equality check works as expected:
- column description range was literal instead of IRI
- Adding the following does not fail pre-fix (maybe due to how InMemoryRDFHandler processes the data?):  
```
assertTrue(
handler.resources.values().stream().map(i -> i.get(RDFS.RANGE)).findFirst().get().stream()
.findFirst()
.get()
.isIRI());
```
Use `curl http://localhost:8080/pet%20store/api/rdf/Pet/column/name` and see the difference.
On master (`cadb470d4328054a2ebd50ee8a217db3be8e6034`):
```
<http://localhost:8080/pet%20store/api/rdf/Pet/column/name> a owl:DatatypeProperty;
rdfs:range "http://www.w3.org/2001/XMLSchema#string";
```
On PR (`d3312abb4aafded47bf31f3e2447e1e2c0c0979f`):
```
<http://localhost:8080/pet%20store/api/rdf/Pet/column/name> a …
```
> fix(RDF): column range was literal instead of IRI

- apps/molgenis-viz/src/components/display/FileList.vue
The ERN dashboards have a page where project members can download documents. There is an issue where documents are opened in the a new tab and not automatically downloaded.
> fix(dashboards): added missing download attribute in file component

- backend/molgenis-emx2/src/main/java/org/molgenis/emx2/utils/TypeUtils.java
- backend/molgenis-emx2/src/test/java/org/molgenis/emx2/TestTypeUtils.java
Added a check for values in a boolean type column if the value can be cast to integer. In that case checks whether the value is either 0 (_false_) or 1 (_true_) and will raise an error otherwise.
- created a unit test in TestTypeUtils.java
> feat(data): boolean data coded as integer 0 and 1 are cast to boolean upon importing

- backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/BasicIRI.java
- backend/molgenis-emx2-rdf/src/main/java/org/molgenis/emx2/rdf/generators/Emx2RdfGenerator.java
- removed (if I'm correct) an unused functionality
- #5039 already removed text describing this
- could not find a shared data model that used `id` as semantic, but maybe I overlooked something?
- `sio:SIO_000396` with correct namespace configuration would achieve exactly the same
- Existing templates should not fail
> fix: removed code related to "id" as semantics

- apps/catalogue/components/content/ContentBlockCatalogues.vue
This is a follow-up PR to molgenis/molgenis-emx2#5150. I noticed that alt text for the logo was not descriptive enough (see [Using alt attributes on img elements](https://www.w3.org/WAI/WCAG22/Techniques/html/H37)). For the catalogue, this should be the name of the catalogue. Given this is a required field, it will accurately describe the image.
> fix(catalogue-app): improved alt text for logos

- apps/central/src/components/SchemaCreateModal.vue
- e2e/tests/central/admin!create-database.spec.ts
- Changed the error message when an invalid schema name was entered from starting with "Table name" to "Schema name"
- Go to emx2.dev.molgenis.org and create a new schema, start with a number => see that the error message starts with: _"Table name must start with a letter, followed by zero or more letters, ..."_
- Go to the preview, again create a new schema starting with a number => see that the error message now starts with:
_"Schema name must start with a letter, followed by zero or more letters, ..."_ which makes more sense.
> chore: fix schema error message

- backend/molgenis-emx2-webapi/src/main/java/org/molgenis/emx2/web/MolgenisSession.java
- backend/molgenis-emx2-webapi/src/test/java/org/molgenis/emx2/web/MolgenisSessionTest.java
- changed the `graphqlPerSchema` attribute of class `MolgenisSession` from `LinkedHashMap` to `ConcurrentHashMap` to prevent `ConcurrentModificationException`
- wrote a new test to verify this behaviour
> fix(graphql): concurrent GraphQL queries do not clash

- apps/updownload/src/components/Import.vue
closes #5239 
n.b. I think we are now deciding that we should use absolute paths in hyperlinks to make it more robust. I think I am at peace with that now :-)
n.b. this fix is also being tested in #5231 because we found it there also.
> fix(updownload): download URLs were missing path to the schema

- apps/tailwind-components/components/Modal.vue
- apps/tailwind-components/components/form/AddModal.vue
- apps/tailwind-components/components/form/DeleteModal.vue
- apps/tailwind-components/components/form/EditModal.vue
- apps/tailwind-components/components/table/TableEMX2.vue
This PR introduces a fix in the row delete/edit modal components where if the mouse was hovered on a different window, display, or program, the modal would close. This was caused by a conflict in the row hover actions and the fact that the modals were rendered in each row. Central modals should be used instead as it is more efficient rather than generating modals and modal content for each row.
This PR is part of molgenis/GCC#1579
> [!NOTE]
> There's still an issue with buttons and semantics. In the next PR, we will likely reposition the buttons so that they are placed in the first cell in each row. Currently, the buttons are not accessible and do not correspond to the primary key(s). I attempted to fix this in this PR, but it was decided to move this in the next PR to keep this one …
> fix: row edit and delete modals no longer close on mouseout

- apps/tailwind-components/assets/css/main.css
This PR is part of molgenis/GCC#1579
- In the preview, navigate to the button story in the new components gallery
- Run the WAVE browser extension. Note the contrasts errors of the filterWell button and compare with the emx2 dev demo
> fix(tw): increased color contrast of filter well button text

- apps/molgenis-components/src/client/client.ts
- apps/molgenis-components/src/components/utils.test.ts
- apps/molgenis-components/src/components/utils.ts
Fixes #5204
- Added test if key = number in utils getKey (from row)
> fix(forms): if key is of type integer, correctly resolve the key in Edit modal

- backend/molgenis-emx2-io/src/main/java/org/molgenis/emx2/io/ImportTableTask.java
Closes #5350 
when uploading a csv with empty values at auto_id column skip validation
> fix(upload): when uploading a csv with empty values at auto_id column skip validation
